src/org/omegat/gui/preferences/view/EditingBehaviorPanel.form, src/org/omegat/gui/preferences/view/EditingBehaviorPanel.java
- OmT development ML [[OmTdev] inconsistency in preference dialog EditingBehaiviorPanel](https://sourceforge.net/p/omegat/mailman/message/37629789/)
- Add paraMarkText and paraMarkLabel gui component on panel
- Re-generate java source from EditingBehaviorPanel.form
=> Preference: fix inconsistency form and generated java source

release/readme.txt
Change project leader role and document manager role.
=> change roles

release/changes.txt, src/org/omegat/Main.java, src/org/omegat/core/data/RealProject.java, src/org/omegat/filters2/AbstractFilter.java, src/org/omegat/filters2/IAlignCallback.java, src/org/omegat/filters2/moodlephp/MoodlePHPFilter.java, src/org/omegat/filters2/text/bundles/ResourceBundleFilter.java, src/org/omegat/filters2/text/ini/INIFilter.java, src/org/omegat/util/TMXWriter2.java, test/src/org/omegat/core/data/TmxComplianceBase.java
Change ``AbstractFilter#alignFile`` signature.
- Link: https://sourceforge.net/p/omegat/feature-requests/1408/
- Title: In mode=console-align, generate tmx with mutiples translations
- Produce TMX that have same source string with multiples translations
- Change TMXWriter2#writeEntries to accept Map<EntryKey, TMXEntry> data.
- Update RealProject#align to return Map<EntryKey, TMXEntry>
- Update align to change behavior according to project configuration.
Merged the proposal #32 onto current master and adjust to current TMXEntry definition.
=> [RFE#1408] CLI: new option in mode=console-align

src/org/omegat/core/team2/impl/GITExternalGpgSigner.java, src/org/omegat/core/team2/impl/GITRemoteRepository2.java
- Link: 
- Title: 
- When `user.signingkey` is specified, enable signer.
- Fix detection of gpg command path
- Add @NotNull annotation
=> Team: Git: fix gpg signer enable condition

build.gradle
- Link: 
- Title: 
- org.apache.pdfbox@2.0.26
- fifesoft
- rsyntaxtextarea@3.2.0
-  rstaui@3.2.0
-  languagesupport@3.1.4 
- autocomplete@3.2.0
- Drop transient dictzip
=> Gradle: bump versions of dependencies

.docker-compose.yml, src/org/omegat/core/team2/impl/SVNAuthenticationManager.java, test-integration/docker/client/Dockerfile, test-integration/docker/server/Dockerfile, test-integration/src/org/omegat/core/data/TestTeamIntegration.java, test-integration/src/org/omegat/core/data/TestTeamIntegrationChild.java
This proposal add subversion server on integration-test docker tool setts.
- Link: 
- Title: 
-
-
-
=> Integration-test: support subversion test with docker

src/org/omegat/Bundle.properties, src/org/omegat/core/data/RealProject.java, src/org/omegat/util/FileUtil.java
Refactoring FileUtil#removeOldBackups and  Update RealProject#loadTranslations
to  check backup file creation and record it as log message.
Improve safety and visibility of backup file creation
- Link: 
- Title: 
- use lambda in removeOldBackup method to improve code clearer
- check return value from backup method and record it in log
=> Update FilUtil#backup, #removeOldBackup and  its caller

src/org/omegat/core/data/ProjectProperties.java
=> Clean unused imports

src/org/omegat/Bundle.properties, src/org/omegat/Bundle_ja.properties, src/org/omegat/gui/properties/ISegmentPropertiesView.java, src/org/omegat/gui/properties/SegmentPropertiesArea.java, src/org/omegat/util/Preferences.java
- Bug fix
-  GUI: Comment is shown on both Comment and Segment Properties pane
*  https://sourceforge.net/p/omegat/bugs/1119/
- Show existence flag of comment instead of its content on segment properties pane
- Update flash notifier default keys
=> Fix duplicated comment display

src/org/omegat/Bundle.properties, src/org/omegat/gui/glossary/FindGlossaryThread.java, src/org/omegat/gui/glossary/GlossaryAutoCompleterView.java, src/org/omegat/gui/glossary/GlossaryManager.java, src/org/omegat/gui/glossary/GlossarySearcher.java, src/org/omegat/gui/glossary/GlossaryTextArea.java, src/org/omegat/util/Preferences.java, test/src/org/omegat/gui/glossary/FindGlossaryThreadTest.java
-  Glossary pane sorting
* https://sourceforge.net/p/omegat/feature-requests/1606/
- sort entries when result is set
-
-
=> GlossaryPane: configurable for sort order of entries 

.gitignore
Pick from @brandelune manuel5.n branch to organize commits
=> Update gitignore to include emacs backup files

doc_src/build.xml
pick from @brandelune manuel5.n branch
=> TOC to 3 levels

src/org/omegat/gui/main/MainWindowMenu.java
- Move project>import and project>wiki import bellow save menu
- Move edit>overwrite machine translation below insert souce
pick from @brandelune manuel5.n changes
=> Menu: move some items on main menu tree

src/org/omegat/Bundle.properties
- Use shorter and simpler messages
- Update menu item with shorter representation
pick from @brandelune manuel5.n branch
=> Update menu item and messages

doc_src/en/App_Glossaries.xml, doc_src/en/App_Segmentation.xml, doc_src/en/App_ShortCuts.xml, doc_src/en/Dialogs_ProjectProperties.xml, doc_src/en/Introduction.xml, doc_src/en/OmegaT5_EditorsPanes.xml, doc_src/en/OmegaT5_Menus.xml, doc_src/en/OmegaT5_Preferences.xml, doc_src/en/OmegaT5_WindowsAndDialogs.xml, doc_src/en/Windows_SourceFilesList.xml, doc_src/en/Windows_TextReplace.xml
There were a number of issues in the FO file that kept the PDF from building. The original DocBook was fixed to ensure that the FO file is valid and produces a PDF file.
This PR does not address issues in the PDF itself, like font use or layout.
=> Ensure the PDF builds properly

src/org/omegat/core/data/ProjectProperties.java, src/org/omegat/gui/glossary/TransTipsPopup.java, test/src/org/omegat/core/data/ProjectPropertiesTest.java
- Add tests
- Robust against wrong values
=> Improve ProjectProperties#setExportTmLevels

doc_src/en/HowTo_Run.xml
=> fix command line example indent

doc_src/en/App_ConfigurationFolder.xml, doc_src/en/HowTo_Install.xml, doc_src/en/HowTo_Run.xml
[documentation]
- Improve wording and fix incomplete sentences.
- Unify use of "parameters" vs. "options": Java parameters, OmegaT options.
=> Updates to command line launch section of manual.

src/org/omegat/Bundle.properties, src/org/omegat/gui/editor/EditorController.java, src/org/omegat/gui/editor/IEditor.java, src/org/omegat/gui/main/MainMenuShortcuts.mac.properties, src/org/omegat/gui/main/MainMenuShortcuts.properties, src/org/omegat/gui/main/MainWindowMenu.java, src/org/omegat/gui/main/MainWindowMenuHandler.java, src/org/omegat/gui/scripting/ConsoleBindings.java, test-integration/src/org/omegat/core/data/TestTeamIntegrationChild.java, test/src/org/omegat/core/TestCore.java
Re-create commits and PR of #294
=> Recreated PR "Added a call to select the current source text"

doc_src/en/Dialogs_ProjectProperties.xml, doc_src/en/OmegaT5_Preferences.xml, doc_src/en/Windows_TextReplace.xml, doc_src/en/Windows_TextSearch.xml, doc_src/en/index.xml, src/org/omegat/Bundle.properties
Make sure changes in Bundle.properties are reflected in the manual, and vice-versa.
[documentation]
- Apply consistent wording and capitalization to UI elements between Bundle.properties and the manual.
- Tweak the wording of some UI messages or strings.
=> Make UI and manual capitalization consistent.

src/org/omegat/gui/main/MainMenuShortcuts.mac.properties
https://sourceforge.net/p/omegat/bugs/1127/
=> Cmd+Shift+Q conflicts with

build.gradle, docs_devel/Release.md
OmegaT web site has already expired JNLP signature and the project plan to remove webstart support.
- Link: 
- Title: 
-
-
-
=> Gradle: Drop jnlp build

doc_src/en/App_PostProcessingCommands.xml, doc_src/en/Dialogs_ProjectProperties.xml, doc_src/en/OmegaT5_Appendices.xml, doc_src/en/OmegaT5_Preferences.xml, src/org/omegat/core/team2/ProjectTeamSettings.java, src/org/omegat/core/team2/RebaseAndCommit.java, src/org/omegat/core/team2/RemoteRepositoryProvider.java, src/org/omegat/core/team2/TeamSettings.java, src/org/omegat/core/team2/TeamTool.java
New documentation for the postprocessing commands.
=> postprocessing commands docs @Gregory Vigo

src/org/omegat/Bundle.properties
Improve the wording and fix inconsistent capitalization in a few UI strings.
=> Fix inconsistent spelling and improve wording.

doc_src/en/App_ShortCuts.xml, doc_src/en/HowTo_UseTM.xml, doc_src/en/Menus_GoTo.xml, doc_src/en/OmegaT5_Preferences.xml, doc_src/en/OmegaT5_ProjectFolder.xml, src/org/omegat/Bundle.properties
Documentation for the functions described here:
https://github.com/omegat-org/omegat/pull/370
I've also changed the names of the menu items following my comment in the above PR.
=> Documentation for the x-goto functions

docs_devel/docs/03.GitWorkFlows.md, docs_devel/docs/23.CoreMethods.md, docs_devel/docs/30.CodingStyles.md, docs_devel/docs/33.TestAndCoverage.md, docs_devel/docs/index.md
- Documentation 
404 error is reported on mastodon community.
- Fix 404 error
- Add core method section
- Add test and coverage section
- Add git workflow section
=> docs_devel: Fix and update contribution guide

test/src/org/omegat/core/dictionaries/LingvoDSLTest.java
Improve test coverage
N.A.
- Add test case that use predictive search
=> Update LingvoDSLTest: add predictive search case

src/org/omegat/gui/align/AlignPanelController.java
- #1360 Font settings in Aligner
* https://sourceforge.net/p/omegat/feature-requests/1360
- Aligner: update font configuration by `registerFontChangedListener` in dynamic manner.
- Always use a font from `MainWindow#getApplicaitonFont` method instead of creation of new font object
- Refactoring;
- Avoid empty `if` body.
- Avoid ?-operator
- Add javadoc param descriptions
- Also removes invalid param javadoc tags
- Spotless code formatting
=> aligner: Improve font setting and refactoring

src/org/omegat/gui/search/SearchWindowController.java
- Font Rendering issue in OmegaT (Santali)
* https://sourceforge.net/p/omegat/bugs/1133/
-  set configured font to search / replace field on search dialog 
-  register font change event listener that update search dialog fonts
=> Fix search window field font

src/org/omegat/gui/filters2/FiltersCustomizerController.java
Put sort order for local / global file filter list in preferences.
Related #356
=> GUI: filter sort order of filter list

src/org/omegat/core/machinetranslators/AbstractMyMemoryTranslate.java, src/org/omegat/core/machinetranslators/ApertiumTranslate.java, src/org/omegat/core/machinetranslators/BaseCachedTranslate.java, src/org/omegat/core/machinetranslators/BaseTranslate.java, src/org/omegat/core/machinetranslators/BelazarTranslate.java, src/org/omegat/core/machinetranslators/DeepLTranslate.java, src/org/omegat/core/machinetranslators/Google2Translate.java, src/org/omegat/core/machinetranslators/IBMWatsonTranslate.java, src/org/omegat/core/machinetranslators/YandexCloudTranslate.java
refactor
Suggested in PR #470
- Introduce `BaseCachedTranslate` class that has Cache layer.
- Change `BaseTranslate` not to handle cache
=> refactor(mt): introduce BaseCachedTranslate class

src/org/omegat/core/data/DataUtils.java, src/org/omegat/gui/main/MainWindow.java, src/org/omegat/gui/matches/MatchesTextArea.java
- Color the fuzzy matches from /tm/mt
* https://sourceforge.net/p/omegat/bugs/1144
- check if a fuzzy match comes from the /tm/mt folder before being inserted
- refactor the code that checks if a NearString comes from /tm/mt (the clunky test was also used in MainWindow)
- spotlessChangedApply on the 3 modified files
=> fix: Color the fuzzy matches from /tm/mt

docs_devel/docs/90.ReleaseProcedure.md
- Fix typo on docs_devel/docs/90.ReleaseProceddure.md
=> doc(devel): fix typos of release procedure memo

doc_src/en/manualvariables.mod, doc_src/en/version.properties
The version number mentioned in the documentation (First Steps) was not updated.
master currently corresponds to 6.1
https://sourceforge.net/p/omegat/mailman/message/37802787/
=> Update version number for the documentation

src/org/omegat/Bundle.properties, src/org/omegat/gui/main/ProjectUICommands.java, src/org/omegat/util/FileUtil.java
- Title
* URL
- Fix degrade on #415
- ref;  https://github.com/omegat-org/omegat/pull/415#issuecomment-1449046191
- When project is not a team project, there does not produce a backup file when user does not change property.
=> Improve handling of backup file of omegat.project 

src/org/omegat/core/data/ProjectProperties.java, src/org/omegat/core/data/RealProject.java, src/org/omegat/core/segmentation/SRX.java, src/org/omegat/core/segmentation/defaultRules.srx, src/org/omegat/util/Preferences.java
=> Support for SRX format

docs_devel/docs/34.IntegrationTest.md, test-integration/docker/client/Dockerfile, test-integration/docker/server/Dockerfile
Spell check developer memo.
- Title
* URL
-
-
-
=> docs_devel: fix typos and copyright header around integration test

src/org/omegat/Bundle.properties, src/org/omegat/gui/main/MainWindowAccessTools.java
Improve Source File combo
- Improve souce file combobox in newUI access tool
=> newUI: show number of entries  in Source File ComboBox

docs_devel/docs/02.HowToBuild.md, docs_devel/docs/05.Versioning.md, docs_devel/docs/90.ReleaseProcedure.md, docs_devel/docs/92.CodeSigning.md, docs_devel/docs/index.md
- Developers note section, Release procedure is updated refalect to a updated CI/CD script that integrated with GitHub.
- I also added  05.Versioning.md that is refered from release procedure section.
- Title
* URL
-
-
-
=> docs_devel: update release procedure and code signing details

tipoftheday/docs/tips/en/change_theme.html, tipoftheday/docs/tips/en/howto_download_dictionary.html, tipoftheday/docs/tips/en/project_folder_tm_auto.html, tipoftheday/docs/tips/en/project_folders.html, tipoftheday/docs/tips/en/shortcut_note.html, tipoftheday/docs/tips/en/tips.yaml, tipoftheday/docs/tips/ja/shortcut_note.html, tipoftheday/docs/tips/tips.css
- Add more contents
- Update CSS
- fix some contents
- Title
* URL
-
-
-
=> feat: improve tip of the day

src/org/omegat/Bundle.properties, src/org/omegat/core/data/RealProject.java, src/org/omegat/core/statistics/Statistics.java, src/org/omegat/util/TMXReader2.java
This detect XMLStreamException when loading the project. An error will be happened when filters.xml or segmentation.srx corruption. OmegaT has no way to investigate a reason, we can only show a better message.
- Better error message for omegat.project failure
* https://sourceforge.net/p/omegat/feature-requests/1696/
-
-
-
=> feat: detect XMLStreamException

azure-pipelines.yml, build.gradle, ci/azure-pipelines/build_steps.yml, ci/azure-pipelines/publish_release.yml, ci/azure-pipelines/publish_weekly.yml
- Update build_steps.yml
- Update not to use PublishBuildArtifacts task
- Update to use PublishPipelineArtifact task
- Add publish_release.yml and publish_weekly.yml template
- Trigger schedule for every saturday
- Gradle: add printVersion task
-
-
-
=> chore(ci): publish weekly and release

build.gradle
ref. hunspell project issue "libhunspell.dylib not signed" https://gitlab.com/dumonts/hunspell-java/-/issues/7
- Title
* URL
- fix signature target to *.dylib
-
-
=> chore(gradle): code signing *.dylib

doc_src/en/App_Segmentation.xml, doc_src/en/App_ShortCuts.xml, doc_src/en/HowTo_Run.xml, doc_src/en/HowTo_UseTeamProject.xml, doc_src/en/Menus_GoTo.xml
Documentation fix
Missing words, typing mistakes, and punctuation fix
=> Documentation fixes

doc_src/en/App_Regex.xml
=> Digits and letters

doc_src/en/App_FileFilters.xml
=> Added an "s" to "these option"

doc_src/en/App_FileFilters.xml, doc_src/en/App_Regex.xml, doc_src/en/App_Segmentation.xml, doc_src/en/App_ShortCuts.xml, doc_src/en/HowTo_Run.xml, doc_src/en/HowTo_UseTeamProject.xml, doc_src/en/Menus_GoTo.xml
backports document error fix into base branch `releases/6.0`.
- backport #572 
- backport #566
- backport #565
-
The PR is created by cherry-picking commits from master branch into topic branch.
When cherry-picking, authors and PR numbers are preserved in commits.
=> docs(6.0): backport docs updates202305

build.gradle, src/org/omegat/gui/dialogs/AboutDialog.java, src/org/omegat/util/MemoryUtils.java, src/org/omegat/util/TMXWriter.java, src/org/omegat/util/xml/DefaultEntityFilter.java, src/org/omegat/util/xml/XMLAttribute.java, src/org/omegat/util/xml/XMLBlock.java, src/org/omegat/util/xml/XMLReader.java, src/org/omegat/util/xml/XMLStreamReader.java, test/src/org/omegat/util/XMLStreamReaderTest.java
Java17 compatibility changes.
Add forRemoval and since parameter for @Deprecated annotation
These class will be removed in future 6.x release.
jdeprscan is a Java genuine utility to check deprecation
The plugin help us running the tool by command line
./gradlew jdeprscan --Pjdeprscan-release=11
It is reported for an usage of deprecated method isAccesible()
by jdeprscan java toolbox utility.
We update the class to replace with a new method introduced in Java 9.
=> [Java17] refactor unused classes

.github/workflows/checkstyle-annotate.yml
This github actions just run gradle checkstyleMain and checkstyleTest and send annotation to github API.
When reviewing Pull-Request on github project page, you can see checkstyle warnings on code diff page.
=> Help github review process for checkstyle

release/changes.txt, src/org/omegat/Version.properties
next git tag will be like v5.8.0_1
=> chore: prepare for release 5.8.0

build.gradle
- Build and release changes 
- Update `build.gradle`  target java to 11
=> [6.0] chore: bump target java to 11

src/org/omegat/Bundle.properties, src/org/omegat/core/data/RealProject.java
- Improve behavior on BUGS#1168 "OmegaT cannot load a project and error dialog with FileSystemLoopException"
- OmegaT cannot load a project and error dialog with FileSystemLoopException
* Bugs: https://sourceforge.net/p/omegat/bugs/1168
-
-
-
=> [6.0]  [BUGS#1168] feat:error message for loop link

azure-pipelines.yml, build.gradle, ci/azure-pipelines/build_steps.yml
- add explicit write permission to build folder
- Change name of bash script
- Change task order of windows build
- change weekly build schedule
=> chore(ci): update package build script

azure-pipelines.yml, build.gradle, ci/azure-pipelines/build_steps.yml, ci/azure-pipelines/publish_release.yml, ci/azure-pipelines/publish_weekly.yml, ci/buildiscon.sh, ci/iscc
- There is a permission issue on original amake/innosetup:innosetup6 container
- Tweak container image
- build local container give root privilege to user inside container
- tag is omegat/innosetup:innosetup6
- Automatically run docker build when task winJRE called
- And update run condition
=> chore: tweak winJRE/winJRE64 builder

src/org/omegat/util/FileUtil.java
=> fix(util): fix always to return GMT lastModifiedDate string

doc_src/fr/App_ApplicationFolder.xml, doc_src/fr/App_ConfigurationFolder.xml, doc_src/fr/App_FileFilters.xml, doc_src/fr/App_Regex.xml, doc_src/fr/App_ShortCuts.xml, doc_src/fr/Dialogs_ProjectProperties.xml, doc_src/fr/HowTo_Run.xml, doc_src/fr/InstantStartGuide.xml, doc_src/fr/Menus_Project.xml, doc_src/fr/Menus_Tools.xml, doc_src/fr/Menus_View.xml, doc_src/fr/OmegaT_EditorsPanes.xml, doc_src/fr/OmegaT_Preferences.xml, doc_src/fr/OmegaT_ProjectFolder.xml, src/org/omegat/Bundle_fr.properties
FR fix to master that corresponds to the state of 6.0 (with 6.1 version numbers)
=> 6.1 FR fix

release/changes.txt
https://sourceforge.net/p/omegat/feature-requests/1702/
=> macOS integration

doc_src/ca/version_ca.properties, doc_src/de/version_de.properties, doc_src/index_template.html
dev ML
https://sourceforge.net/p/omegat/mailman/message/37861387/
- Update index template to remove PDF link
- Update ca and de version property
-
=> [6.0] docs(webManual): update index_template.html and version_(ca|de).properties

build.gradle
- Set javadoc options.locale to en_US
- Set javadoc options.encoding to UTF-8
- Set jFlags user.language to en
- Configure javadoc behaviors
dev ML
https://sourceforge.net/p/omegat/mailman/message/37861403/
- Update javadoc section of build.gradle
=> [6.0] chore(gradle): javadoc configurations

src/org/omegat/gui/common/EntryInfoPane.java, src/org/omegat/gui/editor/Document3.java, src/org/omegat/gui/editor/EditorController.java, src/org/omegat/gui/editor/SegmentBuilder.java, src/org/omegat/gui/matches/MatchesVarExpansion.java, src/org/omegat/gui/properties/SegmentPropertiesArea.java, src/org/omegat/help/Help.java, src/org/omegat/util/Language.java, test/src/org/omegat/util/LanguageTest.java
PR #519 has many refactoring and style changes with core fix.
To clarify things, I produce style/refactoring only change from #519.
After rebase on the refactoring/styles, #519 can be reviewed.
Clarification for complex pull-request.
- style
- refactoring that use lambda
- Introduce utility method to get language/country of default locale
All commits are marked as  authored by @damien-rembert
=> refactoring/style: changes for preparation of rtl fix changes in #519

src/org/omegat/gui/editor/EditorController.java, src/org/omegat/gui/editor/SegmentBuilder.java
Preparation for PR #519  for review
- remove unused method
- style update
=> refactor/style:  editor classes

src/org/omegat/gui/main/ProjectUICommands.java
- Use repository mappings in a local project 
- https://sourceforge.net/p/omegat/feature-requests/1448/
- Fix team project detection
- resolved RFE#1448
=> [RFE#1448] feat: support repository mapping in a local project

azure-pipelines.yml, ci/azure-pipelines/build_steps.yml
=> chore(ci): update jre versions

build.gradle
- update gradle config to bundle subprojects jar files in distribution section
=> [6.1] chore: bundle modules in dist files

azure-pipelines.yml, build.gradle, ci/azure-pipelines/build_steps.yml, ci/azure-pipelines/publish_release.yml, ci/iscc
After release 6.0.0, next 6.0.1 will released with new GitHub/Azure CI configuraiton.
dev ml: https://sourceforge.net/p/omegat/mailman/message/37847970/
- feedback from improvements in master branch
- Patch ISCC about permission problem
- Update release and publish script
- Avoid duplicated tasks
REF #606
=> [6.0.1] chore(ci): update ci build

test/data/project/entities.project, test/data/project/team.project, test/data/project/teamMapWithExclude.project, test/data/project/teamWithMap.project, test/src/org/omegat/util/ProjectFileStorageTest.java
- Read with entities
- Write team project - with mapping - with excludes attributes
Add test  to check ProjectFileStorage write cases.
maser branch changes dependency for XML handling libraries.
These tests help keeping compatibility between versions.
=> [6.0] test: ProjectFileStorage cases

doc_src/en/Menus_Options.xml
=> docs: typo maches -> matches

azure-pipelines.yml, ci/azure-pipelines/build_steps.yml, ci/azure-pipelines/publish_weekly.yml
- Make CI configuration mostly identical with master branch
- Difference: no integration-test on releases/6.0 branch
-  Update azure-pipelines.yml as most identical with master branch
- Add publish_weekly
=> chore(ci): make identical with master

doc_src/en/Menus_Options.xml
=> typo maches -> matches

doc_src/en/Menus_Edit.xml
Modification taken from 5.8/6.0
=> Expand on "alternative translation" explanation

azure-pipelines.yml, build.gradle, ci/azure-pipelines/build_steps.yml, ci/azure-pipelines/publish_weekly.yml
Current CI has a problems
1. It does not produce jre bundled version
2. Unwanted OmegaT-win.zip file
- Fix windows binary build configuration on build.gradle
- Fix CI script always to download java 11
=> chore(ci/build): fix windows build issues

release/changes.txt, test-integration/docker/server/entrypoint.sh
remove /var/run/apache2/* before starting
- Integration test(docker) failure with 503
* https://sourceforge.net/p/omegat/bugs/1199/
-
-
-
=> chore(integ-test): update server entrypoint.sh

build.gradle
- Build package bundled with JRE for aarch64  linux
-
-
=> chore: linux aarch64 jre bundle

doc_src/en/HowTo_Install.xml
Here's a proposal to fix the errors in the _Install OmegaT_ section of the manual caught by Hiroshi and reported on the [development mailing list](https://sourceforge.net/p/omegat/mailman/message/37873374/).
Once this is finalized, I'll also make the relevant changes for the 5.8/6.0 releases branches.
=> Update phrasing in installation section

doc_src/en/Menus_Edit.xml
https://sourceforge.net/p/omegat/mailman/message/37863465/
The text is taken from Marc's How-to.
https://sourceforge.net/p/omegat/documentation/411/
=> docs: Explanation about alternative translations

build.gradle, machinetranslators/apertium/src/test/java/org/omegat/core/machinetranslators/ApertiumTranslateTest.java, machinetranslators/deepl/src/test/java/org/omegat/core/machinetranslators/DeepLTranslateTest.java, machinetranslators/google/src/test/java/org/omegat/core/machinetranslators/Google2TranslateTest.java, machinetranslators/ibmwatson/src/test/java/org/omegat/core/machinetranslators/IBMWatsonTranslateTest.java, machinetranslators/mymemory/src/test/java/org/omegat/core/machinetranslators/MyMemoryTranslationTest.java, test/fixtures/org/omegat/core/TestCore.java, test/fixtures/org/omegat/core/TestCoreWireMock.java
Reduce unnecessary log messages when running test.
refactor
- Separate WireMock related class from TestCore for test performance
- Test cases which need WireMock facility, it should inherit from TestCoreWireMock
- Add dependency for SLF4J for test-fixtures
=> refactor(test): introduce TestCoreWireMock class

src/org/omegat/filters3/xml/resx/ResXFilter.java, test/data/filters/ResX/Simple.resx, test/src/org/omegat/filters/ResXFilterTest.java
Improve ResX unit test with "translate" test case.
QA
- Title
* URL
- There is no feature change.
- Compare whether output is identical with original as in XML.
=> fix(resx): avoid NPE and add test cases

release/changes.txt, src/org/omegat/Bundle.properties, src/org/omegat/core/threads/SaveThread.java, src/org/omegat/util/Log.java
Update SaveThread class
- Solve BUGS#1207
- Critical errors are logged, but no longer shown to the user
* https://sourceforge.net/p/omegat/bugs/1207/
- Catch OOM during auto saving, and exit for emergencies
- Catch network error and leave a message-
=> [BUGS#1207] fix: catch OOM during auto saving

tipoftheday/src/main/java/org/omegat/gui/tipoftheday/OmegaTTipOfTheDayModel.java, tipoftheday/src/main/java/org/omegat/gui/tipoftheday/TipOfTheDayController.java, tipoftheday/src/main/java/org/omegat/gui/tipoftheday/TipOfTheDayDialog.java, tipoftheday/src/main/java/org/omegat/gui/tipoftheday/TipOfTheDayUtils.java
- Set default on close button
- set InputMap; left, right, escape
TipOfTheDay dialog is disabled in 6.1 development cycle so the change does not any sub effect in 6.1 release.
=> [6.2] refactor(tipfotheday): add dialog class

src/org/omegat/Bundle.properties
Update error message to suggest users to fix their TMX using validation tool.
- Fails to load TM using <ph> tags
- https://sourceforge.net/p/omegat/bugs/1090
- Update an error message in Bundle
=> [BUGS#1090] fix: improve error message.

test-integration/docker/client/Dockerfile, test-integration/docker/client/entrypoint.sh, test-integration/docker/server/entrypoint.sh
Fix issues in integration test.
- server: rm old id_rsa file at first
- client: 
- insert sleep before copy id_rsa
- install adoptium openJDK 11 in image to avoid downloading when execution
=> fix(integration-test): improve docker execution

build.gradle
- [Duplication of some files in the distributed packages](https://sourceforge.net/p/omegat/bugs/1123/)
* https://sourceforge.net/p/omegat/bugs/1123/
- Change install target folders and exclude filters
=> [BUGS#1123] fix: remove duplicated document installation

build.gradle, tipoftheday/build.gradle
make totd module as fat jar.
-
-
-
=> chore: build tipofthday module as fatjar

build.gradle, src/org/omegat/gui/scripting/ScriptRunner.java, src/org/omegat/gui/scripting/ScriptingWindow.java, src/org/omegat/gui/scripting/ScriptsMonitor.java, test/src/org/omegat/gui/scripting/ScriptingTest.java
refactor
- refactor Scripting code to avoid initialization of scripting engine instance in static context
-
=> refactor: avoid script engine initialization in static context

release/win32-specific/OmegaT.iss
Weekly release CI failed to build windows binary.
https://dev.azure.com/omegat-org/OmegaT/_build/results?buildId=6442&view=results
- remove doc-license.txt from windows specific release configuration, which is now placed under docs
=> fix(ci): iscc failed with a file not found

aligner/src/main/java/org/omegat/gui/align/AlignFilePicker.form, aligner/src/main/java/org/omegat/gui/align/AlignFilePicker.java, aligner/src/main/java/org/omegat/gui/align/AlignMenuFrame.form, aligner/src/main/java/org/omegat/gui/align/AlignMenuFrame.java, aligner/src/main/java/org/omegat/gui/align/AlignPanel.form, aligner/src/main/java/org/omegat/gui/align/AlignPanel.java, aligner/src/main/java/org/omegat/gui/align/AlignerModule.java, aligner/src/main/java/org/omegat/gui/align/EditingPanel.form, aligner/src/main/java/org/omegat/gui/align/EditingPanel.java, aligner/src/main/resources/org/omegat/gui/align/Bundle.properties, aligner/src/test/java/org/omegat/gui/align/BundleTest.java, aligner/src/test/java/org/omegat/gui/align/CopyrightTest.java, build.gradle, test/fixtures/org/omegat/util/CommonVerifications.java
Fix align tool error reported in
https://github.com/omegat-org/omegat/pull/729#issuecomment-1733383055
-
- Add BundleTest and Copyright Test for align tool module
- Fix bundle errors
-
=> fix: Bundle reference error on align tool as module

build.gradle, gradle/utils.gradle, src/org/omegat/Version.properties
- Rewrite git utilities to be gradle configuration-cache aware
- Rewrite deprecated application convention
=> chore: refactor: Gradle cache support and rewrite deprecated convention

Plugins.properties, build.gradle, src/org/omegat/core/team2/RemoteRepositoryFactory.java, src/org/omegat/core/team2/impl/FileRepository.java, src/org/omegat/core/team2/impl/GITRemoteRepository2.java, src/org/omegat/core/team2/impl/HTTPRemoteRepository.java, src/org/omegat/core/team2/impl/SVNRemoteRepository2.java, src/org/omegat/filters2/master/PluginUtils.java
refactor
- #1715 Make repository connectors as plugin
* https://sourceforge.net/p/omegat/feature-requests/1715/
- Add plugin type "repository"
- Introduce RemoteRepositoryFactory.addRepositoryConnector func
- make file, git, svn and http connectors as plugin
- Set description attribute for new plugin type
DEV-ML https://sourceforge.net/p/omegat/mailman/message/37803705/
=> feat: make repository connectors as plugin

src/org/omegat/gui/main/MainWindowUI.java, src/org/omegat/util/Preferences.java
- Drop screen_* keys that keep main window geometry in long ago.
refactor 
- 
-
-
=> fix: remove unused preferences key and updates

src/org/omegat/Bundle.properties
Here's a proposed updated wording for the blocks from Issue #694.
Let me know if you also want to backport them to 5.8 and 6.0.
=> chore: Updated wording for UI blocks

build.gradle, ci/iscc, ci/osslsigncode
- Allow signing with docker image
- Add USBDEV environ variable for ci/osslsigncode
- Add `winCodesignDevice` property to specify USBDEV
- Allow using nerdctl instead of docker command
- Refactoring `$buildDir` reference with `layout.buildDirectory` syntax
=> chore: improve windows binary build, and build.gradle refactoring

build.gradle
Refactoring build.gradle to improve clarification for code maintenance 
- Build/release
- refactoring
- remove `linux64` and `linuxArm64` distribution definition
- register `installLinux*Dist` and `linux*DistTarBz` tasks in logic as similar as windows tasks
=> chore: refactor build.gradle for linux distributions

settings.gradle
- Broken gradle tasks on Debian
-  https://sourceforge.net/p/omegat/bugs/1217/
- Add foojay resolver plugin for build.gradle
=> chore: configure foojay toolchains resolver

.github/workflows/checkstyle-annotate.yml, ci/github/problem-matcher.json
- replace actions market recipe to simple problem-matcher
- Update problem-matcher.json to recognize checkstyle
=> chore(ci): update checkstyle annotation

test-integration/docker/client/Dockerfile, test-integration/docker/client/entrypoint.sh
=> chore: Update gradle version in integration-test

ci/osslsigncode
- update ci/osslsigncode
- Bulid container image locally
- add --pull=never not to ask docker.io server
- fix logics
=> chore: osslsigncode container execution

ci/azure-pipelines/build_steps.yml
=> chore(ci): bump bundle JRE 17.0.9+9

build.gradle, ci/azure-pipelines/build_steps.yml, config/checkstyle/suppressions.xml, docs_devel/docs/93.BuildingInstallerPackage.md, gradle/libs.versions.toml, release/changes.txt, src/org/omegat/util/StaticUtils.java
- #1721 Provide package "deb" and "rpm" as distribution format for linux
- https://sourceforge.net/p/omegat/feature-requests/1721/
- Add gradle jpackage plugin
- Add task linuxDebDist and linuxRpmDist
- produce debian and rpm package.
- discussed in [dev-ml](https://sourceforge.net/p/omegat/mailman/omegat-development/thread/zmuMdSRyYxr_rUZWYLNakRIHNiS71-ks7ww2LuUvQSCQPda1YdUqgVRLFdjFHxltgYQwGXGunV0FFuV3dNkqQDgN54HRIDN4qGrqPstE69s%3D%40northside.tokyo/#msg46693967)
- jpackage tool bundles JRE from a  java runtime which gradle run on. Because Azure pipelines CI environment uses Ubuntu 22.04, it bundles runtime from ubuntu package openjdk-17-jdk 17.0.8+1 version.
=> [RFE#1271] feat: provide  linux standard packages

build.gradle
Fix build failure of mac distribution 
- Remove no needed `distributions/mac` configuration that cause failure.
=> chore: gradle: fix merge error of PR#807

ci/iscc, doc_src/docgen
=> [BUGS#1228] chore: workaround innosetup docker permission issue

build.gradle
- Avoid incompatible clauses in build.gradle against configuration-cache
=> chore: update genMac task

gradle.properties
Explicitly define gradle cache features
-  explicitly disable configuration cache
- leave comment to refer a bug ticket on jpackage plugin
-
=> chore: disable configuration cache and explicit enable build cache

azure-pipelines.yml, ci/azure-pipelines/build_doc_steps.yml, ci/azure-pipelines/publish_manual_snapshot.yml, doc_src/Readme.md
This is a fix of docCI
- Fix the doc change detection  broken by azure-pipeline git environment issue
- Fix snapshot manual upload to be recursive files
- update doc_src/readme.md
=> chore(ci): try to fix docCI

build.gradle, release/jpackage-specific/linux/OmegaT.spec, release/jpackage-specific/linux/desktop, release/jpackage-specific/linux/postinst, release/jpackage-specific/linux/prerm
Improve deb/rpm packages
- Update deb category to editors
- Bump package version to 2
- Fix debMaintainer mail address
- Update rpm category to Application/Editors
- override postinst/prerm to make link /usr/bin/omegat
- override desktop file template to add menu translations
=> chore(pkg): update debian metadata

build.gradle
Fix CI/CD error for documentation build.
- Remove `finalizedBy genDocIndex` from manualHtmls
- genDocIndex.dependsOn manualHtmls
- webManual.dependsOn manualHtmls, genDocIndex
=> chore: Update task dependency in Gradle

azure-pipelines.yml, ci/azure-pipelines/publish_manual_snapshot.yml, ci/azure-pipelines/publish_release.yml, ci/azure-pipelines/publish_weekly.yml
=> chore(ci): job status as template parameters

azure-pipelines.yml
- CI: thin checkouts to speed up tests except for release build and docCheck job
=> chore(ci): thin checkouts for tests

azure-pipelines.yml, ci/azure-pipelines/build_doc_steps.yml, ci/azure-pipelines/check_steps.yml, ci/azure-pipelines/publish_weekly.yml, doc_src/Readme_nl.txt
- use `parameters.condition` to pass build condition to template rather than `- ${{ if ... }}:`  syntax
=> chore(ci): value Agent.JobStatus as template parameters

release/changes.txt
=> docs: update changes.txt

build.gradle
Allow build and run OmegaT project on environment which does not have docker.
dev-ml
https://sourceforge.net/p/omegat/mailman/omegat-development/thread/A666AE3A-356E-4581-8A26-8DF8FA60E624%40traduction-libre.org/#msg58709796
- Check java version of execution for gradle to be Java 17, skip jpackage tasks if not
- Check docker or nerdctl executable presence, skip manual builds if not exist
- Check xcrun and codesign command presence, skip mac signing if not exist
=> chore(ci): check prerequisite of some tasks

release/readme.txt
- Add link to OmegaT contribution guide on readthedocs.org
=> docs: Update readme.txt

aligner/build.gradle, spellchecker/hunspell-jmyspell/build.gradle, theme/build.gradle
- make aligner/theme/spellchecker module as fatjar
dev-ml
https://sourceforge.net/p/omegat/mailman/message/58709814/
- Fix aligner build configuration to make fatjar
- Fix theme config to make fatjar
- Fix spellchecker config to make fatjar
=> chore: fix module dependency

machinetranslators/google/src/main/resources/org/omegat/machinetranslators/google/Bundle.properties
- Fix wrong english message in MT google connector.
-
-
Related #831  point message error
=> UI: fix message error

src/org/omegat/help/Help.java, src/org/omegat/util/OConsts.java, src/org/omegat/util/StaticUtils.java, test/src/org/omegat/gui/scripting/ScriptingTest.java
- StaticUtils#installDir: Check developer environment first and add detailed explanation comment
- OConsts: Define a build folder name
- Help#getHelpFileURI: Also check a developer case
- ScriptingTest: Put assertion error messages
-
-
-
=> feat: update installDir detection

machinetranslators/google/src/main/java/org/omegat/machinetranslators/google/Google2Translate.java, machinetranslators/ibmwatson/src/main/java/org/omegat/machinetranslators/ibmwatson/IBMWatsonTranslate.java
- operator position of Google2Translate
- line length of IBMWatsonTranslate
refactor
-
-
-
=> style: machinetranslators files

src/org/omegat/core/team2/impl/SVNRemoteRepository2.java
- Pick a part of enhancement from PR #906
refactor
- Move a part of setting system property in SVNRemoteRepository2 class to constructor-
=> refactor: initialize SVNKit preference in constructor

test/src/org/omegat/core/team2/AbstractRemoteRepository2IT.java
port finding from PR #906
refactor
-
-
-
=> refactor/test: initialize remote repository plugins before creating local repository

build.gradle, ci/iscc, doc_src/docgen
- Update build.gradle to check also nerdctl
- Update docgen/iscc shell scripts
=> [6.0] backport doc build container command

gradle/libs.versions.toml
- rsyntaxextarea@3.3.4
- rstaui@3.3.1
- languagesupport@3.3.0
- autocomplete@3.3.0
dependency
-
-
-
=> chore: bump rstaui version

Plugins.properties, src/org/omegat/filters3/xml/android/AndroidFilter.java, src/org/omegat/filters3/xml/camtasiawindows/CamtasiaWindowsFilter.java, src/org/omegat/filters3/xml/docbook/DocBookFilter.java, src/org/omegat/filters3/xml/flash/FlashFilter.java, src/org/omegat/filters3/xml/helpandmanual/HelpAndManualFilter.java, src/org/omegat/filters3/xml/infix/InfixFilter.java, src/org/omegat/filters3/xml/l10nmgr/L10nmgrFilter.java, src/org/omegat/filters3/xml/opendoc/OpenDocFilter.java, src/org/omegat/filters3/xml/openxml/OpenXMLFilter.java, src/org/omegat/filters3/xml/properties/PropertiesFilter.java, src/org/omegat/filters3/xml/relaxng/RelaxNGFilter.java, src/org/omegat/filters3/xml/resx/ResXFilter.java, src/org/omegat/filters3/xml/schematron/SchematronFilter.java, src/org/omegat/filters3/xml/scribus/ScribusFilter.java, src/org/omegat/filters3/xml/svg/SvgFilter.java, src/org/omegat/filters3/xml/txml/TXMLFilter.java, src/org/omegat/filters3/xml/typo3/Typo3Filter.java, src/org/omegat/filters3/xml/visio/VisioFilter.java, src/org/omegat/filters3/xml/wix/WiXFilter.java, src/org/omegat/filters3/xml/wordpress/WordpressFilter.java, src/org/omegat/filters3/xml/xhtml/XHTMLFilter.java, src/org/omegat/filters3/xml/xmlspreadsheet/XMLSpreadsheetFilter.java
refactor
dev-ML discussion
https://sourceforge.net/p/omegat/mailman/omegat-development/thread/2F1E7417-2CB7-4BD0-A0E6-345F48F08DFA%40traduction-libre.org/#msg58733211
- Add loadPlugins function for each filters.
=> refactor: migrate filters3 to omegat3 plugin style

src/org/omegat/gui/glossary/GlossaryManager.java, src/org/omegat/gui/glossary/GlossaryTextArea.java, src/org/omegat/gui/glossary/IGlossaries.java, src/org/omegat/gui/scripting/ConsoleBindings.java, test/src/org/omegat/gui/glossary/GlossaryAutoCompleterViewTest.java
=> refactor: pull up GlossaryTextArea#refresh as IGlossaries API

config/checkstyle/suppressions.xml, src/org/omegat/core/data/RealProject.java, src/org/omegat/core/team2/RebaseAndCommit.java, src/org/omegat/core/team2/impl/GITRemoteRepository2.java, src/org/omegat/core/team2/impl/HTTPRemoteRepository.java, test-integration/logger.properties
- Debug log in some classes are broke
- https://sourceforge.net/p/omegat/bugs/1249/
- Debug logs in some classes are broken because of placeholder differences.
- Use fluent API for logging
- Add debug logs for glossary handling functions
- refactor: Replace some try-finally with try-resources
- Tweak log levels of integration test
=> [BUGS#1249] fix: fix debug log placeholders

.github/workflows/gradle-build-master.yml
CI improvement
- Fix CI script issue
- Update for preparation of acceptance test; 
- install xvfb 
- run gradle with xvfb-run
Spin out an improvement from #964
=> chore(GitHub Actions): fix gradle scan url post

src/org/omegat/filters4/xml/AbstractXmlFilter.java, src/org/omegat/filters4/xml/openxml/OpenXmlFilter.java, src/org/omegat/filters4/xml/xliff/AbstractXliffFilter.java, src/org/omegat/filters4/xml/xliff/SdlXliff.java, src/org/omegat/filters4/xml/xliff/Xliff1Filter.java, src/org/omegat/filters4/xml/xliff/Xliff2Filter.java, test/data/filters/xliff/filters4-xliff1/file-XLIFFFilter1-multiple-file-tag-expect.xlf, test/data/filters/xliff/filters4-xliff1/file-XLIFFFilter1-multiple-file-tag.xlf, test/src/org/omegat/filters4/Xliff1FilterTest.java
refactor
- Backport from #937, and #945 
-
=> [6.0] refactor: backport improvement of StaX filter: create event reader when shifting mode

src/org/omegat/core/Core.java, src/org/omegat/gui/filelist/IProjectFilesList.java, src/org/omegat/gui/filelist/ProjectFilesListController.java, src/org/omegat/gui/main/MainWindow.java, src/org/omegat/gui/main/MainWindowMenuHandler.java, src/org/omegat/gui/main/MainWindowUI.java
Technical debt repayment.
refactor
- add IProjectFilesList interface
- add Core.getProjectFilesList core function
- create ProjectFilesList object in Core.initilizeGUI function
- reduce a direct MainWindow object access w/o using IMainWindow API from MenuHandler
Spin off PR from #964
=> refactor: Introduce IProjectFilesList interface

test/data/filters/xliff/filters4-xliff1/en-ca.xlf, test/src/org/omegat/core/data/ExternalTMFactoryTest.java
- Update the case tm by xliff1
- Update case with "state=final and translate=no"
#804 [BUGS#1220] Support XLIFF as external TM 
#805 [BUGS#1215] chore: Xliff1FilterTest with translate=no arg
=> test: change case for ExternalTMFactoryTest

build.gradle, ci/azure-pipelines/build_steps.yml, ci/azure-pipelines/publish_release.yml, ci/azure-pipelines/publish_weekly.yml
- update build.gradle
- Replace deprecated distsDirName with distsDirectory base plugin convension
- refactor win dists signing tasks to use lazy evaluation with function
- rename mac dist build task names
- add checks for up-to-date status for custom tasks
- release with checksums
-
=> chore: gradle: replace deprecated convention

src/org/omegat/gui/dialogs/AboutDialog.java, src/org/omegat/gui/dialogs/CreateGlossaryEntry.java, src/org/omegat/gui/dialogs/LicenseDialog.java, src/org/omegat/gui/dialogs/LogDialog.java, src/org/omegat/gui/dialogs/NewProjectFileChooser.java, src/org/omegat/gui/glossary/GlossaryTextArea.java
For test purpose, put names for GUI parts.
-
-
-
=> feat: give UI parts names

src/org/omegat/gui/editor/EditorController.java, src/org/omegat/gui/main/BaseMainWindowMenu.java, src/org/omegat/gui/main/MainWindow.java, src/org/omegat/gui/main/MainWindowMenuHandler.java, src/org/omegat/gui/main/MainWindowStatusBar.java, src/org/omegat/gui/main/MainWindowUI.java, src/org/omegat/gui/main/ProjectUICommands.java
refactor
- MainWindow don't extend JFrame to help test code to mock JFrame
- add MainWindowStatusBar class to Improve encapsulation
=> refactor: MainWindow does not inherit JFrame

ci/azure-pipelines/build_steps.yml
=> chore(ci): bump bundle JRE@17.0.23+9

azure-pipelines.yml, ci/azure-pipelines/build_steps.yml, ci/azure-pipelines/publish_release.yml, ci/azure-pipelines/publish_weekly.yml
Last weekly release succeeded but scp to sourceforge only a single file.
It changes build script to be more robust 
- move scripts to check version after cache resume to speed up
- change scp option to "-p -s" for publish_* scripts to use SFTP for upload and preserve build date/time
=> chore(ci): change build scripts

src/org/omegat/gui/main/MainWindowMenuHandler.java
=> refactor: Replace mainWindow obj access with Core.getMainWindow API

src/org/omegat/gui/editor/EditorController.java
=> refactor: Update EditorContoller to reference MainMenu fields

src/org/omegat/gui/main/ConsoleWindow.java, src/org/omegat/gui/main/IMainWindow.java, src/org/omegat/gui/main/MainWindow.java, src/org/omegat/gui/main/MainWindowMenuHandler.java, src/org/omegat/gui/main/MainWindowUI.java, src/org/omegat/gui/main/ProjectUICommands.java, src/org/omegat/gui/search/SearchWindowManager.java, test-acceptance/src/org/omegat/gui/main/TestMainWindow.java, test/fixtures/org/omegat/core/TestCore.java
refactor 
- add IMainWindow#saveDesktopLayout and IMainWindow@resetDesktopLayout
- define MenuHandler functions in ProjectUICommands  
- introduce SearchWindowManager and move related functions to it
=> refactor: extend MainWindow API, and move MenuHandler functions in ProjectUICommands, then introduce SearchWindowManager

docs_devel/docs/05.Versioning.md, docs_devel/docs/90.ReleaseProcedure.md, docs_devel/docs/index.md
=> docs_devel: revise a release procedure manual

release/changes.txt
=> docs: update changes.txt for rel 6.0.1

doc_src/ca/version_ca.properties, doc_src/de/version_de.properties, doc_src/en/version.properties, doc_src/fr/version_fr.properties, doc_src/ja/version_ja.properties, doc_src/nl/version_nl.properties, docs/ca/version_ca.properties, docs/en/version.properties, docs/fr/version_fr.properties, docs/ja/version_ja.properties, docs/nl/OmegaT.css, docs/nl/version_nl.properties
OmegaT check manual version is as exactly the same as the one, defined in src/org/omegat/Version.properties
- Update version_*.properteis
- Update docs/nl/OmegaT.css
=> [6.0.1]fix:  manual version_*.properties

doc_src/fr/Introduction.xml, doc_src/fr/manualvariables.mod
generated with omeat-L10N/fr repository. I copy an English manuals into `source/6.0/doc_src` and get translation from `target/6.0/doc_src`
=> [6.0] docs: Update HTML manuals of FR from l10n project

src/org/omegat/gui/main/BaseMainWindowMenu.java, src/org/omegat/gui/main/MainWindowMenuHandler.java, src/org/omegat/gui/main/ProjectUICommands.java, src/org/omegat/util/gui/MenuExtender.java
- Removal of MED package save/load feature
- https://sourceforge.net/p/omegat/bugs/1266/
- Removal of MED packaging feature
- It is obsolete and there is no user
=> Removal of MED package feature

azure-pipelines.yml, ci/azure-pipelines/build_doc_steps.yml, ci/azure-pipelines/build_steps.yml, ci/azure-pipelines/check_steps.yml, ci/azure-pipelines/publish_manual.yml, ci/azure-pipelines/publish_release.yml, ci/azure-pipelines/publish_weekly.yml, ci/azure-pipelines/test_steps.yml, src/org/omegat/filters2/po/PoFilter.java, src/org/omegat/util/Platform.java, test/src/org/omegat/MainTest.java, test/src/org/omegat/core/TestCore.java, test/src/org/omegat/core/team2/AbstractRemoteRepository2IT.java, test/src/org/omegat/filters/HTMLFilter2Test.java, test/src/org/omegat/filters/MozillaFTLFilterTest.java, test/src/org/omegat/filters/POFilterTest.java, test/src/org/omegat/gui/dialogs/DialogsTest.java, test/src/org/omegat/util/FileUtilTest.java, test/src/org/omegat/util/TMXWriterTest.java
Backport CI/CD azure pipelines from master branch.
- build and release
- Backport CI script from master branch, especially for testing on Windows and mac.
- Backport PR #788 to fix BUGS#1223
- Azure-Pipelines: always publish test results, it did not publish when test failed. 
- Fix or skip test errors on Windows, backport from master branch.
- Update JRE files for release.
=> [6.0]chore: backport azure-pipelines config

src/org/omegat/core/team2/impl/GITCredentialsProvider.java, src/org/omegat/gui/main/ConsoleWindow.java, src/org/omegat/util/FunctionalAction.java, src/org/omegat/util/gui/StaticUIUtils.java, test/src/org/omegat/util/gui/StaticUIUtilsTest.java
- resolve BUGS#1267 Console-stats command failed with error
- Console-stats command failed with error
- https://sourceforge.net/p/omegat/bugs/1267/
- Update detection logic of GUI environment
=> fix: isGUI detect properly

.github/workflows/acceptance-master.yml, .github/workflows/gradle-check-master.yml, .github/workflows/gradle-wrapper-validate.yml, .github/workflows/greetings-builds-master.yml, .github/workflows/manuals-builds-master.yml, .gitignore, build.gradle, src/org/omegat/core/Core.java, src/org/omegat/gui/editor/EditorController.java, test/fixtures/org/omegat/core/TestCoreInitializer.java
- update GitHub Actions
- refactor o.o.g.e.EditorController and update o.o.c.Core, and test's o.o.c.TestCoreInitializer
=> chore: use xvfb for acceptance test

.github/workflows/acceptance-master.yml, build.gradle, src/org/omegat/gui/editor/EditorController.java, src/org/omegat/gui/main/DockablePanel.java, src/org/omegat/gui/main/MainWindowUI.java, test-acceptance/src/org/omegat/gui/editor/EditorTextAreaTest.java, test-acceptance/src/org/omegat/gui/main/TestMainWindow.java
Currently, the acceptance test is under the development.
This PR is to improve the test cases, and fixes several GUI components provisioning for test purpose.
refactor
- refactor: `MainWindowUI` utility accept `IMainWindow` as argument instead of real `MainWindow`
- update `build.gradle` to use project property "testDisplay" for the acceptance test. When run without the property, it runs on current live display. Otherwise, it runs on `Xvfb`  virtual display with specified display number.
- Fix `DockablePanel#getName` method returns the value properly.
- update `TestMainWindow` to initialize screen layout properly.
- set `EditorScrollPane` name to use in the acceptance test
- add simple `EditorPane` test to detect "First Steps" text on the startup OmegaT screen.
=> chore: improve acceptance test

src/org/omegat/gui/editor/EditorController.java, src/org/omegat/gui/editor/IEditor.java, src/org/omegat/gui/search/SearchWindowController.java
- move logic from SearchWindowController to EditorController
=> refactor: Extend IEditor to provide getCurrentPositionInEntryTranslationInEditor

aligner/src/main/java/org/omegat/gui/align/AlignFilePickerController.java, aligner/src/main/java/org/omegat/gui/align/AlignPanelController.java, aligner/src/main/java/org/omegat/gui/align/AlignerModule.java, build.gradle, src/org/omegat/gui/main/BaseMainWindowMenu.java, test-acceptance/src/org/omegat/gui/align/AlignerWindowTest.java, test/fixtures/org/omegat/util/LocaleRule.java
- set names for components on aligner
- Test picker dialog GUI parts.
Quality assurance
- Add acceptance test case to check aligner
=> feat: basic acceptance test of aligner

aligner/src/main/java/org/omegat/gui/align/AlignFilePickerController.java, aligner/src/main/java/org/omegat/gui/align/AlignPanelController.java, test-acceptance/data/project/source/parseSource.txt, test-acceptance/data/project/target/parseTarget.txt, test-acceptance/src/org/omegat/gui/align/AlignerWindowTest.java, test-acceptance/src/org/omegat/gui/main/TestCoreGUI.java
- Bug
- Add acceptance test case for aligner. 
- aligner average distance can be {0} which expected a numeric value
- https://sourceforge.net/p/omegat/bugs/1275/ 
- add acceptance test case `AlignerWindowTest.java`
=> Aligner: acceptance test and fix a message bug

build.gradle, test-acceptance/src/org/omegat/gui/align/AlignerWindowTest.java
Acceptance test is now flaky. This change the test case of aligner and update test configuration for the fix of stop of the Xvfb process.
- Skip flaky operation in the aligner acceptance test
- Update gradle configuration to fix the testAcceptanceFinally task
=> chore: test acceptance: stabilize flaky aligner acceptance test

src/org/omegat/core/statistics/FindMatches.java
=> docs: update javadoc of FindMatches class

aligner/src/main/java/org/omegat/gui/align/AlignFilePickerController.java, build.gradle, config/checkstyle/suppressions.xml, test-acceptance/src/org/omegat/gui/align/AlignerWindowTest.java, test-acceptance/src/org/omegat/gui/editor/EditorUtilsGUITest.java, test-acceptance/src/org/omegat/gui/editor/EditorUtilsTest.java, test-acceptance/src/org/omegat/gui/main/TestCoreGUI.java
- Fix the flaky acceptance test
- aligner: reduce dependency for Core
- EditorUtilsTest: update expectation for stability
- TestCoreGUI: add initialize once part
=> chore: update setup/teardown logic of acceptance test

src/org/omegat/core/statistics/FindMatches.java
=> feat: mark matches from source file translations as MATCH_SOURCE.FILES

doc_src/en/App_Segmentation.xml, doc_src/en/OmegaT_Preferences.xml, release/changes.txt, src/org/omegat/Bundle.properties
Change UI label for breaks setting UI checkbox.
https://sourceforge.net/p/omegat/feature-requests/484/
=> Change label for "break/exception" checkbox

release/changes.txt, src/org/omegat/Bundle_pt_BR.properties
A few items in the pt-BR bundle had typos.
- Bug fix → [1282]
"Typos in the pt-BR bundle"
https://sourceforge.net/p/omegat/bugs/1282/
Fixes a number of UI items in the pt-br bundle.
=> fix pt-br UI issues

src/org/omegat/gui/dialogs/NewProjectFileChooser.java
Ensure the new project dialog defaults to a valid directory when the current folder is not set or invalid. It now falls back to the user's home directory or the current working directory if the home directory is unavailable. This improves usability and prevents potential null directory issues.
- refactoring
- Added logic to ensure a sensible default directory is always set, using the user's home directory as a fallback when no valid current directory is found.
- Updated directory selection behavior to handle potential null directory states more robustly.
- Enhanced checks for file list validity and improved file/directory existence and permissions validation using Java NIO methods.
=> feat: Set default directory fallback for new project dialog

compose.yml, test-integration/docker/client/Dockerfile
Fix weekly release CI/CD process.
There is no issue to point.
- Bump Gradle version to 8.13 for CI configuration
-
-
=> chore: Update Gradle version to 8.13 in Dockerfile and compose.yml

build.gradle
Fix CI/CD error.
There is no issue to point.
- Remove `layout.settingsDirectory.dir` from `into` configuration.
=> Chore: Fix gradle task error for sourceDistZip

test/src/org/omegat/filters2/text/LineLengthLimitWriterTest.java
The utility class LineLengthLimitWriter don't have any unit tests and functional test.
This PR adds the test cases.
Add missing unit test
There is no issue to point.
- Add unit tests and functional test
=> Add unit tests for LineLengthLimitWriter

test/src/org/omegat/core/search/SearcherTest.java
Introduce detailed test cases covering various search scenarios, including exact matches, keyword matches, regex matches, width-insensitivity, empty/null inputs, and multiple/collapsed results. These tests aim to ensure the robustness and accuracy of the search logic under diverse edge cases.
-
-
-
=> Add comprehensive unit tests for Searcher functionality

src/org/omegat/gui/editor/Document3.java
refactor
- placing annotations in individual lines
-
-
=> style: Refactor formatting for readability in Document3.java

src/org/omegat/gui/editor/MarkerController.java
This PR improves o.o.g.e.MarkerContoller class for readability of comment, and code.
It also fix the potential NPE when document3 is null by checking null.
refactoring
- Reformat comment
- Replace runnable with a lambda expression
- Add null check to prevent NPE
- Use enhanced-for to replace legacy one for readability
=> style: Refactor MarkerController for improved readability and efficiency

src/org/omegat/gui/editor/TranslationUndoManager.java
Reduce complexity for future maintainability.
There is a potential compatibility issue for future java versions.
The private method handleWrapperCase use `setAccesible` which has been deprecated in Java 17 and later. 
refactor
- refactoring private method `TranslationUndoManager#extractEvent` to reduce complexity.
=> Refactor and improve DefaultDocumentEvent extraction logic

test/src/org/omegat/util/ProjectFileStorageTest.java
- refacotr
- Add more test cases
- Improve test coverage 86%
-
=> refactor: ProjectFileStorageTest to configure XML parser properly and check the result of mkdir

src/org/omegat/gui/editor/EditorController.java
Switch the old JUL logging framework with SLF4J based one.
This updates logger initialization and logging lines with new syntax.
reafactor
there is no ticket for the refactoring
- Update logger definition with LoggerFactory
- Update logging lines with new fluent syntax.
=> refactor: EditorController: Replace java.util.logging with SLF4J based logging

config/checkstyle/suppressions.xml, src/org/omegat/core/data/EntryKey.java, src/org/omegat/util/StringUtil.java, test/src/org/omegat/util/StringUtilTest.java
refacotor
- Add unit test for nullable comparison utility method.
- Rename the method name
- Improve javadoc
- avoid `==` operator
=> Refactor null-safe comparison method and replace usages

build.gradle, language-modules/ast/build.gradle, language-modules/ta/build.gradle, language-modules/tl/build.gradle
- Add build-logic into source package
- Fix the dependencies for building from source package
-
-
=> chore: Add morfologik-stemming jar and build-logic to build.gradle includes

src/org/omegat/core/Core.java, src/org/omegat/gui/multtrans/MultipleTransFindThread.java
refactor
- Remove unused Core.multiple field
- Improve MultipleTransFindThread lambda expression
#1296
=> Refactor translation search and remove unused field.

build-logic/src/main/groovy/org.omegat.document-conventions.gradle
The manual build task has a wrong output directory.
=> error in output directory name

src_docs/developer/00.ContributingEcoSystem.md, src_docs/developer/01.ContributingOmegaT.md, src_docs/developer/03.GitWorkFlows.md, src_docs/developer/07.MannerOfThePullRequest.md, src_docs/developer/index.md
1. **Rewritten "Variety of Contribution" section**
- Refreshed the description of our project's philosophy
- Highlighted different ways people can contribute (docs, plugins, testing, etc.)
- Clarified how the community works and how suggestions can be made
2. **Improved "Contributing to OmegaT Development" section**
- Explained the steps to contribute code more clearly
- Added info about opening tickets and submitting PRs
- Made it easier for new contributors to understand the process
3. **New section: "Manner of the Pull Request"**
- A quick guide on how to give constructive feedback on PRs
- Tips for staying on-topic, being respectful, and avoiding common issues
- Especially useful for testers, core members, or anyone reviewing changes
- Enhanced the …
=> docs: Add and refine developer contribution guidelines

.github/workflows/pmd-annotate.yml, build-logic/src/main/groovy/org.omegat.java-conventions.gradle, ci/github/problem-matcher.json, config/pmd/ruleset.xml, language-modules/br/src/test/java/org/omegat/languages/br/MorfologikTest.java, language-modules/uk/src/main/java/org/omegat/languages/uk/UkrainianPlugin.java, machinetranslators/apertium/src/main/java/org/omegat/machinetranslators/apertium/ApertiumTranslate.java, machinetranslators/dummy/src/main/java/org/omegat/machinetranslators/dummy/Dummy.java, spellchecker/hunspell/src/main/java/org/omegat/spellchecker/hunspell/HunSpellChecker.java, spellchecker/hunspell/src/test/java/org/omegat/spellchecker/hunspell/HunspellSpellcheckerTest.java, spellchecker/morfologik/src/main/java/org/omegat/spellchecker/morfologik/MorfologikSpellchecker.java, src/org/omegat/core/segmentation/SRX.java, src/org/omegat/core/team2/RemoteRepositoryProvider.java, src/org/omegat/core/team2/impl/SVNAuthenticationManager.java, src/org/omegat/core/team2/impl/SVNRemoteRepository2.java, src/org/omegat/filters2/html2/FilterVisitor.java, src/org/omegat/filters2/html2/HTMLFilter2.java, src/org/omegat/filters3/xml/opendoc/OpenDocDialect.java, src/org/omegat/filters3/xml/xliff/XLIFFDialect.java, src/org/omegat/gui/accesstool/ProjectFileInformation.java, src/org/omegat/gui/accesstool/ProjectFileRenderer.java, src/org/omegat/gui/accesstool/QuickAccess.java, src/org/omegat/gui/main/BaseMainWindowMenuHandler.java, src/org/omegat/languagetools/LanguageClassBroker.java, src/org/omegat/util/gui/CustomDockingUISettings.java, src/org/omegat/util/gui/laf/WindowsDarkThemeDetector.java, test-integration/src/org/omegat/core/data/TestTeamIntegration.java, test/src/org/omegat/gui/editor/mark/MarkerTestBase.java
This introduce PMD static code analysis with minimum rulesets.
- Add Gradle pmd plugin
- Add config/pmd/ruleset.xml configuration
- There are two rules; unused fields and default constructor without logic
- Fix errors of two rules
=> chore: Add PMD static code analysis with minimum rulesets 

test/src/org/omegat/filters/TestFilterBase.java, test/src/org/omegat/languagetools/LanguageToolTest.java
Some test cases in OmegaT requires network reachability because of DTD validation and LanguageServer connection test. This PR is backport PR #1155 to releases/6.0 branch.
- REFACTORING
- Update TestFilterBase to configure DocumentBuilderFactory noto to validate DTD.
- Update LanguageToolTest to select socket port
=> [6.0][backport] improve test robustness against network reachability

.readthedocs.yml
=> [6.0] docs: Add Read the Docs configuration file

src/org/omegat/filters3/xml/opendoc/OpenDocFilter.java, test/src/org/omegat/filters/OpenDocFilterTest.java
- refactor
- Use try-resource-catch to improve resource handling.
- Refactor large parseFile method to smaller helpers.
- Add a basic unit test for isSupported method to improve code coverage.
=> Refactor OpenDocFilter for clarity and resource management

src/org/omegat/Bundle.properties, src/org/omegat/util/gui/Styles.java
Improve Color style definitions.
refactor
- Update Styles class ctor to use explicit bundle key access
- Add javadoc for enum entries
- Define error message in Bundle.properties, which was defined in direct string in the source.
- Updated comments throughout the code for clarity and accuracy.
#1296
=> refactor: Color style enum name definition on ctor

.github/workflows/gradle-check-master.yml, settings.gradle
Add github actions to check quality which is backported from master branch
- Add GitHub Actions to run Gradle check and git repository cleanness after check
-
=> chore: [6.0] Add GitHub Actions workflow to run gradle check

src/org/omegat/gui/properties/SegmentPropertiesArea.java
- Fix BUGS#1291
- And refactoring to reduce the complexity of `SegmentPropertiesArea#setProperties` internal method.
- style: fix to catch Exception instead of Throwable
- minor fix to log with the utility function `Log.log`
- style: removal of a dead code
- See PR #1357
- Sometimes called `SegmentProperties.onEntryActivated` after closed a project
- https://sourceforge.net/p/omegat/bugs/1291/
- Check a project loading status when processing entry activation event. 
- Removed unused code and imports: Eliminated unused imports, unnecessary comments, and commented-out code.
- Improved exception handling: Replaced generic exception handling with a more concise and uniform logging utility (Log.log()).
- …
=> [6.0][backport]Fix the EventListener to check project status isLoaded to solve BUGS#1291.

src/org/omegat/core/segmentation/SRX.java, src/org/omegat/core/segmentation/SegmentationConfValidator.java, src/org/omegat/util/ValidationResult.java, test/data/segmentation/locale_de_54/segmentation.conf, test/data/segmentation/malformed0/segmentation.conf, test/data/segmentation/malformed1/segmentation.conf, test/src/org/omegat/core/segmentation/SegmentationConfValidatorTest.java
This is another approach. This adds a validator but not  convert.
- Security
-
- CVE-2024-51366
- Introduce `SegmentationConfValidator` class
- Update SRX#loadSRX to validate before loading the file.
-
Related #1400 #1401
=> [6.0] Add segmentation.conf validation tool

src/org/omegat/util/Log.java
- Enhancement - internal util function
- Introduced `isDebugEnabled` method to check debug-level logging status.
- Added `logDebug` method for logging debug messages with optional parameters.
- Enhanced Javadoc for the new methods for clarity.
=> feat(util): add debug-level logging methods to Log class

test-integration/src/org/omegat/core/data/TestTeamIntegration.java
The previous refactoring breaks integration test.
-
-
-
=> fix(tests): handle directory creation failure in `TestTeamIntegration#setupRunnerDirectory`

.mailmap, ci/git-code-analysis.sh, src_docs/developer/91.appendix.md, src_docs/developer/94.GitRepositoryAnalysis.md, src_docs/developer/index.md
This Pull Request adds new scripts, documentation, and minor adjustments to aid development and repository analysis. It introduces tools for analyzing contributions, organizes documentation, and fixes minor issues in existing files.
- New additions:
- git-code-analysis.sh: A script to analyze contributors' activity in the repository.
- A new developer documentation file: 94.GitRepositoryAnalysis.md for repository analysis instructions.
- Documentation updates:
- Renamed and reorganized sections within 91.appendix.md (now "Supplementary files").
- Updated developer index (developer/index.md) to include new content and correct the format.
- Minor fixes:
- Adjusted formatting and fixed typos in developer documentation.
=> docs: update developer documentation and add git repository analysis

src/org/omegat/filters4/xml/xliff/Xliff1Filter.java
Refactor the `XLiff1Filter#generateTargetStartElement` method to replace inefficient for loop with `keySets()` with stream of `entrySets()` and other small improvements
- refactoring
- Introduced helper methods `writeTranslatedTarget`, `writeDefaultTarget`, and `checkTranslationStatus`.
- Simplified and streamlined `generateTargetStartElement` for better readability and maintainability.
- Replaced redundant logic with reusable constants and methods.
=> refactor(xliff): modularize target element generation logic in `Xliff1Filter`

src/org/omegat/Bundle.properties, src/org/omegat/gui/dialogs/LastChangesDialog.java
This Pull Request introduces updates to the LastChangesDialog functionality to improve handling of scenarios where the last changes file is unavailable. The changes separate the logic for loading the file to a dedicated method and enhance error handling with logging.
refactor
- Error Handling:
- Added a new localized error message "LASTCHANGESDIALOG_ERROR" in Bundle.properties.
- Introduced additional logging in LastChangesDialog to report errors when the last changes file fails to load.
- Code Refactor for Readability:
- Extracted the logic for loading the last changes file into a dedicated method loadLastChangesText, improving clarity and maintainability.
- Simplified some event listeners using lambda expressions and method references.
- UI Component Updates: …
=> refactor(gui): modularize last changes text loading and clean up `LastChangesDialog` initialization

src/org/omegat/core/statistics/StatsResult.java
- refactor
- update visibility to be package-private for internal data instead of public
=> refactor(core): update visibility of statistics headers in `StatsResult`

src/org/omegat/gui/scripting/ScriptingWindow.java, src/org/omegat/util/Log.java
- refactor
- Centralized logging logic by adding overloaded `log` methods in `Log` utility.
- Replaced direct `Logger` calls in `ScriptingWindow` with unified `Log` methods.
- Improved exception handling and thread interruption management for better robustness.
=> refactor(scripting): unify logging methods and improve exception handling

src/org/omegat/util/gui/RoundedCornerBorder.java
The Pull Request refactors the RoundedCornerBorder class by introducing a helper class SideShapeSpec and a corresponding factory method (createSideShapeSpec). This change simplifies and consolidates repetitive logic related to the creation of corner shapes and their associated drawing lines.
-refactor
- Extracted repetitive shape creation logic into a new helper class SideShapeSpec with fields for roundedHalfClip, line1, and line2.
- Added a factory method createSideShapeSpec to handle the creation of SideShapeSpec objects based on the side (e.g., top, left, bottom, right).
- Updated the main method to use the SideShapeSpec objects, making the code more modular and reducing repeated code sections.
- Improved readability and maintainability by encapsulating …
=> refactor(gui): extract `SideShapeSpec` class and factory method to simplify border rendering logic

src/org/omegat/util/logging/OmegaTFileHandler.java, test-integration/src/org/omegat/util/logging/TestLogFileHandler.java
Improve logger file handler.
-refactor
- replace File.delete() with `FileUtils.deleteQuietly`
- narrow exception type
- other improvements
=> refactor(logging): enhance directory creation error handling and cleanup logic

test/src/org/omegat/core/statistics/CalcMatchStatisticsTest.java
Fix the functional test that has duplicated initialization. This fixes the fraky unit test.
- Bug fix -> [bug] of the test
- remove duplicated test setup
- explicitly provide filter master instance
- improve test comments
=> refactor(tests): inject `FilterMaster` dependency and remove redundant setup

src/org/omegat/gui/issues/IssueColumn.java, src/org/omegat/gui/issues/IssuesPanelController.java, src/org/omegat/gui/issues/IssuesTableModel.java, src/org/omegat/gui/issues/IssuesTypeListModel.java, test-acceptance/src/org/omegat/gui/issues/IssuesPanelTest.java
This Pull Request introduces several updates and additions to the "Issues" feature in the OmegaT application. It includes creating new helper classes, moving existing logic to separate classes, and enhancing the functionality of the Issues Panel.
refactor
- New File Added: IssueColumn.java to define column metadata for the Issues table.
- Refactoring and Enhancements:
-  Moved table-specific logic into a new IssuesTableModel.java file.
- Separated type list-related logic to a new IssuesTypeListModel.java file.
- Improved mouse interaction handling for the Issues table with a dedicated mouse adapter.
- Added methods for better customization and maintainability of font, shortcut setup, and event handling in IssuesPanelController.
- Tests updated: Modified …
=> refactor(gui): extract `IssuesColumn`, `IssuesTableModel`, and `IssuesTypeListModel` into separate classes

src/org/omegat/filters2/html2/FilterVisitor.java
- refactor
- Utilized `Objects.requireNonNullElseGet` to simplify `options` initialization and prevent potential null pointer exceptions.
- Updated `writer` and `options` fields to `final` for immutability.
=> refactor(html2): improve constructor logic in `FilterVisitor`

src/org/omegat/filters2/AbstractFilter.java
=> refactor(filters): improve JavaDoc in `AbstractFilter` for enhanced readability

src/org/omegat/core/segmentation/MapRule.java, src/org/omegat/core/segmentation/Rule.java, src/org/omegat/filters2/html2/HTMLFilter2.java, src/org/omegat/filters2/html2/HTMLWriter.java, src/org/omegat/filters2/latex/LatexFilter.java, src/org/omegat/filters2/master/OneFilterTableModel.java, src/org/omegat/filters2/rc/RcFilter.java, src/org/omegat/filters2/xtagqxp/Xtag.java, src/org/omegat/util/Token.java
Improve code quality.
- refactor
- Add missing @Override for multiple classes
-
-
=> refactor(filters): annotate methods with `@Override` to improve clarity and maintain consistency across multiple classes

src/org/omegat/util/gui/OSXIntegration.java
There is an anti-pattern code in the class
- bugs
- refactor
- 
- Combined `APP_LISTENER` and `OPEN_FILES_HANDLER` into a new `OSXEventListener` class to simplify logic and reduce redundancy.
- Updated registration logic in `init` to use the new unified event listener.
- Avoid updating static field from instance
=> refactor(core): unify `OSXEventListener` and `IOpenFilesHandler` into single class

src_docs/developer/adr/2025003.StaticCodeAnalysis.md, src_docs/developer/adr/index.md, src_docs/developer/stylesheets/extra.css, src_docs/mkdocs.yml, src_docs/requirements.txt
Static code analysis is a part of the clean code initiative. There are so many technology debt in the project during over 20 years, and so many pitfalls in code base.
-
-
-
=> docs(adr): add decision record for comprehensive static code analysis strategy (#2025003)

src/org/omegat/core/spellchecker/AbstractSpellChecker.java, src/org/omegat/core/spellchecker/ISpellCheckerDictionary.java, src/org/omegat/core/spellchecker/SpellCheckerMarker.java
- Annotated fields, methods, and parameters with `@Nullable` for improved null-safety.
- Updated logic to prevent potential `NullPointerException` by adding null checks for `checker` in various methods.
- Simplified and adjusted code for better readability and maintainability.
refactor
- Title
* URL
-
-
-
=> refactor(spellchecker): add `@Nullable` annotations and improve null check

config/checkstyle/suppressions.xml, machinetranslators/belazar/build.gradle, machinetranslators/belazar/src/main/java/org/omegat/machinetranslators/belazar/BelazarTranslate.java, machinetranslators/google/build.gradle, machinetranslators/google/src/main/java/org/omegat/machinetranslators/google/Google2Translate.java, machinetranslators/ibmwatson/build.gradle, machinetranslators/ibmwatson/src/main/java/org/omegat/machinetranslators/ibmwatson/IBMWatsonTranslate.java, machinetranslators/mymemory/build.gradle, machinetranslators/mymemory/src/main/java/org/omegat/machinetranslators/mymemory/MyMemoryMachineTranslate.java, machinetranslators/yandex/build.gradle, machinetranslators/yandex/src/main/java/org/omegat/machinetranslators/yandex/YandexCloudTranslate.java, src/org/omegat/core/machinetranslators/BaseCachedTranslate.java
=> refactor(module): add nullability annotations and improve null handling across machine translation classes

tipoftheday/build.gradle, tipoftheday/src/main/java/org/omegat/gui/tipoftheday/TipOfTheDayModule.java, tipoftheday/src/main/java/org/omegat/gui/tipoftheday/TipOfTheDayUtils.java
=> refactor(tips): add nullability annotations and include `jetbrains.annotations` dependency for improved type safety

aligner/build.gradle, aligner/src/main/java/org/omegat/gui/align/AlignFilePickerController.java, aligner/src/main/java/org/omegat/gui/align/AlignPanelController.java, aligner/src/main/java/org/omegat/gui/align/Aligner.java, aligner/src/main/java/org/omegat/gui/align/AlignerModule.java, aligner/src/main/resources/org/omegat/gui/align/Bundle.properties
- refactor
- Gradle Build File Changes:
-  Added dependency on JetBrains Annotations to enhance null-safety in the code.
-  Aligner Module Enhancements:
-  Introduced @Nullable annotations to various fields, methods, and parameters across multiple classes.
-  Improved null checks in logic, reducing potential null pointer exceptions (e.g., checks added in alignHeapwise and alignImpl methods).
-  Converted some method calls to modern, safer alternatives like List.of() instead of Arrays.asList().
-  Code Cleanup:
-  Removed unused imports (e.g., LoggerFactory, ILogger).
-  Replaced explicit writer management logic with a try-with-resources block to handle resource cleanup in writePairsToTMX.
-  Fixed …
=> refactor(aligner): add nullability annotations and improve safety checks across aligner classes

.github/CODEOWNERS
- Add configuration of the several directries for documents, ui contents, build system, and document styles
-
-
=> chore: update CODEOWNERS with granular ownership rules for project files

src/org/omegat/core/data/ParseEntry.java, src/org/omegat/core/data/ProtectedPart.java, src/org/omegat/core/data/SourceTextEntry.java, src/org/omegat/core/segmentation/Segmenter.java, src/org/omegat/gui/editor/mark/Mark.java, src/org/omegat/gui/segmentation/SegmentationCustomizer.java, src/org/omegat/help/Help.java, src/org/omegat/util/StringUtil.java, src/org/omegat/util/TMXWriter2.java
=> refactor(core): add `@Nullable` annotations to improve null-safety and clarify method contracts across multiple classes

src/org/omegat/help/Help.java
- refactor
- Add @Nullable to Help.java
-
-
=> refactor(help): add `@Nullable` annotations and enhance null-safety in Help class methods

build-logic/src/main/groovy/org.omegat.document-conventions.gradle
- change from group('...') to group = '...'
-
-
=> refactor(gradle): update task group assignment syntax for consistency

src/org/omegat/filters2/master/PluginUtils.java
- Bug fix -> [bug] for test
- Fix typo to detect plugin type and class name
- Fix the integration test initializaqtion
-
=> refactor(core): annotate `loadPluginFromProperties` with `@VisibleForTesting` and streamline plugin loading logic

gradle/libs.versions.toml
typo in dependency version
-  fix typo: version => version.ref
-
-
=> chore(dependency): fix typo version reference `jaxb4-api`

src/org/omegat/filters2/html2/HTMLFilter2.java
- `String.splitter` can provide a surprising results, so use it with limit argument
- refactor
-  
-
-
=> refactor(filters): refine meta attribute handling in HTMLFilter2

src/org/omegat/core/statistics/StatCount.java, src/org/omegat/core/statistics/StatProjectProperties.java, src/org/omegat/core/statistics/StatsResult.java, test/data/statistics/stats-result-1.xml, test/src/org/omegat/core/statistics/StatsResultTest.java
-  Wrong root element name for stats.xml
- https://sourceforge.net/p/omegat/bugs/1301/
- Add functional tests for console command lines
- Fix the XML wrapping element name `<omegat-stats>` instead of `<StatsResults>`
-
=> fix(cli): stats XML output problem and add functional tests

src/org/omegat/core/data/ImportFromAutoTMX.java, src/org/omegat/core/team2/RebaseAndCommit.java, src/org/omegat/core/team2/RemoteRepositoryProvider.java, src/org/omegat/gui/main/IMainWindow.java
- rafactoring
- Annotated methods and parameters with `@Nullable` in core classes like `IMainWindow` and `RemoteRepositoryProvider` to improve static analysis.
- Replaced manual map initialization with `computeIfAbsent` for cleaner code in `ImportFromAutoTMX`.
=> refactor(core): add `@Nullable` annotations and enhance null safety across core components

src/org/omegat/core/Core.java, test/fixtures/org/omegat/core/TestCore.java, test/fixtures/org/omegat/core/TestCoreInitializer.java, test/fixtures/org/omegat/util/CommonVerifications.java, test/fixtures/org/omegat/util/LocaleRule.java, test/fixtures/org/omegat/util/TestPreferencesInitializer.java
- refactor
- Nullability annotations: Added @Nullable and @NotNull annotations to enhance code clarity and safety.
- Unused method removal: Removed unused setTagValidation method from Core.java and its corresponding initializer.
- Test code updates:
- Replaced null with empty strings in TestCore.java to reduce ambiguity.
- Introduced improvements in mock implementations, including GUI-related overrides.
- Updated exception and parameter documentation for better clarity.
- Adjusted conditional checks to safely handle null values (e.g., in TestCoreInitializer.java).
- Bug fixes: Corrected logical and formatting issues, such as parentheses in conditionals and LocaleRule's initialization behavior.
- Code cleanup: Removed redundant imports, streamlined code structure, and enhanced several …
=> refactor(core, tests): improve annotations, exception handling, and test structure

build-logic/src/main/groovy/org.omegat.jaxb-conventions.gradle, src/schemas/tmx11.xsd
- Remove JAXB task to produce java files from tmx14.xjb
- OmegaT do not use the source generated.
- Add tmx11.xsd for future validation
- Sub task of PR #1559
=> refactor(build-logic): remove `tmx14` JAXB task and introduce `tmx11` schema file

src_docs/manual/en/HowTo_SetUpTeamProject.xml, src_docs/manual/en/HowTo_UseTeamProject.xml
This is an update for Kazephil:topic/kaze/documentation/updates.
=> Update team related docs (topic/kaze/documentation/updates)

src/org/omegat/core/segmentation/SRX.java
This Pull Request includes refactoring and cleanup of the SRX.java file, affects how segmentation rules are loaded, and improves file deletion operations by utilizing safer and more modern techniques. Deprecated constants are now explicitly marked, and unused methods and redundant logic have been removed.
- refactor
- Modernized file deletion methods to use Files.deleteIfExists instead of File.delete.
- Introduced @Nullable annotation for the loadFromDir method to indicate potential null return values.
- Removed unused methods and redundant logic, including projectConfigFileExists, merge, and upgrade.
- Improved type inference and removed unnecessary generics within the code (e.g., instantiation of ArrayList).
- Explicitly marked constants as deprecated that are related to older …
=> refactor(core): add `@Nullable` annotations and improve file handling with `Files.deleteIfExists`

src_docs/manual/en/HowTo_SetUpTeamProject.xml, src_docs/manual/en/HowTo_UseTeamProject.xml
[documentation]
I'm proposing a few additional changes to the updates to the team project sections Jean-Christophe merged a few days ago.
I think most of them are improvements on my own original poor phrasing, but I've also tried to establish a base to incorporate the additional advanced team project information proposed by @miurahr in #1524.
=> docs: Revisions to phrasing in sections on Team projects

src/org/omegat/core/data/RealProject.java
- refactor
- Added private methods (exportTMXs, compileMatchingFiles, shouldCommitToRepository, commitToRepository, and displayCompilationResult) to improve organization and readability.
- Modified logic to export TMX files and handle exceptions with improved traceability.
- Enhanced the translation compile process by including pre-commit and post-processing steps.
- Improved commit functionality for remote repositories, including revised logic for tracking and committing translations and statistics files.
- Reorganized code to replace in-line logic with reusable private methods for better clarity and maintainability.
=> refactor(core): modularize `RealProject` compilation logic and enhance error handling

tipoftheday/src/main/java/org/omegat/gui/tipoftheday/TipOfTheDayModule.java, tipoftheday/src/main/java/org/omegat/gui/tipoftheday/TipOfTheDayUtils.java
This Pull Request introduces improvements in null-safety checks and applies annotations to ensure better code stability and readability in the tipoftheday module.
- refactor
- Added a null check in the unloadPlugins() method to prevent potential NullPointerException.
- Annotated a JMenuItem variable with @Nullable to clarify its nullability in the TipOfTheDayModuleListener class.
- Annotated the return type of the method getTipsFileURI() in TipOfTheDayUtils class with @Nullable to indicate it can return a null value.
-
=> refactor(tips): add `@Nullable` annotations and refine null checks for improved safety

config/checkstyle/suppressions.xml
- coding style
- Suppress warnings for auto generated files
-
-
=> chore(checkstyle): add LineLength suppression for specific files

src/org/omegat/convert/ConvertProject26to37team.java
refactoring
- style: split long line
- remove unused import
- drop unraised IOException
- Fix javadoc words
=> style(convert): split long log line for readability

release/changes.txt
=> doc: update changes.txt

machinetranslators/apertium/src/main/java/org/omegat/machinetranslators/apertium/ApertiumTranslate.java, machinetranslators/mymemory/src/main/java/org/omegat/machinetranslators/mymemory/AbstractMyMemoryTranslate.java, machinetranslators/mymemory/src/main/java/org/omegat/machinetranslators/mymemory/MyMemoryHumanTranslate.java, machinetranslators/mymemory/src/main/java/org/omegat/machinetranslators/mymemory/MyMemoryMachineTranslate.java, machinetranslators/mymemory/src/main/java/org/omegat/machinetranslators/mymemory/MyMemoryTranslate.java, src/org/omegat/util/gui/DataTableStyling.java, src/org/omegat/util/gui/DragTargetOverlay.java, theme/src/main/java/org/omegat/gui/theme/DefaultFlatDarkTheme.java, theme/src/main/java/org/omegat/gui/theme/DefaultFlatLightTheme.java
- javadoc
- Add class level javadoc
-
-
=> chore(docs): add class-level Javadoc for readability and maintainability

config/checkstyle/suppressions.xml, src/org/omegat/gui/matches/MatchesVarExpansion.java, src/org/omegat/util/CredentialsManager.java, src/org/omegat/util/OConsts.java, src/org/omegat/util/Preferences.java, src/org/omegat/util/gui/FontFallbackListener.java, src/org/omegat/util/gui/ViewFactoryHelper.java
- refactor
- style
- Checkstyle Suppression Updated: Suppressions for new lines in specific files were added or adjusted (e.g., StaticUtils.java and Platform.java).
- Code Formatting: Improved line formatting and readability in files like MatchesVarExpansion.java, FontFallbackListener.java, and ViewFactoryHelper.java.
- Improved Exception Handling: Added a default case for exhaustive handling in a switch statement (CredentialsManager.java).
- Constants Documentation: Improved code comments for constants in OConsts.java.
- Default Value Update: Changed default paragraph delimitation marks in Preferences.java from Latin escape to unicode.
- Refactored Method Documentation: Added detailed Javadoc comments to ViewFactoryHelper.java for better code clarity.
=> style: improve formatting, add checks, and update suppressions

build.gradle, gradle/libs.versions.toml
Solve some dependency conflicts 
- Added commons-codec library as a dependency in build.gradle and its version in libs.versions.toml.
- Updated assertj-swing-junit version from 4.0.0-beta-2 to 4.0.0-beta-3 in libs.versions.toml.
- Modified the test dependency xmlunit in build.gradle to exclude the assertj-core module.
=> chore(dependencies): update library versions and refine test configurations

test/src/org/omegat/core/data/TmxComplianceBase.java
- refactor
- Replaced descriptive type arguments with the diamond operator (<>) for cleaner code.
- Migrated to StandardCharsets.UTF_8 for better charset constant usage instead of a hardcoded string.
- Improved directory creation logic by using Files.createDirectories instead of manual parent directory handling.
- Encapsulated resource usage (e.g., BufferedReader) in a try-with-resources block to ensure proper closure.
=> refactor(tests): improve `TmxComplianceBase` for consistency and maintainability

src/org/omegat/core/data/ProjectTMX.java
The PR introduces several refactorings and improvements to the ProjectTMX.java file, including the addition of new comments, improved synchronization for content updates, enhanced parameter finalization, and streamlined code readability and formatting.
-refactor
- Ensured defaults and alternatives maps are final, thread-safe operations.
- Improved resource handling with try-with-resources while managing TMXWriter2.
- Added a clear method for safe resource reuse.
- Refactored replaceContent for better synchronization and thread-safety.
- Enhanced Javadoc for clarity.
#1566
https://sourceforge.net/p/omegat/mailman/message/59229097/
=> refactor(core): improve `ProjectTMX` data handling and Javadocs

src/org/omegat/core/data/RealProject.java
- refactor
- Replace debug log with a custom logger with `Log.logDebug`
=> refactor(core): replace custom logger with `Log` utility in `RealProject`

build-logic/src/main/groovy/org/omegat/module/OmegatModulePlugin.groovy, spellchecker/hunspell/build.gradle, spellchecker/morfologik/build.gradle, theme/build.gradle, tipoftheday/build.gradle
- Add pmd, spotbugs, checkstyle and errorprone in the module build plugin
=> chore(gradle): add quality check for module plugin

src/org/omegat/filters3/Attributes.java
This PR improves the Attributes class in the org.omegat.filters3 package. 
- refactor
- Added @Nullable annotation to help better identify and handle potential null return values.
- Updated the instantiation of the ArrayList with the diamond operator (<>) for cleaner code.
- Replaced a traditional for loop with an enhanced for-each loop for better readability.
- Added the @Override annotation to the toString() method to explicitly indicate method overriding.
=> refactor(core): enhance `Attributes` with `@Nullable` annotations and code improvements

src/org/omegat/filters3/xml/XMLText.java
The Pull Request refactors the XMLText class to improve code readability and consistency. Key changes include making the inCDATA field final, optimizing string concatenation in the toOriginal method, and adding @Override annotations where appropriate.
- refactor
- The inCDATA field is now declared as final for immutability.
- String concatenation in the toOriginal method has been simplified, improving readability.
- Added @Override annotations to ensure proper method overriding and enhance clarity.
=> refactor(filters3): streamline `XMLText` implementation

src/org/omegat/core/search/Searcher.java
The PR introduces code changes that primarily consist of reformatting the Java source file, focusing on improving code readability and adhering to standard formatting conventions. No apparent logic or functional behavior of the application has been altered.
-style
- Apply spotless to Searcher.java
=> style(core): reformat code in `Searcher.java` to adjust line wraps for better readability

src_docs/developer/adr/index.md
Add missing ADRs and categorize it.
-
-
-
=> chore(docs): restructure ADR index for improved categorization
