- src/org/omegat/gui/glossary/DefaultGlossaryRenderer.java
3 patches, conform to last message in the user list:
Patch 1: add colors for source, translation and comment. These colors are configurable in the colors panel
Patch 2: can disable merging of entries (seems that some people don't like it)
Patch 3: change layout for merged entries, in order to put each comment just after the translation it is associated to (see discussion in users list)
> Glossaries change layout

- src/org/omegat/core/data/ExternalTMX.java
- src/org/omegat/core/data/ITMXEntry.java
- src/org/omegat/core/data/ITranslationEntry.java
- src/org/omegat/core/data/ImportFromAutoTMX.java
- src/org/omegat/core/data/PrepareTMXEntry.java
- src/org/omegat/core/data/TMXEntry.java
- src/org/omegat/core/search/Searcher.java
- src/org/omegat/core/statistics/FindMatches.java
- src/org/omegat/gui/glossary/GlossaryEntry.java
- test/src/org/omegat/core/data/AutoTmxTest.java
- test/src/org/omegat/core/data/ExternalTMFactoryTest.java
- test/src/org/omegat/core/data/TmxSegmentationTest.java
- test/src/org/omegat/filters/POFilterTest.java
Introduce interfaces to TMXEntry
These interfaces have multiple goals.
In short term, they enable to merge functions actually duplicated, as you can see in my second patch (in Searcher class)
In middle term (I did only one example in patch 3) they enable to create an immutable view to (maybe) mutable entries: now users of ExternalTMX cannot modify its contents. We could do the same for ProjectTMX: store mutable entries in the maps, but return ITMXEntry in getDefaultTranslation/getMultipleTranslation
As @amake mentionned in the discussion list, PrepareTMXEntry actually looks like mutable variant of TMXEntry. That was initial meaning, but if you look where they are used, you will see that since ExternalTMX continued to use PrepareTMXEntry, it has been used as something similar to external …
> Refactor tmx entry

- src/org/omegat/filters2/master/PluginUtils.java
- Fix NPE introduced by commit ccbfe72
- Check whether PluginType.getTypeByValue argument is empty
N/A
- Check null for PluginType.getTypeByValue argument.
- Fix NPE when plugin don't have category property.
> PluginUtils: nullable getTypeByValue argument

- test/src/org/omegat/core/team2/AbstractRemoteRepository2IT.java
It is bad practice to create Random instance and use only once.
This changes to use ThreadLocalRandom.current().nextInt().
Fix bad practice
- Link: 
- Title: 
-
-
-
> Test: use ThreadLocalRandom for temp file name

- src/org/omegat/core/search/Searcher.java
- Link: https://sourceforge.net/p/omegat/bugs/1099/
- Title: Absolute paths used in search results from TMs
- When filepath option is on in search dialog, a result pane will show
file paths in relative manner.
- Fix a behavior that TM search show paths even when filepath option is off.
- Address [BUGS#1098](https://sourceforge.net/p/omegat/bugs/1098/) and [BUGS#1099](https://sourceforge.net/p/omegat/bugs/1099/)
> [BUGS#1098,#1099] Searcher: show file path in relative

- src/org/omegat/filters2/po/PoFilter.java
- test/data/filters/po/file-POFilter-be-expected.po
- test/data/filters/po/file-POFilter-fuzzyCtx-expected.po
- test/data/filters/po/file-POFilter-fuzzyCtx.po
- test/src/org/omegat/filters/POFilterTest.java
fixed BUG#1103
- Link: https://sourceforge.net/p/omegat/bugs/1103/
- Title: #1103 PO filter: target files should not keep #| msgctxt
- check #| msgctxt and remove
- Add test case
> [#1103] POFilter: remove fuzzy msgctxt when translate

- src/org/omegat/filters2/AbstractFilter.java
- src/org/omegat/filters2/mozdtd/MozillaDTDFilter.java
- src/org/omegat/filters2/mozlang/MozillaLangFilter.java
- src/org/omegat/filters2/po/PoFilter.java
- test/data/filters/MozillaDTD/file-be.dtd
- test/data/filters/po/file-POFilter-fuzzyCtx-expected.po
- test/data/filters/po/file-POFilter-fuzzyCtx-plural.po
- test/src/org/omegat/filters/MozillaDTDFilterTest.java
- test/src/org/omegat/filters/POFilterTest.java
Refactoring AbstractFilter and its children PoFilter, MozillaLangFilter and MozillaDTDFilter.
A main concern is to use try-resource-finally syntax for reader/writer objects.
Another concern is to clean a BOM workaround by using BOMInputStream in PoFilter.  
A side changes are 
1. Fix signature error in javadoc reference, 
2. Coding style: line length standard 
3. Adopt NIO style writer/reader object creation instead of old style
Refactoring to use try-resource-finally syntax for input/output to improve future maintenance.
N/A
- PoFilter: MozillaLangFilter,MozDTDFilter: use try-resource-finally syntax for reader/writer
- PoFilter: MozillaLangFilter: Override createWriter/Reader method
- PoFilter: use BomInputStream for POFilter instead of …
> AbstractFilter,PoFilter,MozillaLangFilter: Refactoring createWriter createReader

- build.gradle
- release/changes.txt
- src/org/omegat/core/team2/impl/GITCredentialsProvider.java
- Fix BUG#1075: when ssh server reject environment variable GIT_PROTOCOL=version=2 that the fix is included in JGit@5.13.1
- Because JSch has been unmaintained and dead, we replace it with forked mwiede/jsch that supports ssh-agent native.
- Successor of PR #162
**THIS IS A CHANGE for OmegaT@5.8**
- Related PR #174 for OmegaT@6.1
- Link: https://sourceforge.net/p/omegat/bugs/1107/
- Title: OpenSSH new key format and ECDSA/ED25519 keys
- Link: https://sourceforge.net/p/omegat/bugs/1075/
- Title:  Unable to check-out or open/save team projects
- Bump JGit@5.13.1
- JGit@5.13.1 fixes the jgit bug that BUG#1075 reported.
- Replace dead JSch with forked  mwiede/jsch@0.2.3 that supports ssh-agent.
> [BUGS#1075] Team: JGit@5.13.1 w/ mwiede/jsch@0.2.3 (Successor of #162)

- src/org/omegat/gui/main/ProjectUICommands.java
- Limit number of backups when overriding local project.omegat
-  Link: https://sourceforge.net/p/omegat/bugs/1110/
- Title:  Team project pile upback up files of omegat.project
- Insert `FileUtil#removeOldBackups` after `FileUtil.backupFile` in `ProjectUICommands#openProject`
> Update ProjectUICommands#projectOpen method

- src/org/omegat/Bundle.properties
- src/org/omegat/core/team2/impl/GITCredentialsProvider.java
When enables gpg signing, omegat pop-up GPG key finger print on every push for team project.
- Link: 
- Title: 
-  Replace pop-up dialog for message only git credential request into display message on status area.
> Team(git): show message from credential manager on status area

- src/org/omegat/gui/main/ProjectUICommands.java
- test-integration/src/org/omegat/core/data/TestTeamIntegrationChild.java
OmegaT now keeps git/team repository URL configured in local working directory's omegat.project.
But when creating team project, it does not.
This change try to keep repository url set on dialog as repository url other than remote team project settings.
- Link:   https://sourceforge.net/p/omegat/feature-requests/1629/
- Title:  Git/Team project should preserve access URL when download team
- `ProjectUICommands#projectTeamCreate` check remote repository URL and if it is git type and differed with specified one, 
OmegaT respect local one and store it in local `omegat.project` file.
If there has already modification in local `omegat.project` file, OmegaT has already respect it in next open.
> Preserve repo URL when team project creation

- src/org/omegat/core/team2/impl/GITCredentialsProvider.java
- src/org/omegat/gui/main/ProjectUICommands.java
Support following senarios;
1. fork or make branch from translation team project repository
2. a project has root repository mapping that is as same as original
3. creating local working project with `branch` project.
4. works on branch team project
But OmegaT override local repository mapping with remote repository configuration, that can point to original team project.
This patch preserve branch name. 
- Link:   https://sourceforge.net/p/omegat/feature-requests/1531/
- Title:   Support using arbitrary git branch name
- Keep branch name specified in Download team project dialog
- OmegaT to set branch name to local omegat.project's repository mapping as root repository configuration
> [Feature] team: preserve branch name for root mapping

- src/org/omegat/gui/main/ProjectUICommands.java
- Because a filter configuration is stored in filters.xml, remove a comparison from the ProjectUICommands#isIdenticalOmegatProjectProperties method.
- Link: 
- Title: 
Pull request #274 is incomplete to remove a code which compare filters.
- Remove a filter comparison from the ProjectUICommands#isIdenticalOmegatProjectProperties method.
> Remove filter check from ProjectUICommands#isIdenticalOmegatProjectProperties

- src/org/omegat/Bundle.properties
- src/org/omegat/filters2/text/bundles/ResourceBundleFilter.java
- src/org/omegat/filters2/text/bundles/ResourceBundleOptionsDialog.form
- src/org/omegat/filters2/text/bundles/ResourceBundleOptionsDialog.java
- test/data/filters/resourceBundle/.gitattributes
- test/data/filters/resourceBundle/file-ResourceBundleFilter-NonASCIIComments.properties
- test/src/org/omegat/filters/ResourceBundleFilterTest.java
- Link:  https://sourceforge.net/p/omegat/bugs/1116/
- Title:  BundleProperties fIlter should accept UTF-8 properties file
- LInk: https://sourceforge.net/p/omegat/feature-requests/1634/
- Title: BundleProperties Filter: write properties file in UTF-8 w/o escape in default
- Fix BUGS#1116 https://sourceforge.net/p/omegat/bugs/1116/
- Add preference option force to write Java 8 compatible escaped properties and set default to true, escaping.
- Accept UTF-8 encoded properties file in default.
- Add Regression test for ed5e7da83b5c Reproduce reported issue
> 46573: Error: java.io.IOException: /Users/suzume/Documents/Repositories/OmegaT plugin FR/source/omt-package/omt-package.properties
> 46573: Error: …
> Filter: ResourceBundleFilter: Add option to write in UTF-8

- src/org/omegat/core/data/ExternalTMFactory.java
- src/org/omegat/util/TMXReader2.java
- test/data/tmx/en-US_en-GB_fr_sr.tmx
- test/data/tmx/en-US_sr.tmx
- test/src/org/omegat/core/data/ExternalTMFactoryTest.java
- test/src/org/omegat/core/statistics/FindMatchesTest.java
Resolve [RFE#1578](https://sourceforge.net/p/omegat/feature-requests/1578/)
When `ExternalTMFactory.TMXLoader.PROP_FOREIGN_MATCH` is `true`, TM has an entry translation text is as same as source text  that source language is as same as target language.
> TM: Prevent showing externalTM's sourceText as translation when foreign language allowed (RFE#1578)

- src/org/omegat/Bundle.properties
- src/org/omegat/convert/ConvertProject26to37team.java
When try to convert a project that is git repository but forget an initial commit of project files,
OmegaT crash with NPE.
This change to log warning and reason, and show
message dialog and continue to process.
Fix BUGS#1118
- Link:  https://sourceforge.net/p/omegat/bugs/1118/
- Title:  When converting git local-managed project, OmegaT raise NPE
-  Check empty repository remote URL before try to get commit.HEAD
-  Log and show dialog instead of crash with exception
-  Avoid NPE
> Fix NPE on team project conversion

- build.gradle
- PDFBox@2.0.27
- DSL4j@0.5.3
- Stardict4j@0.4.1
- Add support for old dictionaries
- Fix downstream build error
- Title
* URL
-
-
-
> Bump dependencies versions

- Plugins.properties
- src/org/omegat/core/dictionaries/DictionariesManager.java
- src/org/omegat/core/dictionaries/LingvoDSL.java
- src/org/omegat/core/dictionaries/StarDict.java
- test/src/org/omegat/core/dictionaries/DictionariesManagerTest.java
- Register dictionary drivers, LingvoDSL and StarDict through core API.
- Add class path to Plugins.properties.
- It allow clarify a core API, these drivers is not core.
Refactoring for future source tree management and clarify core API.
-
-
-
> Make dictionary drivers as true plugin

- doc_src/en/OmegaTUsersManual_xinclude full.xml
The manual is not a draft anymore :-)
The PR removes the DRAFT label from the guide pages.
> Remove the DRAFT label from the title

- doc_src/whc-toc.xsl
The message.xml file in not necessary anymore in the DocBook set. It was used to create an "Appendix" header for the HTML set, but the header is now created from the DocBook set itself.
> Remove messages.xml. It is not used in the DocBook build process.

- build.gradle
- config/checkstyle/checkstyle.xml
- CheckStyle has a XXE  vulnerability that fixed in 8.29
- CVE-2019-9658
- CVE-2019-10782
Security
> [Security] Bump Checkstyle@8.45.1

- src/org/omegat/gui/glossary/TransTipsPopup.java
when context menu on glossary match on source text show replace candidate, and when mouse is hover on the candidate text, OmegaT show glossary comment as tooltip when it exist.
- Improving the right-click menu on underlined words
* https://sourceforge.net/p/omegat/feature-requests/1515/
-
> Show glossary comment on context menu candidate

- src/org/omegat/Bundle.properties
[documentation]
- Add missing periods at the end of sentences in command line help.
> Fix inconsistency in use of periods in command line help

- src/org/omegat/Bundle.properties
- src/org/omegat/gui/dictionaries/DictionariesTextArea.java
- src/org/omegat/util/Preferences.java
- Visual confirmation that dictionary was searched
* https://sourceforge.net/p/omegat/feature-requests/1633/
- Introduce preference NOTIFY_DICTIONARY_NOHIT
- When set notify even when no search result, it notify with color
> Dictionary: notify when search done but no data

- src/org/omegat/gui/exttrans/MachineTranslateTextArea.java
- src/org/omegat/gui/main/ConsoleWindow.java
- src/org/omegat/gui/main/IMainWindow.java
- src/org/omegat/gui/main/MainWindow.java
- src/org/omegat/util/gui/StaticUIUtils.java
- test-integration/src/org/omegat/core/data/TestTeamIntegrationChild.java
- test/src/org/omegat/core/TestCore.java
Panes need to handle its visible state when user ask actions.
related #348
- Introduce `MainWIndow#getDesktop` that returns `DockingDesktop`  object.
- Introduce `StaticUIUtils#requestVisible` method
> Introduce requestVisible method to unhide/show hidden panes

- build.gradle
- docs_devel/docs/30.CodingStyles.md
Clean up and reorganize Gradle tasks
- refactoring build configuration
- Drop java web start related tasks
- Organize manual and workflow toolings to be "omegat workflow" group
- Run tasks to be "application" group
- Some tasks to be "verification" group
- Some dist creation tasks to be "distribution" group
- JavadocJar and SourceJar are configured in java closure
> Gradle: reorganize tasks

- build.gradle
Stardict4j Changes on v0.5.0
- Drop dependency for Caffeine cache library
- Use internal cache code based on LinkedHashMap
- Can disable drivers cache by setting cacheSize as 0
No ticket but it is related to #373
- Bump stardict4j@0.5.0
> Bump dependency stardict4j@0.5.0

- build.gradle
N.A.
- Add Jacoco configurations to detect  packages/classes without unit test
- Set minimum coverage to 20%
- Exclude generated code, data class, gui classes
- It is not mandatory; comment out check dependency
[What is a reasonable code coverage?](https://stackoverflow.com/a/90021/4467057)
> Gradle: add jacoco verification rules

- doc_src/en/App_Bidi.xml
- doc_src/en/Menus_Edit.xml
- doc_src/en/Menus_View.xml
- doc_src/en/OmegaT5_Appendices.xml
- src/org/omegat/Bundle.properties
Documentation: https://sourceforge.net/p/omegat/documentation/400/
- This PR reverts the use of `Bidi` instead of `Unicode` in the Bidi related features.
- It adds a small appendix to clarify the use of the various features.
- It adds better cross-reference between the manual parts.
> Clarify the Bidi related information

- doc_src/en/Dialogs_ProjectProperties.xml
- doc_src/en/Menus_Edit.xml
- doc_src/en/Menus_GoTo.xml
- doc_src/en/Menus_Options.xml
- doc_src/en/Menus_Project.xml
- doc_src/en/Menus_Tools.xml
- doc_src/en/Menus_View.xml
- doc_src/en/OmegaT5_EditorsPanes.xml
- doc_src/en/OmegaT5_Menus.xml
- doc_src/en/Windows_Aligner.xml
- doc_src/en/Windows_Scripts.xml
- doc_src/en/Windows_SourceFilesList.xml
- doc_src/en/Windows_TextReplace.xml
- doc_src/en/Windows_TextSearch.xml
- src/org/omegat/Bundle.properties
- src/org/omegat/gui/main/MainWindowMenu.java
Revision of the pane chapter, consisting mainly of phrasing changes to tighten up wording, and fixing typos.
There is one major change:
In the note giving examples of modifications translators can make to the editor to adapt it to their workflow, I changed the text of  item (starting on Line #430) about inserting source text to match the new proposed default.
> Check and fine-tune the remaining chapters.

- build.gradle
- docs_devel/docs/26.Caching.md
- docs_devel/docs/index.md
- src/org/omegat/core/machinetranslators/BaseTranslate.java
Replace MT connectors cache with JCache mechanism
- Add Caffeine cache library and its jcache module
- Use jcache on MT cache
- Avoid OOM
JCache is a standard API in Java JSR-107.
Successor of #369
> MT connectors: cache with JCache

- doc_src/en/HowTo_Run.xml
https://sourceforge.net/p/omegat/documentation/398/
- macOS offers a command (`open`) that allows for opening many things
- that command can be used to launch OmegaT through OmegaT.app
- This PR adds the minimal documentation to cover `open`
> OmegaT.app can be used with open be launched from the command line.

- docs_devel/docs/19.PluginManifest.md
- docs_devel/docs/91.appendix.md
N.A.
- Fix header level error
-  don't jump from H1 to H3
- Fix anchor: don't put link on title
> docs_devel: fix header levels and anchor error

- src/org/omegat/core/machinetranslators/BaseTranslate.java
A method signature change cause MT plugin become MethodNotFound error.
This fix the bug.
> MT: fix method signature change caused not found from plugin

- doc_src/en/App_FileFilters.xml
Address the issues found by Hiroshi regarding the description of the ${nameOnly-`number`} and ${extension-`number`} target file name variables.
@miurahr
Does this address your concerns?
> Clarify target file filter variable use

- test/src/org/omegat/core/data/RealProjectTest.java
Because the project is not closed at the end of the test, the `omegat.project` file is locked and cause an Exception during cleanup.
> Minor fix to make RealProjectTest test pass on Windows

- doc_src/en/HowTo_Run.xml
- doc_src/en/HowTo_UseTeamProject.xml
- doc_src/en/Introduction.xml
- doc_src/en/Menus_Edit.xml
- doc_src/en/Menus_View.xml
- doc_src/en/OmegaT5_Preferences.xml
- doc_src/en/OmegaT5_ProjectFolder.xml
- release/changes.txt
- src/org/omegat/Bundle.properties
- src/org/omegat/Bundle_us.properties
I'm putting this up as a draft to get opinions first before finalizing this proposed cosmetic change.
As far as I can see, the current user facing material (manual, UI, `changes.txt`) primarily uses American spelling, with the occasional instance of British spelling sneaking up in words like colour (color).
I'd like to reflect the more international composiiton of both the OmegaT team and its community of users, and since I'm Canadian, I'd like to update all user facing material to Canadian spelling, which is most often a compromise between American and British spelling.
In practice, that means sticking to "-ize" in words like "recognize" or "realize", but using "-our" in words like "colour".
Thoughts, objections, comments?
> Unify to "-our" spelling in user facing material

- src/org/omegat/core/statistics/FindMatches.java
- Title Matches containing non-alphabetical text are ignored in TM leverage
* https://sourceforge.net/p/omegat/bugs/1003/
- Removes the test that prevents the third percentage to be calculated if the first two are below the threshold.
> fix: always try to calculate the third TM match score (untokenized)

- src/org/omegat/filters4/xml/AbstractXmlFilter.java
- src/org/omegat/filters4/xml/openxml/OpenXmlFilter.java
- src/org/omegat/filters4/xml/xliff/Xliff2Filter.java
Xliff2Filter use  `try { ... } catch (NPE e) { ..} `. This type of block is not recommended,
and update as `if (foo !=null) { ...} else {... }`.   
refactor
- Refactor Xliff2Filter to avoid catch NPE to process.
- Update javadoc/comments
> refactor(filters4): avoid catching NPE

- src/org/omegat/Bundle.properties
The UI still had instances of "guide" instead of "manual"
> Change "guide" to "manual"

- build.gradle
- src/org/omegat/Bundle.properties
- src/org/omegat/core/team2/impl/GITCredentialsProvider.java
- src/org/omegat/core/team2/impl/GITRemoteRepository2.java
- test/src/org/omegat/core/team2/impl/GITCredentialsProviderTest.java
JSch has been unmaintained and JGit goes to Apache MINA sshd for its target.
This PR migrate ssh transport to use Apache MINA sshd.
**THIS IS A CHANGE for OmegaT@6.1.0**
- Related PR #240 for OmegaT@5.8.0
- Bump JGit@6.1.0
- Fix [BUGS#1075](https://sourceforge.net/p/omegat/bugs/1075/)
- Support elliptic curve cryptography ed25519 and ecdsa keys [RFE#1598](https://sourceforge.net/p/omegat/feature-requests/1598/)
- Remove dependency for JSch and JSch agentproxy utilities.
- Use Apache MINA sshd for ssh connection and agent proxy.
Future tasks
ssh-agent support by JGit through apache MINA sshd is merged into JGit 6.0 (minimum Java 11)
https://git.eclipse.org/c/jgit/jgit.git/commit/?id=634302d2da74226cff9f78e121ad5b8216c476e6
The PR is successor of  PR #161 and #162.
> Team: Git: migrate to Apache MINA sshd (RFE#1598)

- build.gradle
- src/org/omegat/convert/v20to21/Convert20to21.java
- src/org/omegat/core/statistics/StatsResult.java
- src/org/omegat/filters2/master/FilterMaster.java
- src/org/omegat/util/JaxbXmlMapper.java
- src/org/omegat/util/Preferences.java
- src/org/omegat/util/PreferencesXML.java
- src/org/omegat/util/ProjectFileStorage.java
- src/org/omegat/util/TMXReader2.java
- src/org/omegat/util/TMXWriter2.java
- src/org/omegat/util/xml/DefaultEntityFilter.java
- src/org/omegat/util/xml/XMLAttribute.java
- src/org/omegat/util/xml/XMLBlock.java
- src/org/omegat/util/xml/XMLReader.java
- src/org/omegat/util/xml/XMLStreamReader.java
- test/src/org/omegat/filters/XLIFFFilterTest.java
- test/src/org/omegat/util/PreferencesTest.java
- test/src/org/omegat/util/TMXWriterTest.java
- test/src/org/omegat/util/XMLStreamReaderTest.java
- Use Jackson library as XML parser
- https://sourceforge.net/p/omegat/feature-requests/1582/
- Improve TBX parsing
- https://sourceforge.net/p/omegat/feature-requests/1268/
- Replace JAXB parser with Jackson XML parser
- Patch generated definition of gen.core.project.Masks to add annotation of
@JacksonXmlElementWrapper(useWrapping=false)
because of known issue.
- Update TMXWriterTest to check with system line separator
It is because XML parser can automatically change /r/n into
XML entity `&#xD;/n` when `System.lineSeparator()` is /n
- Update `TMXReader2` to detect both "lang" and "xml:lang"
some implementation return "lang" from "xml:lang" but
other can return "xml:lang" as is.
- Drop JAXB parser from GlossaryReaderTBX class.
- Use jackson for TaasClient class
- Replace PreferencesXML …
> [6.1] Use Jackson XML dataformat for JAXB parser and replace TMX, TBX and omegat.prefs loader/saver

- src/org/omegat/gui/dictionaries/DictionariesTextArea.java
- src/org/omegat/gui/editor/EditorController.java
- src/org/omegat/gui/editor/EditorTextArea3.java
- src/org/omegat/gui/editor/autocompleter/AutoCompleter.java
- src/org/omegat/gui/glossary/GlossaryTextArea.java
- src/org/omegat/gui/matches/MatchesTextArea.java
- src/org/omegat/gui/multtrans/MultipleTransPane.java
- src/org/omegat/gui/search/EntryListPane.java
- src/org/omegat/util/Java8Compat.java
- src/org/omegat/util/gui/JTextPaneLinkifier.java
modelToView and viewToModel is deprecated from Java9.
This replace these with modelToView2D and viewToModel2D
Resolve a part of Java17 compatibility issues.
- Link: https://sourceforge.net/p/omegat/feature-requests/1525/
- Title: Java17 Compatibility
- Deplicate `org.omegat.util.Java8Compat.modelToView` and `viewToMode` compat methods
- Use `modelToView2D` and `viewToModel2D` as replacement. These methods are introduced in Java 7
> [Java17] Replace modelToView and viewToModel with modelToView2D and viewToModel2D

- build.gradle
- src/org/omegat/Bundle.properties
- src/org/omegat/core/machinetranslators/AbstractMyMemoryTranslate.java
- src/org/omegat/core/machinetranslators/ApertiumTranslate.java
- src/org/omegat/core/machinetranslators/DeepLTranslate.java
- src/org/omegat/core/machinetranslators/Google2Translate.java
- src/org/omegat/core/machinetranslators/IBMWatsonTranslate.java
- src/org/omegat/core/machinetranslators/MyMemoryHumanTranslate.java
- src/org/omegat/core/machinetranslators/MyMemoryMachineTranslate.java
- src/org/omegat/core/machinetranslators/YandexCloudTranslate.java
- src/org/omegat/gui/exttrans/MachineTranslateTextArea.java
- test/src/org/omegat/core/machinetranslators/ApertiumTranslateTest.java
- test/src/org/omegat/core/machinetranslators/DeepLTranslateTest.java
- test/src/org/omegat/core/machinetranslators/Google2TranslateTest.java
- test/src/org/omegat/core/machinetranslators/IBMWatsonTranslateTest.java
- test/src/org/omegat/core/machinetranslators/MyMemoryTranslationTest.java
- test/src/org/omegat/core/machinetranslators/TestMachineTranslatorBase.java
- test/src/org/omegat/core/machinetranslators/YandexCloudTranslateTest.java
- #1141 MT engines show JSON parser error as translated text
* https://sourceforge.net/p/omegat/bugs/1141
- Add tests to make http connection,  check request and send back mock response. 
- Apertium
- DeepL
- IBMWatson
- Google2
- MyMemory (Human, Machine)
- Fix bugs that produce NPE,  send error message to translate pane.
- Throw MachineTranslateError instead of generic java.lang.Exception when http connection error
> MT:  http json tests, fixes and improves error case behavior

- build.gradle
- lib/licenses/Licenses.txt
Java 17 drop Nashorn javascript engine
This change add dependency for nashorn engine
- Java 17 compatibility
* https://sourceforge.net/p/omegat/feature-requests/1525/
-
-
-
> [java17] Add nashorn javascript engine

- build.gradle
- src/org/omegat/Bundle.properties
- src/org/omegat/core/segmentation/LanguageCodes.java
- src/org/omegat/core/segmentation/MapRule.java
- src/org/omegat/core/segmentation/Rule.java
- src/org/omegat/core/segmentation/SRX.java
- src/org/omegat/core/segmentation/datamodels/MappingRulesModel.java
- src/org/omegat/gui/segmentation/SegmentationCustomizerController.java
- test/src/org/omegat/core/segmentation/SRXTest.java
- BUG fix
-  SRX conf file is produced with localized name of language
-  https://sourceforge.net/p/omegat/bugs/1160/
- Use Jackson library as XML parser
- https://sourceforge.net/p/omegat/feature-requests/1582/
- Use Jackson XML mapper to write SRX file.
- Use XMLStreamInput to read SRX and conf file.
- Fix MapRule#setLanguage to store Language Code instead of Language name
- Add org.omegat.core.segmentation.LanguageCodes.getLanguageCodeByName static method to get the code
- Rename MapRule#getLanguage to MapRule#getLanguageName
- Rename MapRUle#getLanguageCode to MapRule#getLanguage
- Fix SRX#copy method to copy also a version, or other attributes
- Set  segmentSubFlows and cascade is true in default
- Drop JAXB dependency from runtime
- Fix SRX …
> Enhance/Fix bug: SRX reader/writer, support buggy CONF file to migrate correct SRX file 

- build.gradle
- src/org/omegat/core/machinetranslators/MyMemoryMachineTranslate.java
- src/org/omegat/core/spellchecker/SpellChecker.java
- src/org/omegat/core/spellchecker/SpellCheckerLangToolHunspell.java
- src/org/omegat/core/team2/RebaseAndCommit.java
- src/org/omegat/gui/editor/mark/ProtectedPartsMarker.java
- src/org/omegat/gui/main/ProjectUICommands.java
- src/org/omegat/gui/preferences/view/LanguageToolConfigurationController.java
- src/org/omegat/gui/properties/SegmentPropertiesArea.java
- src/org/omegat/languagetools/LanguageToolNativeBridge.java
- src/org/omegat/tokenizer/BaseTokenizer.java
- src/org/omegat/util/ProjectFileStorage.java
- test-integration/src/org/omegat/core/data/TestTeamIntegration.java
- test/src/org/omegat/languagetools/LanguageToolTest.java
- test/src/org/omegat/tokenizer/TokenizerTest.java
- Feature
- Upgrade to LanguageTool 3.6
- https://sourceforge.net/p/omegat/feature-requests/1299/
- Lucene 5.2 does not work under WebStart
- https://sourceforge.net/p/omegat/bugs/813/
- Fix BUGS#813: The bug was fixed in Lucene 5.5.3 and later
- Bump LanguageTool@5.7
- Update LanguageToolTest expectations according to behavior changes on LanguageTool 3.5->5.7
-  Belarusian on LT@5.7 is deperecated, so I added suppresswarning for it.
In RFE#1299 @amake said
> I have this 90% done locally:
> 
> Upgrade to LanguageTool 4.9
> Upgrade to Lucene 5.5.5
> The remaining issue is that LanguageTool switched Hunspell implementations, and the new one ([hunspell-java](https://gitlab.com/dumonts/hunspell-java)) has multiple JARs containing native binaries which complicates code signing for the Mac …
> Gradle: use LanguageTools@5.7 and Lucene@5.5.5

- src/org/omegat/core/machinetranslators/ApertiumTranslate.java
- src/org/omegat/core/machinetranslators/BaseCachedTranslate.java
- src/org/omegat/core/machinetranslators/BaseTranslate.java
- src/org/omegat/core/machinetranslators/BelazarTranslate.java
- src/org/omegat/core/machinetranslators/DeepLTranslate.java
- src/org/omegat/core/machinetranslators/Google2Translate.java
- src/org/omegat/core/machinetranslators/IBMWatsonTranslate.java
- src/org/omegat/core/machinetranslators/MyMemoryHumanTranslate.java
- src/org/omegat/core/machinetranslators/MyMemoryMachineTranslate.java
- src/org/omegat/core/machinetranslators/YandexCloudTranslate.java
- src/org/omegat/gui/exttrans/IMachineTranslation.java
refactor
Suggested in PR #470
- Introduce `BaseCachedTranslate` class that has Cache layer.
- Change `BaseTranslate` not to handle cache
- Introduce `BaseTranslate#getTruncateText`  and handle source text max length in common
- Add constructor with maxTextLength
> Refactor(MT):  handle maxTextLength in BaseTranslate

- tipoftheday/docs/tips/en/shortcut_note.html
- tipoftheday/docs/tips/ja/shortcut_note.html
- Current shortcut for note/editor pane is ctrl alt 0/9
-
-
-
> docs(tips): fix shortcut key assign

- src/org/omegat/Bundle.properties
- src/org/omegat/gui/main/ProjectUICommands.java
- src/org/omegat/util/FileUtil.java
backport https://github.com/omegat-org/omegat/pull/509 into releases/6.0 release branch.
- Backup file does not created in no-team project
* https://sourceforge.net/p/omegat/bugs/1159/
- Fix degrade on https://github.com/omegat-org/omegat/pull/415
- ref; https://github.com/omegat-org/omegat/pull/415#issuecomment-1449046191
- When project is not a team project, there does not produce a backup file when user does not change property.
- Backport from 6.1 development master branch.
> [backport 6.0] Improve handling of backup file of omegat.project

- src/org/omegat/gui/editor/SegmentBuilder.java
- src/org/omegat/gui/preferences/view/EditingBehaviorController.java
Commit b06f906e6f contains some mistaken double negations between insertSource and DONT_INSERT_SOURCE_TEXT:
if DONT_INSERT_SOURCE_TEXT_DEFAULT = false then defaultRadio = true and leaveEmptyRadio = false 
if DONT_INSERT_SOURCE_TEXT_DEFAULT = true then defaultRadio = false and leaveEmptyRadio = true 
Also in SegmentBuilder, isInsertSource is true if DONT_INSERT_SOURCE_TEXT_DEFAULT is false, not the contrary!
https://sourceforge.net/p/omegat/bugs/1155/
Note: bug absent from last published 5.7.1, but present in 5.8, 6.0 and 6.1
> Correct double negations

- release/changes.txt
- src/org/omegat/util/JaxbXmlMapper.java
- test/data/project/entities.project
- test/src/org/omegat/util/ProjectFileStorageTest.java
- Project not loaded if it contains DTD internal entities
* https://sourceforge.net/p/omegat/bugs/1163/
- Essentially, it sets the `XMLInputFactory.SUPPORT_DTD` flag to true when creating the XmlMapper
See also: https://sourceforge.net/p/omegat/mailman/message/37805777/
> Allow DTD parsing in order to load internal entities

- src/org/omegat/core/segmentation/Rule.java
There's nothing preventing the segmentation configuration (`.srx` or `.conf`) from having undefined `beforebreak` and `afterbreak` elements. If there's such an empty rule:
```xml
<languagerule languagerulename="New language and country">
<rule/>
</languagerule>
```
a NullPointerException is thrown when loading a project.
> Check that a segmentation rule has beforeBreak/afterBreak attributes

- build.gradle
- tipoftheday/build.gradle
Bump tipoftheday@0.4.1 that drop xml-apis
and update transient dependencies
- swingbox@1.2.4
- jstyleparser@4.1.1
- cssbox4@4.21 which drop xml-apis deps
- Title
* URL
- Bump tipoftheday library to vresion 0.4.1
An alternative fix for #553
> fix: drop xml-apis dependency

- doc_src/ca/First_Steps.xml
- doc_src/en/First_Steps.xml
- doc_src/ja/First_Steps.xml
- docs/ca/first_steps.html
- docs/en/first_steps.html
- docs/ja/first_steps.html
When show on OmegaT version number in First step article, it should be as same as OmegaT release version.
Current version number is set from manual version, that is incorrect.
-  First step document show wrong OmegaT version
* https://sourceforge.net/p/omegat/documentation/409/
- Remove referece to manual version.
-
-
> docs(first step): remove version string from First_Step

- build.gradle
Changes from 1.10.9
- Apache SSHD libraries upgraded to version 2.9.2
- SVNKIT-770: Support "aarch64" (M1) architecture for Mac.
- SVNKit 1.10.9 was a  first version that SQLJet become GPL3 compatible. It depends on JNA 3.3.0 which was very old.
- SVNKit 1.10.11 update its JNA dependency to 5.8.0.
- It also update Apache SSHD dependency on wihch OmegaT 6.1 depends.
- M1/M2 mac support
> chore(deps): Bump svnkit@1.10.11

- src/org/omegat/Bundle.properties
- src/org/omegat/filters3/xml/XMLFilter.java
- src/org/omegat/filters3/xml/docbook/DocBookFilter.java
JAXB SAX parser is known as XXE vulnerable default configuration.
This change make it strengthen for XXE attack.
- Title
* URL
-  Disable external entities and xinclude feature
-  Add setSAXFeature method for docbook filter
-  docbook filter relax a protection
Reference: 
https://securityboulevard.com/2020/09/xml-external-entity-xxe-pitfalls-with-jaxb/
> Security: filters3: protect XXE parser attack in default parser config

- build.gradle
- test/src/org/omegat/languagetools/LanguageToolTest.java
- exclude duplicated slf4j logging module
- use Assert.assertThrows for error check test
- improve a test message because an old XML API was removed in LanguageTool 3.7 and later.
refactoring
> refactor: improve LanguageToolTest

- src/org/omegat/filters2/master/FilterMaster.java
- test/src/org/omegat/filters2/FilterMasterTest.java
- Default filters settings don't initialize options
* https://sourceforge.net/p/omegat/bugs/1167/
> fix: avoid using filter option with `null` name

- src/org/omegat/logger.properties
- Suppress jStyleParser warnings
- Useless warning log from CSS parser library
*https://sourceforge.net/p/omegat/bugs/1169
- Add log level configuration in logger.properties
> [BUGS#1169] fix: supress useless warnings

- build.gradle
- test/src/svn/BundleTest.java
- Allow UTF-8 character for comments, especially for author name
- Add compiler flag to allow UTF-8 in java source files
- Update test case not to check US-ASCII
- A check should be done by spotless and checkstyle, instead of crafted one
Here is a Dev-ML discussion thread about BUNDLE file.
https://sourceforge.net/p/omegat/mailman/omegat-development/thread/8zfUNKLS058FYMIUPADGzNmrOOu_73IQWvrNRLFGTbfPmZke8l6fR9yAtLT2j1cGOo6ZpeQ4j-hNbT8fNAfgAtaEb2kmScQffrmXhGtZmx4%3D%40northside.tokyo/#msg37844491
> chore: allow UTF-8 character as source file

- build.gradle
- tipoftheday/src/main/java/org/omegat/gui/tipoftheday/TipOfTheDayController.java
Disable tipoftheday plugin bundle into releaase package
- change config key
- no bundle tipofheday module
> [6.1] feat: not include tipoftheday module into release

- src/org/omegat/gui/preferences/view/AppearanceController.java
- src/org/omegat/gui/preferences/view/AppearancePreferencesPanel.form
- src/org/omegat/gui/preferences/view/AppearancePreferencesPanel.java
According to devevelpment ML discussion and result, disable newUI feature configuraiton.
Disable newUI experimental UI for 6.1 release
-  remove preference option
> [6.1] feat: disable newUI configuration

- src/org/omegat/core/data/RealProject.java
Current OmegaT raises NPE when the mandatory writable glossary file is out of project root.  ~~This change to show warning dialog and gracefully  throws exception with a clear reason.~~  This proposal remove a dead line which raise NPE.
- [OmTdev] [BUG] build/install/OmegaT/OmegaT
* https://sourceforge.net/p/omegat/mailman/message/37842271/
-  Remove dead code which raise NPE when glossaryPath is null
> [6.1] fix NPE when team project with glossary outside

- build.gradle
Refactoring in PR#570, tweaking to reduce duplication of multiple libraries versions. PR#570 passed the check, but I might make mistake at lucene-gosen dependency.
The issue is reported at dev ML
https://sourceforge.net/p/omegat/mailman/message/37843223/
- Reported at development ML
https://sourceforge.net/p/omegat/mailman/message/37843223/
-  Revert exclude line of lucene-gosen to be lucene-gosen-ipa
> [6.1]fix: dependency inconsistency in lucene-gosen

- src/org/omegat/Bundle.properties
- src/org/omegat/core/data/RealProject.java
Backport error message enhance from 6.0/6.1
- OmegaT cannot load a project and error dialog with FileSystemLoopException
* https://sourceforge.net/p/omegat/bugs/1168
- Improve behavior on BUGS#1168 by @miurahr "OmegaT cannot load a project and error dialog with FileSystemLoopException"
- style: Reword new error messages by @kazephil: I rephrased the new error messages a little, and replaced a few unnecessary exclamation marks I happened to notice at the same time. (I thought I'd cleaned them all up a little while back, but I guess I missed a few.)
- style: Update file loop error message by @kazephil: I changed the message again to make it easier to understand for people less familiar with computers.
The …
> [5.8][BUGS#1168] feat: error message for loop link

- docs_devel/docs/30.CodingStyles.md
- src/org/omegat/core/team2/impl/GITExternalGpgSigner.java
- src/org/omegat/gui/editor/SegmentBuilder.java
- src/org/omegat/gui/exttrans/IMTGlossarySupplier.java
- src/org/omegat/gui/notes/NotesTextArea.java
- src/org/omegat/gui/preferences/view/EditingBehaviorPanel.java
- src/org/omegat/tokenizer/LuceneGermanTokenizer.java
- src/org/omegat/util/Preferences.java
- test/src/org/omegat/core/statistics/FindMatchesTest.java
- test/src/org/omegat/core/team2/SVNRemoteRepository2IT.java
- test/src/org/omegat/util/HTMLUtilsTest.java
- test/src/svn/BundleTest.java
Allowing UTF-8 in Java code has a risk of malformded commits that is hard to detect in review process.
It is known as “Trojan Source” Attack.
[The answer is proper review](https://research.swtch.com/trojan#review)
Making LTR/RTL code points visible is particularly important for review tools. The proposal here
is improve review process to check dangerous character in source code when Pull-Request.
The PR also update developer note about coding sytle.
- test: check a existence of Right-to-Left-Override "\u202e" character that is used to inject malformded code in the code
- test: check a existence of invisible characters such as  TAB, Zenkaku-Space, Non breakable space in the coee
- Please see https://attack.mitre.org/techniques/T1036/002/
for …
> [6.1] feat/style: check malformed character in java source

- src/org/omegat/core/team2/impl/GITCredentialsProvider.java
- Apache SSHD change a behavior in recent version
- Team(git): when connecting new server, connection failed
- https://sourceforge.net/p/omegat/bugs/1177
- When connecting new server, OmegaT failed to connect because of unknown fingerprint message.
- In previous versions, Apache MINA SSHD put message in YesNoType item, but now it send message in information type.
-
> fix(git): Grab hostkey fingerprint message from apache sshd

- ci/azure-pipelines/build_steps.yml
- ci/azure-pipelines/check_steps.yml
- ci/azure-pipelines/publish_release.yml
- ci/azure-pipelines/publish_weekly.yml
Current CI/CD use artifact publish feature of Azure pipelines. This storage area is limited for free account.
Uploading sourceforege site can be failed, and rerun can failed when uploading artifact.
We can skip upload/download artifact so this skip procedure.
It reduce build duration and stability in weekly and release Ci/CD.
> chore(ci): no use of artifact upload

- src/org/omegat/Bundle.properties
This PR produces the following diff between releases/5.8 and releases/6.0:
```diff
diff --git a/src/org/omegat/Bundle.properties b/src/org/omegat/Bundle.properties
index 97cba6ebe..5bd80081b 100644
--- a/src/org/omegat/Bundle.properties
+++ b/src/org/omegat/Bundle.properties
@@ -18,7 +18,7 @@
-#               Home page: http://www.omegat.org/
+#               Home page: https://www.omegat.org/
#
@@ -34,7 +34,7 @@
#
-# along with this program.  If not, see <http://www.gnu.org/licenses/>.
+# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#**************************************************************************/
#
```
Which is what @kosivantsov was requesting all along.
> (final) align 6.0 and 5.8 bundle

- build.gradle
- local.properties.example
- #1179 build/release: Windows binary signature with PKCS#11 HSM
*  https://sourceforge.net/p/omegat/bugs/1179
- Remove a way to sign with Docker because of supporting HSM
- Update local.properties keys for PKCS#11
- Improve unsigned/signed exe generation
- make unsigned exe generation task not using ant task and use copy and delete task for moving artifact
- signed exe generation task as Exec type, not sequence of procedure for keeping idempotency.
- Fix error with GString conversion
- Tested with my private key stored in HSM with ACR37U-A1 usb dongle
- I use a proprietary pkcs11 access module
When you have private key and certs in HSM, you can test new config wit `winNoJRESigned` task.
> chore(gradle): support PKCS#11 signing with HSM

- docs/index.html
- src/org/omegat/core/segmentation/SRX.java
- src/org/omegat/filters2/master/FilterMaster.java
- src/org/omegat/util/ProjectFileStorage.java
- test/src/org/omegat/filters2/master/FilterMasterTest.java
- OmegaT produce several empty tags in project files 
- we can observe `<otherAttributes/>, <include/> and <exclude/>` in omegat.properties
- `<formathandle/>` in segmentation.srx file 
-  `<option/>` in filters.xml
- Title
* URL
-  Add `Include.Include.NON_EMPTY` paremter to XmlMapper
> fix(xml): serialize without empty list

- build.gradle
- src/org/omegat/core/dictionaries/StarDict.java
Adding support for Stardict XDXF type of dictionaryu format.
- Add XDXF as allowed text type
- Add converter from XDXF content to HTML
Releated issue: 
- Dictionary displays apostrophe as html entitty code
https://sourceforge.net/p/omegat/bugs/1181
``` 
<c c="xxxxxx">...</c> (c c stands for Color Code)  Marks text with a given color.
The syntax for "c" attribute is the same as for "color" attribute of "font" tag in HTML.
If the color attribute is omitted, the default color is implied.  The default color is
chosen by the dictionary program.
<k> Key phrase is a phrase by which an article containing it can be found.
Article may contain more than one key phrase.
Tag <k> may not be nested …
```
> [BUGS#1181] feat: add support for XDXF article in StarDict

- azure-pipelines.yml
- ci/azure-pipelines/integ_test_steps.yml
- test-integration/docker/client/Dockerfile
- test-integration/docker/client/entrypoint.sh
This PR try to add 10 min Integration-Test before release build.
It improve a quality of weekly release. 
-  Add integration test stage in azure-pipelines YAML
> chore(ci): run integration test before weekly release

- build.gradle
- release/linux-specific/OmegaT
- src/org/omegat/Main.java
- There is a hack to change application name on Gnome shell, committed in 2013, that use reflective access to sun.awt.X11.XToolKit class. This causes warning log on Java 9-16.
- Java 17 and ongoing, there is no "--illegal-access=permit" JVM option, so "--add-opens" is a only way to handle it.
- Change launcher script, build.gradle run options
- There is also a minor fix to deal `setAccesible` method become unrecommended, so use `trySetAccessible` method.
Fix the issue about JVM print warning in stderr 
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.omegat.Main (file:/opt/omegat/OmegaT_5.8.0/OmegaT.jar) to field sun.awt.X11.XToolkit.awtAppClassName
WARNING: Please consider reporting this to the maintainers of org.omegat.Main …
```
> fix(linux): suppress illegal reflective access warning

- build.gradle
iscc task run from container may sometimes different user than operator uid/gid. It can cause a chmod failure.
It allows the failure and move it to doFirst block to avoid error.
- Fix weekly release task in CI
> chore(gradle): allow failure of chmod in winJRE(64) task

- build.gradle
Set task group for tasks for tasks that is mandatory in the release procedure.
- omegat release
- publishManual
- publishJavadoc
- publishVersion
- updateManuals
- omegat distribution
- mac
-  linux
-  win
-  winJRE64Signed
-  winJRESigned
-  winNoJRESigned 
- macSignedDistZip 
-  macNotarize 
-  macDistZip
omegat-dev ML discusstion
https://sourceforge.net/p/omegat/mailman/message/37860965/
> chore(gradle): add task group to some

- src/org/omegat/gui/main/MainWindow.java
Extend MainWindow#displayErrorRB and MainWindow#displayWarningRB to show multiple lines of message according to "\n" in a message.
- 
An enhancement is suggested in #600
> feat: display(Error|Warning)RB show multi-line message

- src/org/omegat/gui/dialogs/PreferencesDialog.java
- src/org/omegat/gui/preferences/IPreferencesController.java
- src/org/omegat/gui/preferences/PreferencesWindowController.java
- src/org/omegat/gui/preferences/view/PluginsPreferencesController.java
- src/org/omegat/gui/preferences/view/SecureStoreController.java
When there is no field to restore, OmegaT disable restore button.
- Remove "Restore defaults" button where it has no function
* https://sourceforge.net/p/omegat/feature-requests/1364/
-  IPreferencesController: add default method canRestoreDefaults
-  Return false when controller do not have restore function.
> [RFE#1364] feat(preference): Disable restore button when no feature

- src/org/omegat/core/team2/impl/SVNAuthenticationManager.java
- src/org/omegat/core/team2/impl/SVNRemoteRepository2.java
- test-integration/src/org/omegat/core/data/TestTeamIntegration.java
SVNKit 1.10.5 and later support apache sshd and recommend to switch to it.
SVNKIT-759: Apache sshd based implementation for svn+ssh:// protocol as an alternative to trilead.
- Team: SVN support svn+ssh protocol with key authentication
- https://sourceforge.net/p/omegat/feature-requests/1700/
-  Team: SVN: Replacing trilead-ssh2 with Apache sshd
- https://sourceforge.net/p/omegat/feature-requests/1699/
- Set System property to specify Apache MINA-SSHD for SVNKit for team subversion connections
- It supports EC cipher
- SVN/Git use a common apache ssh library for team connections
> [6.1][RFE#1169] feat: use Apache MINA SSHD for SVN transport

- docs_devel/docs/90.ReleaseProcedure.md
- update document
- publishVersion task uploads Version.properties file. It should not be changed before publishedVersion task.
-
> docs_devel: release procedure: bump after publishVersion

- doc_src/en/Menus_Edit.xml
Bring the 6.0 manual up to date with the explanation for alternative translations.
> chore: Cherry-pick expanded alternative translation explanation into released manual

- doc_src/en/Menus_Edit.xml
Bring the 5.8 manual up to date with the explanation for alternative translations.
> chore: Cherry-pick expanded alternative translation explanation into released manual (5.8)

- build.gradle
- release/changes.txt
- src/org/omegat/core/dictionaries/StarDict.java
Backport
- Dictionary displays apostrophe as html entitty code
* https://sourceforge.net/p/omegat/bugs/1181
- Quick and darty hack to support XDXF type of article
(cherry picked from commit 5cde153b7bacf37ad8a16ceddd8d061875bb1aed)
- feat(stardict): support styles for XDXF type
(cherry picked from commit fd285e049fb1485a6f4fb8cda83f9f2862617305)
- feat(stardict/xdxf): support link/image/audio
- Support iref, rref tags
- remove kref
(cherry picked from commit b5c24a1029c8469bb22c7ee919135fbe51cd9218)
Back port from https://github.com/omegat-org/omegat/pull/628
> [6.0]  [BUGS#1181] feat: add support for XDXF article in StarDict

- src/org/omegat/filters2/master/FiltersTableModel.java
- src/org/omegat/gui/filters2/FiltersCustomizerController.java
- Update Filter customizer change when next edit
- resolve BUGS#1045
- Changes in "Edit Filter"dialog window not reflected when the window is called up again
* https://sourceforge.net/p/omegat/bugs/1045/ 
- Update FiltersCustomizer table model class with data POJO class
- Set updated config in FiltersCustomizer table when edit
- Add `setFilter` method for table model
> fix: FiltersCustomizer consistency

- release/changes.txt
- src/org/omegat/filters4/xml/xliff/AbstractXliffFilter.java
Currently notes are displayed like this :
instead of :
because we use the default `toString()` of the XMLEvent instead of the actual content of the character event.
+ minor refactor (removing extraneous calls to `.toString()` and replacing `list.size() > 0` by `!list.isEmpty()` to make a clearer intent.
- Content of notes elements are not displayed correctly with Xliff filter
* https://sourceforge.net/p/omegat/bugs/1192/
> fix: display the correct content of the Notes in XLIFF

- src/org/omegat/util/ProjectFileStorage.java
- test/data/project/team.project
- test/data/project/teamMapWithExclude.project
- test/data/project/teamWithMap.project
- test/src/org/omegat/util/ProjectFileStorageTest.java
ProjectFileStorage class is use to read and write `omegat.project` file.
This PR change Jackson object mapper configuration using custom serializer for `otherAttributes` attribute.
Current master branch produce `<otherAttributes/>` node in `omegat.project` when there is no attribute, and fix it with custom selializer.
I've added test cases that is as same as `releases/6.0`, so it guarantee a compaitibility between versions.
- ProjectFile has unwanted XML element otherAttributes
* https://sourceforge.net/p/omegat/bugs/1191/
- Add test as same as  #662
- Add custom serializer for `Map<QName, String> otherAttributes` object.
> [6.1][BUGS#1191] fix: jackson custom serializer for ProjectFileStorage

- docs_devel/docs/34.IntegrationTest.md
- test-integration/runner.sh
Integration test sometimes become failed with server error.
It is because a test procedure is not good to clean up after test.
A proposal here change a developer manual to do clean it after the test done.
Also I add a helper script to help developer to do it with one liner.
- Integration test(docker) failure with 503
* https://sourceforge.net/p/omegat/bugs/1199/
-
-
-
> docs_devel: update Integration-test procedure

- doc_src/en/Menus_Options.xml
- doc_src/en/OmegaT_EditorsPanes.xml
- doc_src/en/OmegaT_Preferences.xml
Here's the PR covering the backport to 6.0
Which ticket is resolved?
Machine translation activation
https://sourceforge.net/p/omegat/documentation/413/
What does this PR change?
Expand and clarify the explanations concerning machine translation in the manual.
> docs: Expand on machine translation explanation (6.0)

- release/changes.txt
- src/org/omegat/filters3/xml/XMLTag.java
- src/org/omegat/gui/common/EntryInfoPane.java
- src/org/omegat/gui/editor/AlphabeticalMarkers.java
- src/org/omegat/gui/editor/Document3.java
- src/org/omegat/gui/editor/EditorController.java
- src/org/omegat/gui/editor/SegmentBuilder.java
- src/org/omegat/gui/editor/mark/ProtectedPartsMarker.java
- src/org/omegat/gui/editor/mark/RemoveTagMarker.java
- src/org/omegat/gui/matches/MatchesVarExpansion.java
- src/org/omegat/gui/properties/SegmentPropertiesArea.java
- src/org/omegat/util/BiDiUtils.java
- src/org/omegat/util/Language.java
- test/src/org/omegat/gui/matches/MatchesVarExpansionTest.java
- test/src/org/omegat/util/BiDiUtilsTest.java
Form #519 to be cleaner commits.
-  Incorrect display of RTL segments in the Fuzzy Matches pane
- https://sourceforge.net/p/omegat/bugs/558/
- Introduce BiDiUtils utility class, gathering all BiDi things
- Add test for MatchesVarExpansion and then extend it to support RtL
- refactor Document3.ORIENTATION enum in BiDiUtils.ORIENTATION
- refactor to remove ORIENTATION from return value of internal API
- Set LtR/RtL properly on editor and another panes
- refactor Langauge#isRTL Language#localeIsRTL to move into BiDiUtils
- All commits author @damien-rembert
> [BUGS#558] fix: incorrect display of rtl segments in fuzzy match pane

- release/changes.txt
- src/org/omegat/core/machinetranslators/Google2Translate.java
Google translate v2 api may return a model field.
OmegaT google2 MT connector ignore it for quick fix.
- Google2 MT connector failed to parse response
* https://sourceforge.net/p/omegat/bugs/1206/
- Backport #711
- Ignore "model" property in response json.
> [6.0] fix: google2 MT to ignore model property

- machinetranslators/google/src/main/java/org/omegat/core/machinetranslators/Google2Translate.java
- machinetranslators/google/src/test/java/org/omegat/core/machinetranslators/Google2TranslateTest.java
- release/changes.txt
Google translate v2 api may return response with a model field. OmegaT google2 MT connector has a definition that miss the model field.
- Google2 Translate MT connector failed to parse response
- https://sourceforge.net/p/omegat/bugs/1206/
Dev ML post
https://sourceforge.net/p/omegat/mailman/omegat-development/thread/f5c71c67-4cef-0044-735d-f469240aaa8e%40marcprior.de/#msg37874311
- define field "model" in parser
> [BUGS#1206] fix: google2 MT to ignore model property

- release/changes.txt
- src/org/omegat/core/data/RealProject.java
When we call "commit target files", whenever from console or UI, the TXT and JSON statistics files are re-generated and if you are in a team project, the JSON is also sent to the repository
For explanation about the reason:
https://sourceforge.net/p/omegat/mailman/message/37780726/
https://sourceforge.net/p/omegat/feature-requests/1690/
> [RFE#1690] Have "Commit Target Files" also commit statistics file

- build.gradle
- machinetranslators/apertium/build.gradle
- machinetranslators/belazar/build.gradle
- machinetranslators/deepl/build.gradle
- machinetranslators/google/build.gradle
- machinetranslators/ibmwatson/build.gradle
- machinetranslators/mymemory/build.gradle
- machinetranslators/yandex/build.gradle
- release/changes.txt
- test/src/org/omegat/languagetools/LuceneGosenCompatibilityTest.java
- tipoftheday/build.gradle
languagetool-ja uses (potentially) incompatible  lucene-gosen-ipadic@6.2.1 against lucene-5.5.5
OmegaT forked and published lucene-gosen-ipadic@5.0.0 but languagetool-ja uses incompatible method.
OmegaT project update lucene-gosen to compile with lucene 5.5.5 and add work around for languagetool-ja@6.1 change, and publish to maven central.
- LanguageTool6 lucene-gosen-ipadic from omegat project is incompatible
- https://sourceforge.net/p/omegat/bugs/1204/ 
- fork, modify and publish `org.omegat.lucene:lucene-gosen:5.5.1:ipadic` from https://github.com/omegat-org/lucene-gosen
- add unit tests for regression check and compatibility check
> [BUGS#1204] fix: dependencies `lucene-gosen:5.5.1:ipadic`  based on `Lucene/Solr-5.5.5` and `LanguageTool-6.1`

- doc_src/en/Menus_Edit.xml
- doc_src/en/OmegaT_EditorsPanes.xml
- Add information on navigating between available fuzzy matches using the CTRL+up or down arrow keys.
- Fix the shortcut in the Edit menu description.
> chore: Update documentation fuzzy match navigation.

- docs_devel/docs/34.IntegrationTest.md
- src/org/omegat/util/Log.java
- test-integration/docker/client/Dockerfile
- test-integration/docker/client/entrypoint.sh
- test-integration/docker/client/gitconfig
- test-integration/logger.properties
- test-integration/runner.sh
We have multiple container handle commands  popular for users.
This change support nerdctl and podman which are alternative to docker.
These tools are built upon OCI standard specification. 
The PR also add a support of custom logging configuration with System property. 
Support netctl and podman for integration-test
- Support custom logging.properties by system property.
- Improve client docker image, by coping source code using rsync, that solves permission problem
- Imporve runner.sh helper to support nerdctl and podman through docker-compose
> chore(integ-test): support nerdctl and custom logging.propeties

- src/org/omegat/util/DirectoryMonitor.java
- src/org/omegat/util/FileUtil.java
- Selection of match for pre-translation varies through different OS's
* https://sourceforge.net/p/omegat/bugs/1213/
- When TMX are loaded, the order is determined by `java.io.File.listFiles()` which can return files in a directory in a different order depending on the underlying OS. This fix sort the resulting files by name, case-insensitive.
> BUG#1213 - Ensure file order consistency between platforms

- src/org/omegat/core/data/RealProject.java
- src/org/omegat/core/team2/RebaseAndCommit.java
PR #645 , that try to resolve BUGS#1164,  breaks team feature so integration test become failure.
So it is revertd in PR #643 .
- Translation memories are not correctly reloaded after team synchronization
- https://sourceforge.net/p/omegat/bugs/1164
- Extend `RebaseAndCommit.IRebase` interface to have `reload` method
- `RebaseAndCommit#rebaseAndCommit` properly call `reload` with target file when it is ready to load 
- Improve integration-test container configuration
> [BUGS#1164] Fix properly reloading TMX after team synchronization

- build.gradle
- ci/azure-pipelines/check_steps.yml
- src/org/omegat/Main.java
- src/org/omegat/gui/glossary/GlossaryReaderTBX.java
- test/src/org/omegat/filters2/master/FilterMasterTest.java
- test/src/org/omegat/gui/glossary/GlossaryReaderTBXTest.java
Ensure pass unit tests with Java 17
Feature requests: 
- #1682 Ensure that OmegaT functions properly under Java 17
* https://sourceforge.net/p/omegat/feature-requests/1682/
- Add task testOnJava17 in CI
- bump jacoco@0.8.10,  Java 18,19 are supported in jacoco@0.8.9
- removal of an unused property in the resource bundle: STARTUP_JAXB_LINKAGE_ERROR
> [RFE#1682] fix: Support Java 17 runtime and ensure CI test on Java17

- src/org/omegat/filters2/text/bundles/ResourceBundleFilter.java
- src/org/omegat/filters2/text/bundles/ResourceBundleOptionsDialog.java
- test/src/org/omegat/filters/ResourceBundleFilterTest.java
- not to force escape Unicode
- Java 9 and later change the default of resource bundle charset to UTF-8, so there is no need to escape it now. 
- #1716 ResourceBundle Filter: default not to escape Unicode character
- https://sourceforge.net/p/omegat/feature-requests/1716/
- Change option default
> feat(filter/bundle): change default not to do a Unicode escape (java 9-21 standard)

- release/changes.txt
- src/org/omegat/core/data/ImportFromAutoTMX.java
- src/org/omegat/core/data/RealProject.java
Actually if you create a project containing something in tm/auto, the segments are auto-populated but when you click on SAVE OmegaT does consider the project as non-modified and saves nothing, despite the fact that importing segments against empty file is a modification.
Bug fix -> [bug]
https://sourceforge.net/p/omegat/bugs/1185/
https://sourceforge.net/p/omegat/bugs/1200/
Beginning of tm/auto import a new boolean didAnyChange is false. If any segmennt has been imported it is set to true
At the end of the process, if didAnyChange = true then project.isModified = true
> [BUGS#1185] Saving does not register pre-translation in new projects

- .github/workflows/checkstyle-annotate.yml
- .github/workflows/spotbugs-annotate.yml
- azure-pipelines.yml
- ci/azure-pipelines/check_steps.yml
- ci/azure-pipelines/test_java17_steps.yml
- ci/azure-pipelines/test_steps.yml
It is not easy to see spotbugs error on azure pipelines CI log because there are so many warnings on checkstyles.
This PR resolves a pain point by running spotbugs on github actions and put annotations on PR file diffs.
CI enhancement
- Refactoring azure pipelines flows
- Add spotbugs actions on Github
> chore: annotate spotbugs errors on github PR

- src/org/omegat/Bundle.properties
- src/org/omegat/filters2/text/bundles/ResourceBundleFilter.java
- src/org/omegat/filters2/text/bundles/ResourceBundleOptionsDialog.form
- src/org/omegat/filters2/text/bundles/ResourceBundleOptionsDialog.java
Implement "TODO" commented feature of resource bundle filter.
- #1713 ResourceBundle filter: "Don't translate NOI18N comment" feature optional
- https://sourceforge.net/p/omegat/feature-requests/1713/
- make "don't translate NOI18N comment" feature optional
- improve unicode escape
- output standard Capital hex for escape
- improve string manipulation performance
> [RFE#1713] feat(filter/bundle): make "don't translate NOI18N comment" feature optional

- .github/workflows/spotbugs-annotate.yml
- build.gradle
- ci/github/problem-matcher.json
- languagetools/build.gradle
Show spotbugs errors on console on CI
- Add sportbugsReport task in Gradle
- Run sportbugsReport task on CI
- Annnotate Spotbugs warning/error in Github Actions using `problem-matcher.json`
The feature is discussed at
https://github.com/spotbugs/spotbugs-gradle-plugin/issues/172#issuecomment-555901305
> chore: add spotbugsReport task in Gradle and run it on CI

- build.gradle
- config/spotless/eclipse-formatting.xml
- gradle/libs.versions.toml
- gradle/utils.gradle
- test-integration/docker/client/Dockerfile
- test-integration/docker/client/entrypoint.sh
Fix build.gradle and integration-test to be compatible with Gradle 8.3 version specification.
This fixes integration-test runner.
- Integration-Test
- Copy spotless configuration under `config` folder 
- Bump gradle@8.3 inside docker image 
- Exclude `.gradle` from rsync target folders  
- Source distribution
- Fix a way to update Version.properties
- Fix dependencies issue that cause a failure of compilation with source distribution
> chore: fix integration-test to be compatible with Gradle version 8.3

- azure-pipelines.yml
- ci/azure-pipelines/integ_test_steps.yml
Integration test which run before weekly release become failure.
This change fix the issue.
- Weekly release job depends on check and integration-test
- Update integration-test yaml template to run correctly
Manual run check works fine (canceled by hand)
> chore(ci/azure pipelines): fix  integration test script for weekly release

- src/org/omegat/Main.java
- JNA's bug recorded in bugs#812 has been fixed in JNA 4.3.0 and later
- OmegaT depends on JNA 5.13.0 now.
refactor
- JNA encoding issue on non-UTF-8 platforms
- https://sourceforge.net/p/omegat/bugs/812/
- Remove workaournd for old jna bug.
BUGS#812 affected on Windows, when using Hunspell dictionary that filename is out of ASCII characters like CP1252.
> [BUGS#812] refactor: remove workaround for old JNA bug

- src/org/omegat/filters2/master/PluginUtils.java
- test-integration/plugins.properties
- test-integration/src/org/omegat/core/data/TestTeamIntegration.java
Now repository connectors are in-source plugin, so we need to load these plugins explicitly in integration test.
- Add PluginUtils.loadPluginFromProperties for test purpose
- Add `test-integration/plugins.properties` that lists plugins required for the test.
- Update TestTeamIntegration class to load plugins before start.
related #604
> fix(integ-test): load repository plugins

- docs_devel/docs/06.GuidelineForWelcomingBeginners
- docs_devel/docs/index.md
There are many issue tickets and bug reports in source forge issue manager and development mailing list from beginners or not well-experienced users.
Many of them does not have enough information to reproduce the issue and identify a target source code. To reply and support these post consumes limited times and motivations of contributors.
To help these members, I'd like to add a guidelines and text snippet to reply easily.
> docs(devel): add guideline for welcoming beginners

- src/org/omegat/core/data/RealProject.java
- src/org/omegat/core/team2/RebaseAndCommit.java
- test-integration/src/org/omegat/core/data/TestTeamIntegrationChild.java
When saving a team project and another member have updated translations and OmegaT run rebaseAndCommit, enforce TM become removed from the result.
The change here to change that when merge TMX from remote and local, we save it into file, but DON'T replace it in projectTMX. We reload the file when necessary, in RebaseAndCommit.IRebase#reload.
It changes RealProject#mergeTMX to return merged TMX and the caller should handle the tmx.
-  Translation memories are not correctly reloaded after team synchronization
- https://sourceforge.net/p/omegat/bugs/1164/
- `RealProject#mergeTMX` to return merged TMX and the caller should handle the tmx.
- `RealProject#mergeTMX` does not replace `projectTMX` with `mergedTMX`
-
- Passed integration test in 10 min.
- When running OmegaT with …
> [BUGS#1164] fix: break project translation when rebase and commit

- src/org/omegat/gui/preferences/view/TagProcessingOptionsController.java
- src/org/omegat/util/PatternConsts.java
Fix the bug OmegaT does not allow disable tag regex "\\d+"
Bugs: https://sourceforge.net/p/omegat/bugs/1194
- Add special configuration value `"__EMPTY__"` to express ""
- When remove tag value in preference, OmegaT store it as `"__EMPTY__"`
> [BUGS#1194] fix: allow empty custom tag

- build.gradle
- compose.yml
- Bump Docker JDK to jdk-17.0.8.1.0+1
- Running test-integ on Java 17
Now we bundles Adoptium OpenJDK JRE 17 for weekly release distribution.
It is better to test team integrations with JDK17.
> chore(test-integ): update build.gradle/compose.yml

- src/org/omegat/gui/preferences/view/TagProcessingOptionsController.java
- src/org/omegat/util/PatternConsts.java
- Regular expression for custom tags
- https://sourceforge.net/p/omegat/bugs/1193/
- Allow empty custom tag pattern
- When not exists a configuration key of custom tag pattern, assume default from PatternsConsts.DEFAULT_CHECK_CUSTOM_PATERN
> [BUGS#1193] fix: allow custom tag empty

- release/changes.txt
- src/org/omegat/core/team2/impl/GITRemoteRepository2.java
When user clone team project at first, OmegaT clone with `--depth 1`  to be a shallow clone to reduce disk usage.
Implement RFE#1720
- Download team project with shallow history
- https://sourceforge.net/p/omegat/feature-requests/1720/
- set CloneCommand object configure  `setDepth(1)`
> feat: team: shallow clone team project

- azure-pipelines.yml
- ci/azure-pipelines/check_steps.yml
- ci/azure-pipelines/test_java17_steps.yml
- test/src/org/omegat/MainTest.java
- test/src/org/omegat/core/team2/AbstractRemoteRepository2IT.java
- test/src/org/omegat/filters/HTMLFilter2Test.java
- test/src/org/omegat/filters/MozillaFTLFilterTest.java
- test/src/org/omegat/filters/POFilterTest.java
- test/src/org/omegat/gui/dialogs/DialogsTest.java
- test/src/org/omegat/util/FileUtilTest.java
- test/src/org/omegat/util/TMXWriterTest.java
Enable CI tests on Windows and Mac
-  Unit tests failed on Windows
- https://sourceforge.net/p/omegat/bugs/1223/
Fix or skip following tests
- Fixed
- MainTest#testConsoleTranslate
- GitRemoteRepository2IT#testGetRecentlyDeletedFiles
- SVNRemoteRepository2IT#testGetRecenlyDeletedFIles
- Skipped on Windows
- HTML2Test#testLayoutTrimWhitespace
- MozillaTLFFilterTest#testTranslate
- PoFilterTest#testParseFuzzyCtx
- PoFilterTest#testTranslateMonolingual
- PoFilterTest#testAutoFillInPluralStatement
- PoFIlterTest#testTranslate
> Chore(CI):  CI test on windows mac

- ci/iscc
ci/iscc helper command depends on amake/innosetup docker image. now project github.com/amake/innosetup-docker changes image tags
- amake/innosetup:latest is Debian Buster, InnoSetup 6, 32bit
- amake/innosetup:innosetup6 is Debian Buster, InnoSetup 6, 32bit
- amake/innosetup:innosetup6-buster is Debian Buster, InnoSetup 6, 32bit
- amake/innosetup:innosetup6-bookworm is Debian Bookworm, InnoSetup 6, 32bit
- amake/innosetup:64bit is Debian Buster, InnoSetup 6, 64bit
- amake/innosetup:64bit-buster is Debian Buster, InnoSetup 6, 64bit
- amake/innosetup:64bit-bookworm is Debian Bookworm, InnoSetup 6, 64bit
We use
`amake/innosetup:64bit-buster is Debian Buster, InnoSetup 6, 64bit` for our purpose.
> chore: fix: change iscc container

- release/changes.txt
- src/org/omegat/util/TMXWriter2.java
- test/src/org/omegat/util/TMXWriterTest.java
- Unit tests failed on Windows
- https://sourceforge.net/p/omegat/bugs/1223/
- OmegaT does not handle line breaks correctly on Windows
- https://sourceforge.net/p/omegat/bugs/1219/
- Set Woodstox property
-  not to normalize `/r` in TMXWriter2.  Default is "do normalize"
- produce self-contained empty tags
> [BUGS#1219] fix: tweak Woodstox parser behavior

- azure-pipelines.yml
- ci/azure-pipelines/build_doc_steps.yml
- ci/azure-pipelines/publish_manual_snapshot.yml
Publish snapshot version of manual  when writers update files under `doc_src`.
the manual will be appeared in https://omegat.sourceforge.io/manual-snapshot/
- Define CI task to build manual HTMLs and publish at web site.
- Spin out PR from #705 that have a same change
- When #705 merged, document writer have a difficulty to check resulted manuals. The DocCI will help writers to check resulted HTML manuals on web browser without running build job.
> chore(ci): publish webManual in snapshot folder

- src/org/omegat/Bundle.properties
- src/org/omegat/core/team2/gui/UserPassDialog.java
- src/org/omegat/core/team2/impl/GITCredentialsProvider.java
- src/org/omegat/core/team2/impl/SVNAuthenticationManager.java
- src/org/omegat/core/team2/impl/TeamUtils.java
- Add checkbox in user/pass dialog to ask credentials for per-host or per-repository
- RFE#1719  Give a selection of perHost/PerRespo credentials treatment
- https://sourceforge.net/p/omegat/feature-requests/1719/
- Refactor save/loadCredentials methods
- When per-repo selected
- Store "scheme://host(:port)/path" as a key
> feat: selector credentials per host/repo

- src/org/omegat/Bundle.properties
- src/org/omegat/gui/main/ProjectUICommands.java
- src/org/omegat/util/HttpConnectionUtils.java
- src/org/omegat/util/ProjectFileStorage.java
- src/org/omegat/util/gui/JTextPaneLinkifier.java
- Resolved BUGS#459 Print Exception with Invalid URL in "Import From MediaWiki..
- Print Exception with Invalid URL in "Import From MediaWiki..
- https://sourceforge.net/p/omegat/bugs/459/
- Extend HttpConnectionUtils to have checkUrl method
- Refactor JTextPaneLinkifier to move URL_PATTERN to HttpConnectionUtils class
> [BUGS#459] fix: check URL before doWikiGet

- src/org/omegat/filters2/text/mozftl/MozillaFTLFilter.java
- test/src/org/omegat/filters/MozillaFTLFilterTest.java
MozillaFTLFilter sometimes insert "\n" even it uses `LineBreakPreservingReader`, so it breaks translation output.
- Unit tests failed on Windows
- https://sourceforge.net/p/omegat/bugs/1223/
- replace `write("\n")` with `write(lbpr.getLineBreak())`
- refactor `str1 += str2` with `StringBuider` 
- When translation has a line break, covert  `trans.replaceAll("\n", lbpr.getLinebreak())`
> [BUGS#1223] fix: MozillaFTLFilter:  preserve line-break on windows

- config/checkstyle/suppressions.xml
- src/org/omegat/filters4/AbstractZipFilter.java
- src/org/omegat/filters4/xml/AbstractXmlFilter.java
- src/org/omegat/filters4/xml/xliff/AbstractXliffFilter.java
- src/org/omegat/filters4/xml/xliff/Xliff1Filter.java
- src/org/omegat/filters4/xml/xliff/Xliff2Filter.java
There are many code style warnings/errors on StaX filters.
The changes here to resolve the style errors.
These style errors has been introduced when accepting filters, all checkstyle errors are treated as warning, and author and reviewer does not aware of it.
- refactor
- Unnecessary static for `eFactory` field
- Unnecessary silent override of `eFactory`
- Unnecessary nested blocks
- Bad style of commenting in `if-elseif` syntax
- Unnecessary static for `toPair` method
- Use `try-resource` in `AbstractZipFilter`
> refactor(filters4): XLIFF1,2 filters and abstract classes

- ci/iscc
Fix CI failure for weekly release
- CI: weekly release failed with permission error inside docker image
- https://sourceforge.net/p/omegat/bugs/1228/
- Update uid/gid in docker image as same as host when launch `ci/iscc`
- Only docker environment supported, no change in containerd/nerdctl (TBD)
- Intend to fix the CI issue with docker on Ubuntu 22.04 hosted by Microsoft
> [BUGS#1228] chore: workaround innosetup docker permission issue

- build.gradle
Refactor a build mac distribution section of `buid.gradle` .
Drop  `mac` and `armMac` definition of `distributions` section.
This make simpler `distributions` definition. 
- Bugs
- Build and release changes
- distribution for macOS only run on Java runtime 11
- https://sourceforge.net/p/omegat/bugs/1230/
-  Tasks to generate mac distributions are defined as same way as Windows tasks.
- Change `plist.info` to be accept JVM  `11+`
- Build `appbundler` with `jvmrequired: ${jvmrequired}` other than direct value, and substitute it in pacakging.
> chore: mac distributions:  allow JRE other than java 11

- build.gradle
- gradle/libs.versions.toml
- src/org/omegat/gui/glossary/DefaultGlossaryRenderer.java
- src/org/omegat/gui/glossary/DictionaryGlossaryRenderer.java
- src/org/omegat/gui/glossary/GlossaryTextArea.java
- src/org/omegat/gui/glossary/IGlossaryRenderer.java
- src/org/omegat/util/HttpConnectionUtils.java
- src/org/omegat/util/gui/JTextPaneLinkifier.java
- test/data/glossaries/test.tab
- test/src/org/omegat/gui/glossary/GlossaryReaderTSVTest.java
- test/src/org/omegat/gui/glossary/GlossaryTextAreaTest.java
- test/src/org/omegat/util/HttpConnectionUtilsTest.java
When showing glossary which contains URL in comment, OmegaT decode percent-encoded URL into human readable URL. 
When OmegaT accept URL which contains non-ascii characters, OmegaT encode URL into percent-encoded one, and write to writable glossary TSV file.
- https://sourceforge.net/p/omegat/bugs/1229
- Show percent escaped URL as a decoded path with Unicode characters
- Introduce HttpsConnectionUtils#decodeHttpsURLs utility method
- Add commons-validator dependency to validate URLs
- Enhance HttpConnectionUtils#checkUrl utility to use commons-validator to validate URL.
- Enhance IGlossaryRenderer.HtmlTarget#append to decode percent-encoded URLs
- Update test cases
- Document writer should suggest users to put URL with encoded form in glossary file. …
> feat: glossary: encode URL in glossary comment and linkify percent escaped URLs with human readable link text

- build.gradle
- ci/azure-pipelines/build_steps.yml
Fix weekly release tasks
- Hopefully fix a build failure of zip extraction of win64 JRE
- Fix dependency for jpackage tasks
- Tweak CI build task not to duplicate run of test/check
> chore: update JRE to 17.0.9.9+1

- config/checkstyle/suppressions.xml
- gradle/libs.versions.toml
- src/org/omegat/filters2/AbstractFilter.java
- src/org/omegat/filters2/html2/HTMLFilter2.java
- src/org/omegat/filters2/html2/HTMLReader.java
- src/org/omegat/filters2/moodlephp/MoodlePHPFilter.java
- src/org/omegat/filters2/mozdtd/MozillaDTDFilter.java
- src/org/omegat/filters2/mozlang/MozillaLangFilter.java
- src/org/omegat/filters2/po/PoFilter.java
- src/org/omegat/filters2/text/bundles/ResourceBundleFilter.java
- src/org/omegat/util/MagicComment.java
- src/org/omegat/util/TMXReader2.java
- test/fixtures/org/omegat/core/TestCore.java
- test/src/org/omegat/filters/HTMLFilter2Test.java
Improvement, refactor and style change for AbstractFilter class.
Some filter override `processFile(File, File, fc)`  to enforce encoding, but I prefer to implement `getInputEncoding` and `getOutputEncoding` methods.
Refactoring
- #1726 AbstractFilter should handle BOM when create reader
- https://sourceforge.net/p/omegat/feature-requests/1726/
- Bump commons-io@2.15.0
- Modify MagicComment and TMXReader2 classes 
- Use BOMInputStream class where hand-crafted detectors in AbstractFilter class
- Change fallback default charsets to `StandardCharsets.UTF_8`  rather than `Charset.defaultCharset()`
- Prefer override get(Input|Output)Encoding method instead of create(Reader|Writer)
- MozillaDTDFilter
- MozillaLangFilter
- ResourceBundleFilter
- MoodlePHPFilter
- PoFilter …
> [RFE#1726] refactor: filters: create(Reader|Writer), get(Input|Output)Encoding overrides

- build.gradle
- Avoid incompatible clauses in build.gradle  against configuration-cache
- replace `doFirst` and `doLast` groovy closure blocks with genuine tasks to support configuration cache
- jpackage-gradle-plugin has a bug not to be compatible with gradle configuration cache
https://github.com/petr-panteleyev/jpackage-gradle-plugin/issues/27
> chore: update jpackage tasks

- src/org/omegat/filters2/latex/LatexFilter.java
- test/data/filters/Latex/file-latex-comments.tex
- test/data/filters/Latex/file-latex-items-exp.tex
- test/data/filters/Latex/file-latex-items.tex
- test/data/filters/Latex/test-article-exp.tex
- test/data/filters/Latex/test-article.tex
- test/src/org/omegat/filters/LatexFilterTest.java
Split paragraph when `\item` command accept in latex file.
- The LaTeX filter should use \item as a delimiter
- https://sourceforge.net/p/omegat/bugs/743/
- Refactoring latex filter.
- define `parBreakCommand` list
- split and translate itemized clauses
> [BUGS#743] fix: filters/latex enhance itemize parse to split paragraphs

- .git-archival.properties
- .gitattributes
- build.gradle
Use .gitattribute substitution for git-archival.properties file to determine version of git export archive.
-
-
-
> chore: use hash of commit when git export

- build.gradle
- ci/azure-pipelines/build_steps.yml
Weekly release build in 2nd Dec 2023 failed because  "updateManuals" task is removed.
This change fix the issue by reverting removal and drop the task call in CI/CD.
- Revert "updateManuals" task definition
- No necessary explicit to launch updateManuals
> chore(ci): fix unknown task updateManuals in Weekly build

- azure-pipelines.yml
- build.gradle
- ci/azure-pipelines/build_doc_steps.yml
- ci/azure-pipelines/build_steps.yml
- ci/azure-pipelines/publish_manual_snapshot.yml
- ci/azure-pipelines/publish_weekly.yml
- ci/azure-pipelines
-  build_steps.yml always stop gradle daemon
- Check previous step status when running publish_weekly.yml template
- Check previous step status when running build_doc_steps.yml template
- clean before building release packages
- build.gradle
- Add manualZips task
- Fix dependency problem around genDocIndex task
- remove dependency by sourceDistZip  
- refactoring genDocIndex task definition
- Drop  reference to "docs" folder
> chore(ci): Improve weekly publish and docCI

- build.gradle
The build.gradle file was modified to correctly define the 'mainClass' in the Mac package. This change included correcting the 'appClass' definition and adjusting the 'mainClass' to reference the application's main class. It fixed a wrong 'mainClass' in the Mac package.
-  OmegaT 6.1 macos-arm version does not launch on macOS arm machine
- https://sourceforge.net/p/omegat/bugs/1231/
> fix: mac package does not launch

- src/org/omegat/gui/glossary/GlossarySearcher.java
- Issue window cause exception
- https://sourceforge.net/p/omegat/bugs/1234/
- Resolves a bug in GlossarySearcher where the string comparison cause an index out of range exception.
- A condition check has been added to ensure that term length is greater than token length before performing substring operations.
- Resolve BUGS#1234
> [BUGS#1234] fix: GlossarySearcher token string comparison issue

- build.gradle
- docs_devel/docs/02.HowToBuild.md
- local.properties.example
- Introduce "forceSkipDocumentBuild" property which indicate to skip document build steps.
- Developer can specify Gradle property with "-P" option, such as "gradle -PforceSkipDocumentBuild=1" or via environment variable ORG_GRADLE_PROJECT_forceSkipDocumentBuild=1 
- see https://docs.gradle.org/current/userguide/project_properties.html
Dev-ML
https://sourceforge.net/p/omegat/mailman/omegat-development/thread/F86A5D44-20F7-492D-9F12-98E1C7A9DA97%40traduction-libre.org/#msg58712422
- add document build condition to check property in addition to check of existence of docker command
> chore: skip doc build when property specified

- build.gradle
- gradle.properties
- gradle/libs.versions.toml
- gradle/utils.gradle
A jpackage plugin author declined to fix the bug on gradle cache feature with my proposal to change, and express the project won't support cache feature.
The plugin has no more benefit other than a syntax sugar, so I decided to remove the plugin and migrate it as Exec task type.
Now we can enable a configuration cache and speed-up our build.
-
-
-
> chore: update linux-deb/rpm build

- .github/dependabot.yml
- .github/workflows/gradle-build-master.yml
- ci/azure-pipelines/test_steps.yml
- ci/gradle/gradle-scan.init.gradle
- settings.gradle
- CI: add dependabot
- CI: add gradle build check on github actions with gradle scan
- CI: drop build check from azure-pipelines
- Gradle: add gradle-enterprise plugin to allow gradle scan in CI
- CI: Automatically put Gradle Scan URL on PR when failure
When using Gradle Scan service, we need to agree to term of use.
https://gradle.com/legal/terms-of-use/
> chore(ci): full test on github actions

- gradle/libs.versions.toml
- Bump gradle plugin com.github.ban-manes.version@0.50.0 
- Support for Gradle 8.x
> chore: Update gradle plugin ben-manes.version@0.50.0

- src/org/omegat/gui/issues/IssuesPanelController.java
This commit introduces a change in the IssuesPanelController where the refreshData function is modified to bring the panel to the forefront each time it refreshes. This adjustment ensure that the refreshed panel remains visible and doesn't get hidden behind main window. Resolved BUGS#1225
- List of issues stays hidden in the background
- https://sourceforge.net/p/omegat/bugs/1225/
- `IssuesPanelController#refreshData` does `frame.toFront()`
> [BUGS#1225] fix: Bring Issues Panel to front on refresh

- config/checkstyle/suppressions.xml
- src/org/omegat/core/data/NotLoadedProject.java
- src/org/omegat/core/statistics/CalcMatchStatistics.java
- src/org/omegat/core/statistics/FindMatches.java
- test/data/filters/po/file-POFilter-match-stat-en-ca.po
- test/data/tmx/empty.tmx
- test/data/tmx/test-match-stat-en-ca.tmx
- test/src/org/omegat/core/statistics/CalcMatchStatisticsTest.java
- Match statistics are affected by fuzzy match threshold
- https://sourceforge.net/p/omegat/bugs/1236/
- Add a reproduce case of the bug.
- Add `ignoreThreshold` constructor boolean for `FindMatches` class.
-
> [BUGS#1236] fix: make CalcMatchStatistics ignores threshold

- build.gradle
Current configuration for launch4j specified to JRE path to be jre/ in OmegaT installation directory. This changes to be fallback to JAVA_HOME environment varialbe and PATH.
- Windows launcher does not launch when witout_JRE installer used
- https://sourceforge.net/p/omegat/bugs/1240/
- Change `build.gradle` a section `launch4j` parameter `jrePath` to be `"jre;%JAVA_HOME%;%PATH%"`
In order to debug the created executable call it with the command line argument `--l4j-debug`. This will create the log file `launch4j.log` next to the executable. please take care of write permission of `C:\Program Files\OmegaT` folder on debug session.
> [BUGS#1240]chore: windows: search JRE in PATH

- ci/iscc
- ci/osslsigncode
- doc_src/docgen
When using Rancher-desktop for container execution, it installs both docker and nerdctl commands. Because a execution of docker command with Rancher Desktop fails, check a status of `docker info` command, and wen failed, we select nerdctl. nerdctl can also be failed when user forget to start Rancher desktop. We run ``$CMD info` after the selection, then user can recognize a error with warning message to launch Rancher desktop.
The change does not affect other environment, beucase we use it when docker info or nerdctl info succeeded.
- update docgen, iscc  shell script
- replace nerdctl/docker detection 
-
> fix: docker/nerdctl detection

- release/changes.txt
- src/org/omegat/gui/main/ProjectUICommands.java
- src/org/omegat/util/FileUtil.java
- src/org/omegat/util/ProjectFileStorage.java
This is the backport from PR #575
- Error when trying to backup the project file on Windows
-  https://sourceforge.net/p/omegat/bugs/1166/
-
-
-
> [6.0][BUGS#1166]fix: write the project properties in the backup instead  of copying file

- src/org/omegat/Main.java
- src/org/omegat/core/Core.java
- src/org/omegat/util/gui/UIDesignManager.java
- Introduce getClassLoader utility method in the class and initialize does not take classloader.
- Simplify Core.initializeGUI not to take classloader.
- Simplify Main#runGUI not to take classloader.
With this change, a signature of `Core.initializeGUI` become compatible with OmegaT 5.7.1.
refactor
- refactor UIDesignManager.initialize
- pick a part of enhancement from #906
> refactor: UIDesignManager.initialize

- src/org/omegat/core/Core.java
Pull-Request #915 should keep the interface signature `Core.initializeGUI(ClassLoader, Map)` as deprecated flag.
refactor
> refactor: keep Core.initializeGUI() as deprecated

- build.gradle
There are two annotations jar files in dependency library. We observe annotations-23.0.0.jar (jetbrains) and annotations-1.1.4.jar (google-android). This change excludes android annotation library because OmegaT does not support android.
- Dependencies
-
-
-
> chore: resolve conflict in annotations jar

- build.gradle
- doc_src/build.xml
- doc_src/docgen
- doc_src/en/OmegaT_EditorsPanes.xml
- doc_src/ja/OmegaT_EditorsPanes.xml
Fix issue in manual PDF generation
-  `OmegaT_EditorPanes.xml` has duplicated "id" that cause XML error on PDF generation
- https://sourceforge.net/p/omegat/documentation/419/
- document: Manual source XML has duplicated "id" value which should be unique.
- chore: Update `doc_src/build.xml` not to generate files in source folder but write to under `build/`.  The task accept "target" argument and use it for the output folder.
- chore: Update `docgen` shell script to use `docge:apline` and `docgen:pdfgen` container image
- chore: Change font to "Noto" for PDF generation.
- chore: Fix `manualsPdfs` task properly detect output file.
> docs: fix pdf generation and restructure manual generations

- src/org/omegat/Bundle.properties
- src/org/omegat/filters2/master/FilterMaster.java
When character encoding error happened,  it is just logging but  no notification.
It is a fix to notify the problem for translators, because resulted translation files can not be completed.
- java.nio.charset.UnmappableCharacterException: Input length = 1
- Bugs: https://sourceforge.net/p/omegat/bugs/1233/
- Catch UnsupportedEncodingException, and UnmappableCharacterException and MalformedInputException in `FilterMaster#translateFile`
- The latter 2 exceptions are inherited from  CharacterCodingException.
- Raise a dialog to notify translator the problems.
> [BUGS#1233] fix: Give a proper feedback when filter got character encoding error

- src/org/omegat/Bundle.properties
- src/org/omegat/Main.java
jpackage distribution don't have `bin/java` executable. It need to find a launcher `bin/OmegaT` and execute it. This change is to check existence of `$JAVA_HOME/bin/java`, and when not found, try to check
`<OmegaT installed folder>/bin/OmegaT`.
If both java or launcher exectable are not found, the attempt is aborted and show waring message.
- #1243 When restart GUI on deb/rpm packaged OmegaT, it failed with java not found
- https://sourceforge.net/p/omegat/bugs/1243/
- Update Main#restartGUI method
> [BUGS#1243] fix: restartGUI when jpackage distribution

- src/org/omegat/filters4/xml/xliff/SdlXliff.java
Bug
- sdlxliff filter does not display (some) comments
- https://sourceforge.net/p/omegat/bugs/1244/
Problem mentioned by JC, but he sent me sample in private - see with him if the sample is confidential or not, in which case we may add a unit test.
StaX filter for SDLXLIFF improperly manages comments when used with WoodstoX parser. We already corrected similar problems with other StaX filters but we forgot this one.
To be corrected in all branches (5.8, 6.0 and 6.1)
> Correct SDLXLIFF comments

- test/data/filters/xliff/filters3/file-XLIFFFilter-cdata-bugs418.xlf
- test/src/org/omegat/filters/XLIFFFilterTest.java
Regression test
- XML filters: when data has CDATA, filters does not behave properly
- https://sourceforge.net/p/omegat/bugs/418/
- BUGS#418 claims an old XLIFF filter behaves wrongly.
-  This adds a test data with CDATA in source and target of trans-unit, and add a case in XLIFFFilterTest.
> [BUGS#418] chore: xliff: add CDATA regression test

- src/org/omegat/gui/editor/EditorController.java
- src/org/omegat/gui/notes/NotesTextArea.java
- Fix BUGS#903
- Ctrl+Z incorrectly erases contents of segment Note
- https://sourceforge.net/p/omegat/bugs/903/
- When visiting segment and update note pane when segment has note, we reset a status of undoManager after put note contents.
> [BUGS#903] fix: not-undo a pre-existed note

- src/org/omegat/filters4/xml/AbstractXmlFilter.java
- src/org/omegat/filters4/xml/xliff/AbstractXliffFilter.java
- src/org/omegat/filters4/xml/xliff/Xliff1Filter.java
- test/data/filters/xliff/filters3/file-XLIFFFilter-cdata-bugs418.xlf
- test/data/filters/xliff/filters4-xliff1/file-XLIFFFilter1-multiple-file-tag.xlf
- test/src/org/omegat/filters4/Xliff1FilterTest.java
xliff1 filter produce a broken output file when XLIFF1 file has multiple `<file>` element.
-  XLIFF1 filter produce broken trasnalated file
- https://sourceforge.net/p/omegat/bugs/1247/
- `AbstractXmlFilter#processFile`: when it calls `checkCurrentPosition`, it should be checks `isEventMode` immediately.
- Several style improvements
- Add regression tests
> [BUGS#1247]  xliff1: multiple original file source produce broken output

- src/org/omegat/gui/editor/EditorController.java
- Very slow segment switching with a lot of duplicates
* https://sourceforge.net/p/omegat/bugs/1131/
- A check is added if a segment or its note is changed before redrawing identical segments 
This bug seems to be specific to some environments. OmegaT on Debian testing x64 with OpenJDK from Debian repository is affected for sure. I also have a report that Arm Mac build suffers as well.
I've been using this fix for a year and never found any regressions.
> [BUGS#1131] fix: Redraw duplicate segments only when changed

- test/data/filters/xliff/filters4-xliff2/ex.14.5.xlf
- test/src/org/omegat/filters4/Xliff2FilterTest.java
Improve unit tests
- Improve test case with extra-ordinary cases.
- Add test case when source XLIFF file has contents with an unsupported glossary extension module.
> refactor: test for XLIFF2 glossary module

- build.gradle
- src/org/omegat/gui/editor/EditorController.java
- src/org/omegat/gui/editor/IEditor.java
- src/org/omegat/gui/editor/mark/ComesFromAutoTMMarker.java
- src/org/omegat/gui/editor/mark/ProtectedPartsMarker.java
- src/org/omegat/gui/editor/mark/RemoveTagMarker.java
- src/org/omegat/gui/scripting/ConsoleBindings.java
- test-integration/src/org/omegat/core/data/TestTeamIntegrationChild.java
- test/fixtures/org/omegat/core/TestCore.java
- test/src/org/omegat/gui/editor/mark/BiDiMarkersTest.java
- test/src/org/omegat/gui/editor/mark/ComesFromAutoTMMarkerTest.java
- test/src/org/omegat/gui/editor/mark/MarkerTestBase.java
- test/src/org/omegat/gui/editor/mark/NBSPMarkerTest.java
- test/src/org/omegat/gui/editor/mark/ProtectedPartsMarkerTest.java
- test/src/org/omegat/gui/editor/mark/RemoveTagMarkerTest.java
- test/src/org/omegat/gui/editor/mark/ReplaceMarkerTest.java
- test/src/org/omegat/gui/editor/mark/WhitespaceMarkerTest.java
- test/src/org/omegat/gui/matches/MatchesVarExpansionTest.java
> chore: add and improve maker unit tests

- src/org/omegat/core/spellchecker/SpellCheckerMarker.java
- src/org/omegat/gui/editor/mark/BidiMarkers.java
- src/org/omegat/gui/editor/mark/ComesFromAutoTMMarker.java
- src/org/omegat/gui/editor/mark/ComesFromMTMarker.java
- src/org/omegat/gui/editor/mark/ProtectedPartsMarker.java
- src/org/omegat/gui/editor/mark/ReplaceMarker.java
- src/org/omegat/gui/editor/mark/TransparentHighlightPainter.java
- src/org/omegat/gui/editor/mark/WhitespaceMarker.java
- src/org/omegat/gui/glossary/TransTipsMarker.java
There are unnecessary static variable initialization and static functions. These break registering Markers as plugins.
refactor
- avoid all `Styles` static reference in static initialization, because the reference should be happened after theme modules initialization.  
-
-
Bring improvements from #951
> refactor: markers: avoid unnecessary static

- config/checkstyle/suppressions.xml
- src/org/omegat/filters4/xml/AbstractXmlFilter.java
- src/org/omegat/filters4/xml/openxml/OpenXmlFilter.java
- src/org/omegat/filters4/xml/xliff/SdlXliff.java
- src/org/omegat/filters4/xml/xliff/Xliff1Filter.java
- src/org/omegat/filters4/xml/xliff/Xliff2Filter.java
- Complete solution to avoid StaX implementation difference.
- BUGS#1247
- Create event reader when entering event mode
#937
> [BUGS#1247] fix: filters4: create event reader when entering event mode

- doc_src/en/OmegaT_Preferences.xml
- src/org/omegat/Bundle.properties
- src/org/omegat/gui/glossary/GlossarySearcher.java
- src/org/omegat/gui/glossary/GlossaryTextArea.java
- src/org/omegat/gui/glossary/TransTipsPopup.java
- src/org/omegat/gui/preferences/view/GlossaryPreferencesController.java
- src/org/omegat/gui/preferences/view/GlossaryPreferencesPanel.form
- src/org/omegat/gui/preferences/view/GlossaryPreferencesPanel.java
- src/org/omegat/util/Preferences.java
- test/src/org/omegat/gui/glossary/FindGlossaryThreadTest.java
- Glossary popups behavior changed unintended way
- https://sourceforge.net/p/omegat/bugs/1239/
- Support sort by length of a source text when one contains another.
- It prioritizes a longer match to be shown in tooltips
- Introduce a new preference GLOSSARY_SORT_BY_SRC_LENGTH
- Configurable on glossary pane configuration button
- Configurable on preference dialog
- Update manual to add description of preference -> glossary
> [BUGS#1239] feat: glossary support optional sort by src length

- src/org/omegat/gui/glossary/GlossarySearcher.java
- test/data/glossaries/test.tab
- test/src/org/omegat/gui/glossary/GlossaryReaderTSVTest.java
- test/src/org/omegat/gui/glossary/GlossarySearcherTest.java
Backport #959
- [Short glossary items are not recognized with Korean source](https://sourceforge.net/p/omegat/bugs/1250/)
- https://sourceforge.net/p/omegat/bugs/1250/
-
-
-
> [backport/6.0][BUGS#1250] fix: glossary korean degration

- src/org/omegat/gui/glossary/GlossarySearcher.java
- test/data/glossaries/test.tab
- test/src/org/omegat/gui/glossary/GlossaryReaderTSVTest.java
- test/src/org/omegat/gui/glossary/GlossarySearcherTest.java
- Bug fix
- [Short glossary items are not recognized with Korean source](https://sourceforge.net/p/omegat/bugs/1250/)
- https://sourceforge.net/p/omegat/bugs/1250/)
- Add reproducible of the bug
- Fix the collision detection logic
-
glossary token collisions in Japanese
https://sourceforge.net/p/omegat/bugs/1034/
> [BUGS#1250] fix: korean terms are not found in glossary

- src/org/omegat/core/data/RealProject.java
- src/org/omegat/gui/glossary/GlossaryManager.java
- src/org/omegat/gui/glossary/GlossaryTextArea.java
- test-integration/src/org/omegat/core/data/TestTeamIntegration.java
- test-integration/src/org/omegat/core/data/TestTeamIntegrationChild.java
- bug fix
- enhance test 
- Team projects not saving properly or stopping synchronization
- https://sourceforge.net/p/omegat/bugs/847/
- Test a team synchronize of writable glossary file in integration test
- Start/Stop `GlossaryManager` monitor direct from `RealProject#loadProject` `RealProject#closeProject` 
- Load glossaries immediately after sync with remote
> [BUGS#847] call glossaryManager.fileChanged when sync glossary with team

- src/org/omegat/gui/main/MainWindowMenuHandler.java
fix `MainWindowMenuHandler`  to use `MainWindow#getApplicationFrame`  to get Swing JFrame component from `MainWindow` object.
refactor
Dev-ML
https://sourceforge.net/p/omegat/mailman/message/58742917/
- do not assume MainWindow class as JFrame object
- Use MainWindow#getApplicationFrame when expect parent frame
- The enforcement helps an internal change of MainWindow class
Spin out from #964 topic branch
> fix: always use MainWindow#getApplicationFrame

- aligner/src/main/java/org/omegat/gui/align/AlignerModule.java
- src/org/omegat/gui/scripting/ScriptsMonitor.java
- tipoftheday/src/main/java/org/omegat/gui/tipoftheday/TipOfTheDayController.java
These modules initialize Swing GUI parts in static context. It can be error on non-GUI environment and test environment. This fix changes these are initialized in application start event handler.
refactor
- Initialize Menu Item in Swing thread
- Avoid static initialization of Swing component in module
-
spin off change from PR #964
> refactor/gui: fix modules initialization

- test-integration/src/org/omegat/core/data/TestTeamIntegrationChild.java
Integration Test can failed with No X11 DISPLAY variable set error. It is because Integ-Test uses ProjectFactory.loadProject but it does not use `TestRealProject` overrides then it use `RealProject#mergeTmx` instead of `TestRealProject#mergeTmx` which is modified to run without X11 screen.
integration test when weekly reelases in 9 Mar. and 16 Mar 2024.
- Avoid using ProjectFactory.loadProject function
- Add TestIntegrationChild.loadProject function for replacement
- Do same thing when TestIntegrationTest load at first.
The stack trace is like as follows
TF_LOAD_ERROR
java.awt.HeadlessException:
No X11 DISPLAY variable was set,
but this program performed an operation which requires it.
at …
> chore: fix: integ-test failed with no X11 screen error

- machinetranslators/apertium/src/main/java/org/omegat/machinetranslators/apertium/ApertiumTranslate.java
Originally, the Apertium API was strict about pair language codes. For example, if `en-US` to `es-ES` translation was requested but only `en` to `es` translation was available, it would not fall back and instead report "The requested pair is not installed". For this reason, OmegaT stripped the country/variant part of the locale when calling the Apertium API.
From the current most recent version of the API (for reference: https://github.com/apertium/apertium-apy/releases/tag/v0.12.1), released a couple of weeks ago and already deployed to https://apertium.org, the API has a fallback mode. Now it tries to find an appropriate pair if the requested locale combination is not found directly.
For this reason, OmegaT should now send the whole locale and let the Apertium server choose a suitable …
> feat: send whole locale to Apertium MT

- doc_src/en/OmegaT_Preferences.xml
- src/org/omegat/Bundle.properties
- src/org/omegat/Main.java
- src/org/omegat/MainClassLoader.java
- src/org/omegat/filters2/master/PluginUtils.java
- src/org/omegat/util/PluginInstaller.java
Hardening plugin installer class
-  PluginInstaller throws NPE in certain condition
- https://sourceforge.net/p/omegat/bugs/1235/
dev-ml
https://sourceforge.net/p/omegat/mailman/omegat-development/thread/78b810a2-34f6-4416-b28e-6e1dda659f4b%40northside.tokyo/#msg58712660
- Refactor PluginUtils#loadPlugins to register "jarFile!className" URL even when it is main jar file.
- Check nullity of `currentInfo.getUrl()` and skip retrieving of jarFile object when null.
- Check jar file path that is not under installDir system directory, when try to remove it.
> [BUGS#1235] fix: hardening plugin installer utility class

- src/org/omegat/util/HttpConnectionUtils.java
- test/src/org/omegat/util/HttpConnectionUtilsTest.java
Update URL encode/decode utility to catch string may as possible as URL.   
- Links with ending parens in glossary panes
- https://sourceforge.net/p/omegat/bugs/1253/
- Add a test case with bracket and kanji characters
- Change regex to match URL, that removes "\\b" in end.
> [BUGS#1253] encode/decode URL with bracket

- build.gradle
- Fix preventing installDist when multiple executions
dev-ML
https://sourceforge.net/p/omegat/mailman/omegat-development/thread/a72a64f2-8737-4b9f-819b-6bd1713db1c6%40northside.tokyo/#msg58753665
- set application.executableDir
> chore: installDist task insist of execDir

- build.gradle
- src/org/omegat/gui/glossary/DefaultGlossaryRenderer.java
- src/org/omegat/gui/glossary/DictionaryGlossaryRenderer.java
- src/org/omegat/gui/glossary/GlossaryTextArea.java
- src/org/omegat/gui/glossary/IGlossaryRenderer.java
- src/org/omegat/util/HttpConnectionUtils.java
- src/org/omegat/util/gui/JTextPaneLinkifier.java
- test/src/org/omegat/gui/glossary/GlossaryReaderTSVTest.java
- test/src/org/omegat/gui/glossary/GlossaryTextAreaTest.java
- test/src/org/omegat/util/HttpConnectionUtilsTest.java
As request by project leader, this is backport glossary URL link enhancement from master branch.
This requires many changes from master branch.
- Show percent escaped URL as a decoded path with Unicode characters
- Introduce HttpsConnectionUtils#decodeHttpsURLs utility method
- Add commons-validator dependency to validate URLs
- Enhance HttpConnectionUtils#checkUrl utility to use commons-validator to validate URL.
- Enhance IGlossaryRenderer.HtmlTarget#append to decode percent-encoded URLs
- Update test cases
- Document writer should suggest users to put URL with encoded form in glossary file.
- Encode URL when adding glossary term with comment that contains URL
backport from 417fec84b2e803adad92c6093826f56427bc8d5a and from …
> [6.0][BUGS#1229,1253] feat: glossary: linkify percent escaped URLs with brackets

- src/org/omegat/core/team2/gui/UserPassDialog.java
This change warning to be a text field boarders with yellow background when preceding or trailing space character is found.
- Remove RED colour  background of warning message
- Add YELLOW colour background for problematic input field
- Improve check action run in SwingUtilities.invokeLater
> feat: Team credential window warn input fields when input has extra spaces 

- .github/workflows/gradle-build-master.yml
- settings.gradle
- Allow scan publish on Ci environment
- Bump gradle plugin from enterprise to develocity@3.17.2
- Allow publish only when CI environment
> chore: bump gradle develocity plugin@3.17.2

- build.gradle
- gradle/libs.versions.toml
OmegaT use WireMock for connection test mocking.
WireMock project moves groupID to "org.wiremock" and improve versions.
This PR to bump wiremock to version 3.4.2 from 3.0.1
refactoring
dev-ML
https://sourceforge.net/p/omegat/mailman/omegat-development/thread/ee7e06c3-68ef-463c-ad51-15cc1bcafb80%40northside.tokyo/#msg58769984
- Change groupId to org.wiremock
> chore: Bump wiremock@3.4.2

- build.gradle
- gradle/libs.versions.toml
- test/src/org/omegat/filters/DocBookFilterTest.java
- test/src/org/omegat/filters/TestFilterBase.java
- test/src/org/omegat/util/ProjectFileStorageTest.java
refactoring
dev-ML
https://sourceforge.net/p/omegat/mailman/omegat-development/thread/B21D5C68-C324-4085-A212-AA406547A4D7%40traductaire-libre.org/#msg58769981
- use org.xmlunit:xmlunit-assertj3:2.10.0
- rewrite ProjectFileStorageTest and TestFilterBase with xmlunit assertj style assertions
> feat(test): migrate XMLUnit legacy to assertj3

- src/org/omegat/filters4/xml/openxml/MsOfficeFileFilter.java
Temporarily inactivate Stax filter for Excel until I can debug it
(it is still here but user would have to manually add it in the filters list to use it)
> [6.0]Temporarily inactivate XLSX for StaX filter (known bug ticket #1260)

- src/org/omegat/gui/main/MainWindow.java
Extend MainWindow#displayErrorRB and MainWindow#displayWarningRB to show multiple lines of message according to "\n" in a message.
(cherry picked from commit 17e803336a6c07d994e5184382f8bd1e6f238221)
dev-ML
https://sourceforge.net/p/omegat/mailman/omegat-development/thread/a33409e9-3b54-4f5c-82af-2dd8ed1cab19%40northside.tokyo/#msg58770293
- back port an improvement in master branch
- display error message that have "\n" in String to be multi line dialog
-
> [6.0] feat: display(Error|Warning)RB show multi-line message

- docs_devel/docs/27.UtilityClasses.md
- src/org/omegat/gui/preferences/view/AppearanceController.java
- src/org/omegat/util/Platform.java
- src/org/omegat/util/StaticUtils.java
- src/org/omegat/util/gui/DesktopWrapper.java
- src/org/omegat/util/gui/UIDesignManager.java
- src/org/omegat/util/gui/UIScale.java
- src/org/omegat/util/gui/laf/SystemDarkThemeDetector.java
As discussed in [1746](https://sourceforge.net/p/omegat/feature-requests/1746/), here is the patch.
In general, `Platform.isUnix()` is preferred, which will not break Linux support.
`isX11()` was suggested. I did search in the code and the web. `(Unix|UNIX)` is used in several places in the code and the documentation. It looks to me that `UNIX(R)` is used when referring to the registered trademark, and `Unix` when referring to Unix-like and Unix variants. Thus, `isUnix()` is used in the patch.
- Title #1746 Support U*ix variants
* URL https://sourceforge.net/p/omegat/feature-requests/1746
- Support *BSD variants.
The build was successful, and I am using it. `xdg-open` is working.
> feat: support Unix-like OSes

- src/org/omegat/gui/main/MainWindow.java
- src/org/omegat/gui/main/MainWindowMenuHandler.java
- src/org/omegat/gui/main/MainWindowUI.java
MainWindowMenuHandler requires real MainWindow object instead of access through IMainWindow interface currently. This is becuase SearchWindow management is implemented in MainWindow class. We move SearchWindow management into MainWindowUI class as static function. The change removes access from MainWindowMenuHandler to MainWindow instance method.
refactor
dev-ML
https://sourceforge.net/p/omegat/mailman/omegat-development/thread/cd246ce0-44c2-4c8a-a7ec-e92f390fa488%40northside.tokyo/#msg58749145
- define Search Window manager functions in MainWindowUI class
-  static void createSearchWindow(SearchMode mode, String query)     
-  static void closeSearchWindows() 
-  static boolean reuseSearchWindow(String text) 
- Remove methods with same names in MainWidow class
- …
> refactor: SearchWindowController manager at MainWindowUI

- src/org/omegat/core/Core.java
- test-acceptance/src/org/omegat/gui/main/TestMainWindow.java
- test/fixtures/org/omegat/core/TestCoreInitializer.java
Current acceptance test is not working because of GUI initialization failure.
It is caused by incomplete initialization of GUI parts.
This PR change `Core.initializeGUI` to split two parts and define `initializeGUIimpl` function which can be called from Test code.  
-  Other
refactor
- Define `initializeGUIimpl`
- Separate a save thread initialization
- TestCoreInitializer calls `initializeGUIimpl` when environment is not headless, not a ConsoleWindow.
> refactor: test initialization of GUI component

- build.gradle
Jacoco test report only list a root project result currently.
It should show a merged result of all sub modules.
- Add Gradle plugin jacoco-report-aggregation
- Apply Jacoco plugin in all sub projects 
- Aggregate mathine translation modules and aligner module test results.
> chore: aggregate jacoco reports of modules

- src/org/omegat/core/team2/RemoteRepositoryFactory.java
- test/src/org/omegat/core/team2/RemoteRepositoryFactoryTest.java
- Fix behaviour where git repos would be recognised as SVN
* https://sourceforge.net/p/omegat/bugs/1258/
This PR implements changes recommended on the bug report:
- Assume that url that start with `https://git` are git repos
- Assume that url that end with `.git` are git repos
> [Bug#sf1258] http git repo erroneously set to svn

- compose.yml
- test-integration/docker/client/Dockerfile
Now OmegaT project is configured with Gradle 8.8 and its feature,
integration test's docker compose does not reflect it.
This PR fix the issue in integration test. 
integ-test failure lead a failure of weekly publish of packages.
-
-
-
> Chore: Fix test-integration docker configuration

- src/org/omegat/gui/main/ConsoleWindow.java
- src/org/omegat/gui/main/IMainWindow.java
- src/org/omegat/gui/main/MainWindow.java
- src/org/omegat/gui/main/MainWindowMenuHandler.java
- src/org/omegat/gui/preferences/view/AppearanceController.java
- test-acceptance/src/org/omegat/gui/main/TestMainWindow.java
- test-integration/src/org/omegat/core/data/TestTeamIntegrationChild.java
- test/fixtures/org/omegat/core/TestCore.java
extend IMainWindow API to add `resetDesktopLayout` to help menu handler to avoid direct dependency for raw MainWindow object to help test code mocking it.
refactor
- Extend IMainWindow API
- Remove dependency to "raw" mainWindow from MainWindowMenuHandler
- Update test codes according to API
> refactor: add IMainWindow#resetDesktopLayout

- test-integration/src/org/omegat/core/data/TestTeamIntegration.java
Java 13 and later change launch mechanism on linux https://bugs.openjdk.org/browse/JDK-8213192
This fixes a child process spawn error on Java 17
- Update TestIntegration class to launch child process
- change "java" with full path of java command
ref https://stackoverflow.com/questions/61301818/java-failed-to-exec-spawn-helper-error-since-moving-to-java-14-on-linux
> chore: test-integ: fix spawn with Java 17

- src/org/omegat/gui/main/MainWindowMenuHandler.java
It is required to decouple MenuHandler with real MainWindow object reference to allow mocking MainWindow in Acceptance Test. This changes a reference to mainWindow field of MainWindowMenuHandler to get application frame when exit application.
refactor
- Change reference `mainWindow` to `Core.getMainWindow()` in `prepareForExit` method.
-
-
> refactor: reduce direct reference to real MainWindow object from MenuHandler

- test/src/org/omegat/languagetools/LanguageToolTest.java
- test/src/org/omegat/languagetools/LuceneGosenCompatibilityTest.java
- Avoid direct reference of LT language classes.
- We can use LT utility methods; Languages.getLanguageByName getLanguageByShortCode getLanguageByLocale
refactor
-
-
-
> refactor: avoid usage of direct LT language class

- src/org/omegat/Main.java
- src/org/omegat/logger.properties
- src/org/omegat/util/Log.java
- OmegaT 6.1 does not write startup message in log file
- https://sourceforge.net/p/omegat/bugs/1262/
- refactor: Log static initialization
- changed: logger configuration to show time in log file
- changed: update start up message with timezone
> fix: write startup log into file

- Plugins.properties
- config/checkstyle/suppressions.xml
- release/changes.txt
- src/org/omegat/Bundle.properties
- src/org/omegat/ColorScheme_dark.properties
- src/org/omegat/ColorScheme_light.properties
- src/org/omegat/gui/editor/EditorSettings.java
- src/org/omegat/gui/editor/IEditorSettings.java
- src/org/omegat/gui/editor/MarkerController.java
- src/org/omegat/gui/editor/mark/AltTranslationsMarker.java
- src/org/omegat/gui/main/BaseMainWindowMenu.java
- src/org/omegat/gui/main/MainWindowMenuHandler.java
- src/org/omegat/util/Preferences.java
- src/org/omegat/util/gui/MenuExtender.java
- src/org/omegat/util/gui/Styles.java
- test/data/mark/alternative.tmx
- test/fixtures/org/omegat/core/TestCore.java
- test/src/org/omegat/gui/editor/mark/AltTranslationsMarkerTest.java
- test/src/org/omegat/gui/editor/mark/MarkerTestBase.java
Re-working on the proposal from @chelobaka 
I have reverted some changes from my review comment, because we now understand mark is not perfect to be a plugin.
I tweak several places to fix test errors which is caused by the proposed changes.
- Alternative translation highlight
* https://sourceforge.net/p/omegat/feature-requests/1736/
- This PR implements new highlighter for marking segments with an alternative translation.
- GUI bits one might expect for a highlighter like changing color in settings and default color values for light/dark themes.
Re-submit PR to modify #950
> [RFE#1736] feat: Alternative translation highlight

- src/org/omegat/Main.java
- src/org/omegat/filters2/master/PluginUtils.java
- test-acceptance/src/org/omegat/TestMainInitializer.java
This defines URLClassLoader class loader named THEME_CLASSLOADER that can be add URLs dynamically. It loads theme modules and plugins. Main class set the ClassLoader as UI class loader and Java Swing subsystem can find LaF classes.
refactor
dev-ML
https://sourceforge.net/p/omegat/mailman/omegat-development/thread/a2d24fed-49c2-4ea4-9ee6-3cf49c207ba6%40northside.tokyo/#msg58797265
- Define THEME_CLASSLOADER in PluginUtils
- THEME_CLASSLOADER is MainClassLoader object
- Load theme plugins with THEME_CLASSLOADER
> refactor: PluginUtils to handle theme plugins

- ci/azure-pipelines/publish_manual_snapshot.yml
Last CI build is failed because upload of snapshot manual is failed.
It is because command line scp does not have a "recursive" option.
- Use "scp -r -s" for uploading manual contents
> chore(ci): upload with recursively

- config/git/udiff.sh
Developers can use the unescape diff tool by configurae git like
```bash
git config difftool.udiff.cmd 'config/git/udiff.sh $LOCAL $REMOTE'
git config alias.udiff 'difftool --tool=udiff'
```
then developers can run like
```bash
git udiff src/org/omegat/Bundles_(lang).properties
```
Other (describe below)
developers configuration
Developers need to have "bash", "perl", "diff" and "less" commands on the environment to use.
> chore: add unescape diff tool

- ci/iscc
- ci/osslsigncode
- Backport ci/iscc and ci/osslsigncode from master branch
- These supports recent container execution environments
> [6.0] chore: backport win build shell util

- aligner/build.gradle
- build.gradle
- gradle/libs.versions.toml
- language-modules/build.gradle
- machinetranslators/apertium/build.gradle
- machinetranslators/belazar/build.gradle
- machinetranslators/deepl/build.gradle
- machinetranslators/google/build.gradle
- machinetranslators/ibmwatson/build.gradle
- machinetranslators/mymemory/build.gradle
- machinetranslators/yandex/build.gradle
- spellchecker/hunspell/build.gradle
- spellchecker/morfologik/build.gradle
- theme/build.gradle
- tipoftheday/build.gradle
We should guarantee to build from source distribution without any remote resources.
There often happens that a remote library removed and the project build is not possible.
To guarantee old OmegaT revisions building, we bundles all dependency libraries.
Now we use modular architecture, it is important to guarantee it also for modules.
- Fix a Build failure from sourceDistZip
- It is because missing dependency from `lib/provided`
- Also update removal of unused dependency
TODO
> chore: fix buid from source distribution

- build.gradle
- language-modules/build.gradle
- language-modules/src/test/java/org/omegat/languages/test/LuceneGosenCompatibilityTest.java
- src/org/omegat/languagetools/LanguageManager.java
- When loading "en-AU" LT language, it failed with IllegalArgumentException because of missing "en-US".
- Failed to load "en-AU" LT language by IllegalArgumentException
- https://sourceforge.net/p/omegat/bugs/1265/
- LanguageManager#getLTLanguage loads not only specified language, such as "en-AU" also loads variants such as "en-US", "en-GB" and "en"
> fix: LTmod's IllegalArgument on en-AU

- doc_src/en/OmegaT_Preferences.xml
- src/org/omegat/Bundle.properties
- src/org/omegat/gui/glossary/GlossarySearcher.java
- src/org/omegat/gui/glossary/GlossaryTextArea.java
- src/org/omegat/gui/glossary/TransTipsPopup.java
- src/org/omegat/gui/preferences/view/GlossaryPreferencesController.java
- src/org/omegat/gui/preferences/view/GlossaryPreferencesPanel.form
- src/org/omegat/gui/preferences/view/GlossaryPreferencesPanel.java
- src/org/omegat/util/Preferences.java
- test/src/org/omegat/gui/glossary/FindGlossaryThreadTest.java
Back port from #904
--------
* [BUGS#1239] feat: support optional sort by src length
- Support sort by length of a source text when one contains another.
- It prioritizes a longer match to be shown in tooltips
- Solve BUGS#1239
- Introduce a new preference GLOSSARY_SORT_BY_SRC_LENGTH
- Configurable on glossary pane configuration button
- Configurable on preference dialog
* style: GlossarySearcher class
* docs: update manual
- Describe glossary preference options about sorting
* style: update
* feat: term in glossary context menu
add source term in tooltip of target term on glossary context menu
* fix: Enable source term length sorter in default
---------
Bugs: https://sourceforge.net/p/omegat/bugs/1239/ …
> [6.0][BUGS#1239] feat: glossary support optional sort by src length

- test/src/org/omegat/core/statistics/CalcMatchStatisticsTest.java
- Bug fix of test
N.A.
- Check result is not null. It can be null when the execution thread is intercepted.
> fix(test): avoid NPE when aborting long running thread

- test/src/org/omegat/filters/TestFilterBase.java
- test/src/org/omegat/languagetools/LanguageToolTest.java
There are some test case that requires network reachability and TCP port availability on OS.
These tests are failed when some network issue exists.
This is the improvement of test case to be robust against network connectivity.
test improvement
N.A.
- Select TCP port which is not used for LanguageTool Server test case
- Configure JAXB parser not to download DTD and validate in XML test case.
> improve test robustness against network reachability

- spellchecker/morfologik/src/main/java/org/omegat/spellchecker/morfologik/MorfologikSpellchecker.java
- src/org/omegat/languagetools/LanguageManager.java
- Speller: morfologik: LT bundled dictionary not found in Dutch
- https://sourceforge.net/p/omegat/bugs/1271/
- Looking for `spelling/` folder in addition to `hunspell/` in resources
-
-
> fix: spell: look for LT bundle spelling/ folder

- src/org/omegat/gui/preferences/view/CustomColorSelectionController.java
- Preferences/CutomColorSelector don't show notification immediately when modifying color  
- https://sourceforge.net/p/omegat/bugs/1273/
- check the change when the selection changed
This can be backported to releases/6.0 branch
> fix: o.o.g.p.v.CustomColor setRestartRequired when selection changed

- src/org/omegat/util/OStrings.java
- test/fixtures/org/omegat/util/LocaleRule.java
- Add LocaleRule fixture to support test on specified locale
-
-
> chore/test: add LocaleRule fixture

- build.gradle
- gradle/libs.versions.toml
- src/org/omegat/Main.java
- src/org/omegat/gui/theme/DefaultClassicTheme.java
- src/org/omegat/gui/theme/DefaultFlatTheme.java
- src/org/omegat/gui/theme/DelegatingLookAndFeel.java
- theme/src/main/java/org/omegat/gui/theme/DefaultFlatDarkTheme.java
- theme/src/main/java/org/omegat/gui/theme/DefaultFlatLightTheme.java
Java runtime only supports 11 languages for standard dialogs such as Open, Save, and Color Chooser.
This uses swing-extra-locales library to enhance these dialogs with translations in Russian, Ukrainian, Arabic and Catalan.
- Localize UI for genuine dialogs in various languages
- https://sourceforge.net/p/omegat/feature-requests/1763/
- Add dependency `swing-extra-locales` and initialize the library
> [RFE#1763] feat: localize dialogs for extra locales

- config/checkstyle/suppressions.xml
- src/org/omegat/core/matching/NearString.java
- src/org/omegat/core/statistics/FindMatches.java
- test/src/org/omegat/core/statistics/CalcMatchStatisticsTest.java
- test/src/org/omegat/gui/editor/mark/ComesFromMTMarkerTest.java
- test/src/org/omegat/gui/matches/MatchesVarExpansionTest.java
FindMatches class has been introduced in 2013 and there are several place to improve coding styles.
- refactoring
- Update javadoc contents
- style: remove final from arguments
- revert haveChanceToAdd logic to noChanceToAdd because all conditions are negated
- Replace inline ` new DefaultTranslationsIterator()` and `new MultiTranslationsIterator()` to lambda expression
- Add  NearString and FindMatches ctors with small number of arguments, with PrepareTMXEntries and NearString.Scores data classes.
> refactor: FindMatches to split looong method into multiple private method, use lambda, and relax suppression of checkstyle

- aligner/src/main/java/org/omegat/gui/align/Aligner.java
- config/checkstyle/suppressions.xml
- src/org/omegat/core/data/ExternalTMFactory.java
- src/org/omegat/core/data/ParseEntry.java
- src/org/omegat/filters2/IParseCallback.java
- src/org/omegat/filters2/text/ilias/ILIASFilter.java
- src/org/omegat/filters2/text/magento/MagentoFilter.java
- test/src/org/omegat/core/data/TmxComplianceBase.java
- test/src/org/omegat/core/statistics/CalcMatchStatisticsTest.java
- test/src/org/omegat/filters/TestFilterBase.java
- test/src/org/omegat/filters2/master/FilterMasterTest.java
Use default for old addEntry method signature to reduce code duplications.
refactor
- Update IParseCallback#addEntry to be default
- Remove overrides of it
- Update ILIASFilter and MagentoFilter to use new one
> refactor: simplify IParseCallback#addEntry

- src/org/omegat/Bundle.properties
- src/org/omegat/gui/preferences/view/LanguageToolConfigurationController.java
- src/org/omegat/gui/preferences/view/LanguageToolConfigurationPanel.form
- src/org/omegat/gui/preferences/view/LanguageToolConfigurationPanel.java
- src/org/omegat/languagetools/LanguageToolNetworkBridge.java
- src/org/omegat/languagetools/LanguageToolPrefs.java
- src/org/omegat/languagetools/LanguageToolWrapper.java
- src/org/omegat/util/Preferences.java
- src/org/omegat/util/StaticUtils.java
A code to launch local LanguageTool server from OmegaT has not been maintained in many years.
This improves handling of local LanguageTool server launcher, to add necessary arguments, catch connection error.
Also allow specifying ngram files for LT server.
- Support ngrams for local LT server jar launcher
- https://sourceforge.net/p/omegat/feature-requests/1764/
- Update Preferences > LanguageTool > Local Server Jar to accept folder path that have language model files 
- Catch HTTP connection error and handling the error properly, instead of dumping stacks
- Put heap memory option to java
- Put `--public` to LT server
- Put `--allow-origin`  to LT server (Handle CORS)
- Automatically select an unused port instead of default 8081 only
- Default …
> Feat: Improve supporting LanguageTool local server

- config/checkstyle/suppressions.xml
- src/org/omegat/core/data/ExternalTMFactory.java
- src/org/omegat/core/data/ProjectTMX.java
- src/org/omegat/core/statistics/CalcMatchStatistics.java
- src/org/omegat/core/statistics/FindMatches.java
- test/data/tmx/test-match-stat-en-ca.tmx
- test/src/org/omegat/core/segmentation/SegmenterTest.java
- test/src/org/omegat/core/statistics/CalcMatchStatisticsTest.java
- test/src/org/omegat/core/statistics/FindMatchesTest.java
`FindMatches` class ctor has a argument of boolean `allowSeparateSegmentMatch`.
This PR add a test case with the option and test the chunk of the feature. 
Improve test coverage, Quality Assurance 
- ProjectTMX: change a scope of `defaults` and `alternatives` fields as `protected` for mocking
- ProjectTMXTest: update `TestProject` internal class
- ProjectTMXTest: add the case `testSegmented`
- `calcMatchStatisticsTest` to handle `Segmenter` and `TestProject`
- update `SegmenterTest` 
- refactor `FindMatches`, `CalcMatchStatistics`, `ExternalTMFactory`, and `ProjectTMX`.
- #963 
- #1174
> Add FindMatches class test with segmented

- aligner/src/main/java/org/omegat/gui/align/AlignPanel.form
- aligner/src/main/java/org/omegat/gui/align/AlignPanel.java
- test-acceptance/src/org/omegat/gui/align/AlignerWindowTest.java
-  aligner average distance can be {0} which expected a numeric value
- https://sourceforge.net/p/omegat/bugs/1275/
- Fix the label initializer
- update expectation of acceptance test
> fix: aligner: fix initialize average distance label

- aligner/src/main/java/org/omegat/gui/align/AlignFilePickerController.java
- aligner/src/main/java/org/omegat/gui/align/AlignPanelController.java
- aligner/src/main/java/org/omegat/gui/align/Aligner.java
- aligner/src/main/java/org/omegat/gui/align/AlignerModule.java
- test-acceptance/src/org/omegat/gui/align/AlignerWindowTest.java
The Aligner depends on the Core configuration of segmentation and the filters.
It is not good to access Core API throughout the code, but it can be taken in ctor once.
refactor
- Add a constructor to take the segmenter as an argument for testing.
- Logger is instantiated with Bundle.
- Rewrite action listeners with lambdas.
- Aligner class holds its own the segmenter and the filter master objects.
> refactor: reduce Core dependency for aligner

- gradle/libs.versions.toml
- Support for p2 cache directory in an Eclipse step
- Bump Gradle plugin spotless@7.0.0.BETA4 from 6.25.0
- It supports Eclipse p2 cache in maven local folder
- Reduce network connectivity error in CI check
> chore: bump spotless gradle plugin@7.0.0.BETA4

- test-acceptance/src/org/omegat/gui/align/AlignerWindowTest.java
A test case for aligner GUI test is flows.
Fix unstable test expectation
- put timeout for waiting file chooser
> fix: testAcceptance: aligner test expectation unstable

- build.gradle
- fix an issue that finalizer does not run when test failed
- kill xvfb process with FinalizedBy task
> chore: testAcceptance finalizer always run

- src/org/omegat/gui/main/BaseMainWindowMenu.java
refactor and improvement for GUI acceptance test implementation
- Defines names for all JMenu component
- Implement BaseMainWindowMenu#getMenu without the map
> refactor: BaseMainWindowMenu#createMenu to accept component name

- src/org/omegat/core/team2/impl/GITCredentialsProvider.java
- src/org/omegat/core/team2/impl/SVNAuthenticationManager.java
- test-integration/docker/client/Dockerfile
- test-integration/src/org/omegat/core/data/TestTeamIntegration.java
- test-integration/src/org/omegat/core/data/TestTeamIntegrationChild.java
- test/fixtures/org/omegat/core/TestCoreInitializer.java
When changing a way to detect gui environment, the integration test failed to launch.
This PR is to fix the issue.
- Fix the weekly release
- Improve integration test code to debug child process error
- inherit ConsoleWindow to implement TestIntegrationChild.mainWindow 
- TestIntegration: set `ProcessBuilder.redirectErrorStream(true)`
- Bump target JDK to 17
related #1133
> chore: fix error on Integration Test

- src/org/omegat/gui/main/DockableScrollPane.java
- src/org/omegat/gui/matches/MatchesTextArea.java
- test-acceptance/data/project/omegat/last_entry.properties
- test-acceptance/data/project/omegat/project_save.tmx
- test-acceptance/src/org/omegat/gui/align/AlignerWindowTest.java
- test-acceptance/src/org/omegat/gui/main/TestCoreGUI.java
- test-acceptance/src/org/omegat/gui/matches/MatchesTextAreaTest.java
- Split PR #963 
- Add acceptance of Fuzzy matches pane.
- Title
* URL
-
-
-
> feat: Add acceptance test of Fuzzy matches pane

- src/org/omegat/core/statistics/FindMatches.java
During a subsegment search, if some of the subsegments have a penalty, the global segment receives as penalty the highest value
https://sourceforge.net/p/omegat/bugs/1251/
> Apply max penalty for sub-segment match

- src/org/omegat/core/statistics/CalcMatchStatistics.java
- src/org/omegat/core/statistics/FindMatches.java
- src/org/omegat/gui/matches/FindMatchesThread.java
- test/data/tmx/penalty-010/segment_1.tmx
- test/data/tmx/test-multiple-entries.tmx
- test/src/org/omegat/core/statistics/CalcMatchStatisticsTest.java
- test/src/org/omegat/core/statistics/FindMatchesTest.java
- test/src/org/omegat/gui/matches/FindMatchesThreadTest.java
split #963
refactoring
- BUGS#1251
- Add regression test of BUGS#1251
- Refactor FindMatches class
- Ignore the regression test
> refactor: FindMatches class

- src/org/omegat/core/matching/NearString.java
- src/org/omegat/core/statistics/FindMatches.java
- test/data/tmx/segment_2.tmx
- test/src/org/omegat/core/statistics/FindMatchesTest.java
- test/src/org/omegat/gui/matches/FindMatchesThreadTest.java
PR #1223 respect a penalty value of an external TM, but ignore a penalty of foreign language match
- BUGS#1251
- Extent Scores class to hold penalty
- Calculate `maxPenalty` with `Scores.penalty`
- Enable Unit tests
> fix: respect foreign match penalty in segmented matches

- build.gradle
- languagetool-server depends on lt-core that has a dependency for the hunspell.
- OmegaT explicitly depends on dumont hunspell 2.1.2 but LT 6.1 depends on 2.1.1
> chore: hunspell dependency for test

- build.gradle
- docs_devel/docs/93.BuildingInstallerPackage.md
In recent days, there are several new PCs introduced with qualcomm snapdragon X Elite ARM64 CPU and Windows 11 as CoPilot+PC branding.
It is great if we can publish OmegaT with aarch64 JRE.
- Support Windows 11 and Linux on ARM64 for development environment
- https://sourceforge.net/p/omegat/feature-requests/1773/
- Remove tool chain definition
- Specify the source and target compatibility with Java 11
- Add Windows_aarch64 distribution package
> chore: support package build on windows 11 on aarch64

- build.gradle
- release/changes.txt
- test/data/plugin/bundled/MANIFEST.MF
Current junixsocket is too old and block OmegaT 6.0 macOS notarization.
https://sourceforge.net/p/omegat/bugs/1283/
This fix upgrades the library to its latest version and allows 6.0 macOS notarization.
> move junixsocket to 2.10.1 for macOS notarization

- build.gradle
When building OmegaT from source on Linux ARM64 platform, it failed to run `launch4j`.
The `launch4j` somehow dead project, so I maintain the forked version of the `launch4j` and the topic branch here use the forked version of it. Because `gradle-launch4j` has a bug which configuration syntax `launch4jBin` does not support multi-platform project, I detect os and arch then conditional configuration is used.
- Build and release changes 
-    Support Windows 11 and Linux on ARM64 for development environment
-    https://sourceforge.net/p/omegat/feature-requests/1773/
- detect os and architecture
- use forked version of launch4j
> chore: use custom launch4j binaries

- src/org/omegat/filters2/hhc/HHCFilter2.java
- src/org/omegat/filters2/hhc/HHCFilterVisitor.java
- src/org/omegat/filters2/html2/FilterVisitor.java
- src/org/omegat/filters2/html2/HTMLFilter2.java
refactoring
- Filters components must respect filter context but FilterVisitor class does not.
> fix: passing filter context

- build.gradle
- src/org/omegat/Bundle.properties
- src/org/omegat/help/Help.java
- src/org/omegat/util/StaticUtils.java
- allow users to make bookmark in the browser
- https://sourceforge.net/p/omegat/feature-requests/1778/
- expand manual in the application data directory to allow users to keep bookmark on the browser
- related https://sourceforge.net/p/omegat/mailman/message/59152285/
- Expand HTML manual under `~/Library/Application Support/OmegaT/manual/<version>/<lang>/` instead of temporary folder on macos. `%USERPROFILE%\\AppData\\Local\OmegaT` on Windows and `~/.local/share/OmegaT/` on Linux.
> feat: expand manual in the application data directory to allow users to keep bookmark on the browser

- gradle.properties
- src_docs/greeting/ca/First_Steps.xml
- src_docs/greeting/co/First_Steps.xml
- src_docs/greeting/de/First_Steps.xml
- src_docs/greeting/en/First_Steps.xml
- src_docs/greeting/fr/First_Steps.xml
- src_docs/greeting/ia/First_Steps.xml
- src_docs/greeting/it/First_Steps.xml
- src_docs/greeting/ja/First_Steps.xml
- src_docs/greeting/nl/First_Steps.xml
- src_docs/greeting/pt_BR/First_Steps.xml
- src_docs/greeting/zh_CN/First_Steps.xml
Changed Doctype from 'book' to 'article' for all existing First_Steps translation files. Added new translations for Corsican, Interlingua, Portuguese (Brazil), and Chinese (Simplified). Updated gradle.properties to reflect the new languages.
- Adding First Steps sources from L10N projects
> Update First_Steps translations and restore some languages

- ci/azure-pipelines/publish_release.yml
- ci/azure-pipelines/publish_weekly.yml
Replaced SCP with lftp for file uploads to SourceForge, enabling more robust and secure file transfer operations. This is a backport from master branch.
-
-
-
> [6.0]chore: Update upload pipelines to use secure SSH and lftp for transfers

- src/org/omegat/Bundle.properties
- src/org/omegat/externalfinder/item/ExternalFinderItem.java
- ExternalFinder construct bundle key from enum name. This is to avoid a dynamic key and use enum ctor to define value.
- Add javadoc for enum entries
refactor
-
-
-
> refactor: define enum value by getString and avoid dynamic key for bundle lookup

- aligner/src/main/java/org/omegat/gui/align/AlignFilePickerController.java
- aligner/src/main/java/org/omegat/gui/align/AlignPanelController.java
This change removes `Aligner` as a field in `AlignPanelController` and refactors related methods to accept it as a parameter instead. This improves encapsulation by limiting the scope of the `Aligner` object to where it is needed. It simplifies the controller's responsibilities, making it cleaner and less coupled.
refactoring to fix spotbugs error
- Fix Spotbugs error EI
- https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#ei-may-expose-internal-representation-by-returning-reference-to-mutable-object-ei-expose-rep
-
- Parnt #1296
> Refactor `AlignPanelController` to take `Aligner` as a method parameter

- src/org/omegat/core/team2/gui/RepositoriesCredentialsPanel.form
- src/org/omegat/core/team2/gui/RepositoriesCredentialsPanel.java
refactor
-
```
M B PA_PUBLIC_PRIMITIVE_ATTRIBUTE PA: Primitive field 
org.omegat.core.team2.gui.RepositoriesCredentialsPanel.btnRemove is public and set from inside the class, which makes it too exposed. Consider making it private to limit external accessibility. At RepositoriesCredentialsPanel.java:[line 55]	
M B PA_PUBLIC_PRIMITIVE_ATTRIBUTE PA: Primitive field org.omegat.core.team2.gui.RepositoriesCredentialsPanel.filler1 is public and set from inside the class, which makes it too exposed. Consider making it private to limit external accessibility. At RepositoriesCredentialsPanel.java:[line 56]	
M B PA_PUBLIC_PRIMITIVE_ATTRIBUTE PA: Primitive field …
```
> refactor: adjust spotbugs warnings on RepositoriesCredentialsPanel GUI parts visibility

- src/org/omegat/gui/dialogs/RepositoriesMappingDialog.form
- src/org/omegat/gui/dialogs/RepositoriesMappingDialog.java
refactor
-
- fix the following SpotBugs Errors.
```
M B PA_PUBLIC_PRIMITIVE_ATTRIBUTE PA: Primitive field org.omegat.gui.dialogs.RepositoriesMappingDialog.btnMappingAdd is public and set from inside the class, which makes it too exposed. Consider making it private to limit external accessibility. At RepositoriesMappingDialog.java:[line 71]	
M B PA_PUBLIC_PRIMITIVE_ATTRIBUTE PA: Primitive field org.omegat.gui.dialogs.RepositoriesMappingDialog.btnMappingRemove is public and set from inside the class, which makes it too exposed. Consider making it private to limit external accessibility. At RepositoriesMappingDialog.java:[line 70]	
M B PA_PUBLIC_PRIMITIVE_ATTRIBUTE PA: Primitive field org.omegat.gui.dialogs.RepositoriesMappingDialog.btnRepoAdd is public and set from …
```
> refactor: adjust spotbugs warnings on RepositoriesMappingDialog GUI parts visibility

- aligner/src/main/java/org/omegat/gui/align/AlignFilePicker.form
- aligner/src/main/java/org/omegat/gui/align/AlignFilePicker.java
- aligner/src/main/java/org/omegat/gui/align/AlignMenuFrame.form
- aligner/src/main/java/org/omegat/gui/align/AlignMenuFrame.java
- aligner/src/main/java/org/omegat/gui/align/AlignPanel.form
- aligner/src/main/java/org/omegat/gui/align/AlignPanel.java
- aligner/src/main/java/org/omegat/gui/align/EditingPanel.form
- aligner/src/main/java/org/omegat/gui/align/EditingPanel.java
Refactor GUI components across multiple files to limit access modifiers, removing unnecessary `public` modifiers. This improves encapsulation and aligns with Java best practices.
refactor
- GUI parts are defined as public but it should be package-private
-
-
parent PR #1296
> refactor(aligner): Remove public modifier from GUI variable declarations

- src/org/omegat/core/spellchecker/AbstractSpellChecker.java
Add a safeguard to prevent potential NullPointerException in the saveWordLists method by ensuring file paths are not null before proceeding. This ensures stability when saving ignored and learned words.
Please mark the GitHub LABEL of the change your PR introduces:
- Spellchecker raised NPE when writing word list file
- https://sourceforge.net/p/omegat/bugs/1288/
- Null check for the ignore words file and the learned file path on the saveWordLists method
> Fix: null check in saveWordLists method of SpellChecker

- src/org/omegat/Bundle.properties
- src/org/omegat/gui/editor/Document3.java
- src/org/omegat/gui/editor/EditorTextArea3.java
NPE is reported when using OmegaT 6.1 weekly when RTL languages.
- 
- Uncaught exception in weekly build (2025-01-18) 
- https://sourceforge.net/p/omegat/bugs/1280/
- Dev-ML thread
https://sourceforge.net/p/omegat/mailman/omegat-development/thread/bc__wDAb_8HhKI8874uzACXxlNkr1AsqREJeuM1f7MRE6sbjXIHjLerxgavXTTEOUFbSSBf3mn7Dxybdx9uqCx4Q-LWCvrd1xSvAlyN-M0c%3D%40northside.tokyo/#msg59161278
- Check nullity of the return value of EditorArea3#getOmDocument
- Improve javadoc 
- Improve error log
> fix: EditrorArea3:  avoid NPE when detecting a carret position

- src/org/omegat/gui/glossary/GlossaryTextArea.java
- test/src/org/omegat/gui/main/MainWindowMenuTest.java
Fix the bug reported.
- Refactoring
- 
- Mismatch in method name causes exception when selecting "Open Writable Glossary File"
- https://sourceforge.net/p/omegat/bugs/1290/
- Refactored action listeners: Converted anonymous inner classes for event listeners into lambda expressions for better readability.
- Renamed variables: Updated variable names (mouseListener to myMouseListener, etc.) to align with naming conventions.
- Replaced non-transient with transient fields: Made certain fields transient, ensuring compatibility with serialization.
- Enhanced test cases: Added a new test to verify menu action methods and their existence, improving test coverage.
- Code modernization: Applied modern Java syntax, such as diamond operators (<>) and utility classes.
> fix: GlossaryTextArea listener invoking menu handler and test menu action mapping for invokeAction call

- test/src/org/omegat/gui/glossary/GlossarySearcherTest.java
Entend unit and functional test coverage for GlossarySearcher class.
Unit and functional tests
- Extend GlossarySearcherTest
> Add tests for glossary searches with tags and CJK cases

- test-acceptance/src/org/omegat/gui/matches/MatchesTextAreaTest.java
refactor
There is no issue to point.
- When running acceptance test, it does not open the sample project directory, but copy project files into temporary directory and open.
- The test changes the files to be opened. It cause second test become failure.
> fix: acceptance-test: 'MatchesTextAreaTest' to prepare temporary project directory

- src/org/omegat/Main.java
- refactor
- Adjust for the following SpotBugs warnings.
```
M V MS_MUTABLE_COLLECTION_PKGPROTECT MS: org.omegat.Main.PARAMS is a mutable collection which should be package protected At Main.java:[line 136]	
M V MS_PKGPROTECT MS: org.omegat.Main.projectLocation should be package protected At Main.java:[line 130]	
M V MS_PKGPROTECT MS: org.omegat.Main.remoteProject should be package protected At Main.java:[line 133]	
M V MS_PKGPROTECT MS: org.omegat.Main.runMode should be package protected At Main.java:[line 139]	
M D NP_NULL_ON_SOME_PATH_FROM_RETURN_VALUE NP: Possible null pointer dereference in org.omegat.Main.restartGUI(String) due to return value of called method Dereferenced at Main.java:[line …
```
> Refactor: Main class to adjust visibility of fields

- machinetranslators/google/src/main/java/org/omegat/machinetranslators/google/Google2Translate.java
Removed nested static classes and replaced the response parsing logic with JsonNode for improved flexibility and reduced complexity. Updated translation extraction to handle null checks more effectively and ensure robust error handling.
refactor
- Fix the following SpotBugs errors
```
M V EI_EXPOSE_REP EI: org.omegat.machinetranslators.google.Google2Translate$Data.getTranslations() may expose internal representation by returning Google2Translate$Data.translations At Google2Translate.java:[line 306]	
M V EI_EXPOSE_REP2 EI2: org.omegat.machinetranslators.google.Google2Translate$Data.setTranslations(List) may expose internal representation by storing an externally mutable object into Google2Translate$Data.translations At Google2Translate.java:[line 310]	
M V …
```
> Refactor Google Translate response handling to use JsonNode.

- src/org/omegat/core/KnownException.java
- test/src/org/omegat/core/KnownExceptionTest.java
This change make getparams method of KnownException class returns copy of a array of object. It reduces the risk of exposing internal fields.
refactor
- Added a @Nullable annotation for better null-safety awareness.
- Modified the getParams() method to return a copy of the params array for immutability and preventing potential side effects.
- Introduced additional imports to support the changes (e.g., Arrays and Nullable).
#1296
> refactor: adjust custom exception class not to expose internal object

- src/org/omegat/gui/properties/SegmentPropertiesArea.java
- Sometimes called `SegmentProperties.onEntryActivated` after closed a project
- https://sourceforge.net/p/omegat/bugs/1291/
- Check project is loaded in the event handler
- Refactoring the event handler as internal class
- Reduce complexity of the setProperties method
> Fix: BUGS#1291: Sometimes called SegmentProperties.onEntryActivated after closed a project

- src/org/omegat/Main.java
The logic for checking if the restart binary exists was inverted, causing the application to proceed incorrectly. This update corrects the condition to ensure proper handling when the binary is missing, preventing erroneous behavior during restart. This logic failure introduced in PR#1308 refactoring
-
-
-
> Fix incorrect file existence check for restart logic

- src/org/omegat/core/Core.java
Refactor access modifiers for `editor`, `saveThread`, and `glossary` from `protected` to package-private. This simplifies access control and aligns with typical encapsulation practices within the package. No functional changes were introduced.
refactor - adjust for spotbugss warnings
-This Pull Request modifies the access modifiers of several class fields in the Core.java file, changing them from protected to default (package-private) scope.
- Access modifiers for editor, saveThread, and glossary were updated from protected to default (package-private).
- No additional changes like new logic or features were introduced in the code. It is purely a refactoring of access levels.
- There is only one …
> refactor(Core): Make editor, saveThread, and glossary package-private

- src/org/omegat/gui/filelist/ProjectFilesList.form
- src/org/omegat/gui/filelist/ProjectFilesList.java
- src/org/omegat/gui/filelist/ProjectFilesListController.java
- src/org/omegat/util/gui/DataTableStyling.java
The Pull Request (PR) involves the enhancement of code readability and refinement of data handling by modifying field access levels, optimizing syntax, and introducing auxiliary values in the GUI .form setup.
Main changes:
- Field Access Levels Updated: Changes were made in ProjectFilesList.java to modify field access levels (e.g., public to private) for better encapsulation and object-oriented design practices.
- Sorting Logic Simplified and Optimized: Adjustments in ProjectFilesListController.java include replacing verbose sorting logic with more concise methods like Integer.compare.
- Removal of Redundant Imports: Refactored unnecessary imports to streamline dependencies in the code.
GUI .form Updates: Added AuxValues elements to the ProjectFilesList.form file, likely for additional …
> Refactor: reduce visibility of fields and optimize sorting logic.

- ci/azure-pipelines/build_steps.yml
Updated the JRE download links in the Azure Pipelines configuration to point to version 17.0.14+7 instead of 17.0.11+9. This ensures that the pipeline uses the latest JRE bundles for all supported platforms.
-
-
-
> chore: Update JRE URLs to use version 17.0.14+7

- src/org/omegat/gui/preferences/view/TMMatchesPreferencesController.java
- Reviewer comment in PR#963 about PR#1217
https://github.com/omegat-org/omegat/pull/963#issuecomment-2833433548
- - Fix the issue feedback given by the reviewer after merging approved PR#1217.
- Added reset and persistence logic for the paragraph match toggle related to segmented TMX.
- Ensures consistent behavior by setting a default value during initialization and saving the user preference when changes are made.
> fix: Set default and persist preferences for paragraph match from segmented tmx toggle

- test/src/org/omegat/gui/main/MainWindowMenuTest.java
- Backport the check for BUGS#1290
- OmegaT 6.0.x does not have the same issue.
- The bug is not detected in master branch because there is missing the test, so backport the test case.
- Added testMenuActions_invokeActions test method to validate that all menu actions in the source match defined methods in MainWindowMenuHandler.
- Introduced processSourceContent utility method for processing .java files in the /src directory.
- Improved code readability by:
-  Replacing generic type declarations with the diamond operator (<>).
- Reformatting assertions for better clarity.
> [6.0] chore: check for the existence of the menu invocation action method

- src/org/omegat/core/segmentation/SRX.java
- test/src/org/omegat/core/segmentation/SRXTest.java
SRX.loadConfigFile: If we fail to read the file, throw the exception instead of silently ignore it In unit tests, that can show whenever we break compatiblityhat is normal. 
- 
None, it is done to make resolution of CVE-2024-51366 better
> Do not eat exception in loadConfFile

- src_docs/developer/90.ReleaseProcedure.md
- src_docs/developer/92.CodeSigning.md
- src_docs/developer/93.BuildingInstallerPackage.md
This is a development guide update regarding macOS notarization, which is compulsory now to run on the latest version of macOS (15 at the date of this PR).
https://sourceforge.net/p/omegat/feature-requests/1704/
It updates the macOS notarization documentation but also includes warning that refer to seemingly non working tasks to be investigated.
> update macOS signed/notarized builds information

- build.gradle
- lib/licenses/Licenses.txt
Backport PR #290
- Java 17 compatibility
-    https://sourceforge.net/p/omegat/feature-requests/1525/
- Added org.openjdk.nashorn:nashorn-core:15.4 as a new JavaScript engine dependency in build.gradle.
- Updated Licenses.txt to include the licensing information for the newly added Nashorn JavaScript engine.
> [6.0][java17] Add nashorn javascript engine

- src/org/omegat/Bundle.properties
- src/org/omegat/core/team2/IRemoteRepository2.java
- src/org/omegat/core/team2/impl/HTTPRemoteRepository.java
- test/src/org/omegat/core/team2/impl/HTTPRemoteRepositoryTest.java
- When mapping contents not exist, the error message does not provide enough information.
- https://sourceforge.net/p/omegat/bugs/1295/
- Improve error handling of http remote repository access.
- use NetworkException instead of generic RuntimeException
> fix: Enhance error handling for HTTP response exceptions

- test/src/org/omegat/core/segmentation/SRXTest.java
When testing SRX migration, ensure the full migration runs in the temporary directory (else it may delete file from repository)
Bug
> fix: SRXTest: Copy file in temp dir first, so that the full test runs in the temp dir

- src/org/omegat/Bundle.properties
- src/org/omegat/core/data/ProjectProperties.java
- src/org/omegat/gui/main/ProjectUICommands.java
Removed the "throws Exception" declaration from the constructor to simplify its signature. Added a try-catch block to gracefully handle potential IOException during `loadProjectFilters()` and ensure `projectFilters` is properly initialized.
refactoring to fix spotbugs error
- Ctor should not throw exception for a security reason.
- Bug description: https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#ct-be-wary-of-letting-constructors-throw-exceptions-ct-constructor-throw
-
-
> CT: Be wary of letting constructors throw exceptions. (CT_CONSTRUCTOR_THROW)[](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#ct-be-wary-of-letting-constructors-throw-exceptions-ct-constructor-throw)
> 
> Classes that throw exceptions in their constructors are …
> Remove unnecessary exception and handle filter loading errors

- src/org/omegat/gui/dictionaries/DictionariesTextArea.java
- src/org/omegat/gui/glossary/GlossaryTextArea.java
- src/org/omegat/gui/matches/MatchesTextArea.java
- test-acceptance/data/project/glossary/glossary.txt
- test-acceptance/src/org/omegat/gui/editor/EditorUtilsGUITest.java
- test-acceptance/src/org/omegat/gui/glossary/GlossaryTextTest.java
- test-acceptance/src/org/omegat/gui/main/TestCoreGUI.java
- test-acceptance/src/org/omegat/gui/matches/MatchesTextAreaTest.java
- test-acceptance/src/org/omegat/gui/matches/MatchesTextTest.java
This Pull Request enhances state tracking functionality across several components, adds property change notifications, and introduces modifications to improve test coverage and consistency.
- refacto ring
- Update TestCoreGUI to wait a finish of the search thread and update of the match pane
- Added property change notifications for state changes (displayWords, entries, matches, activeMatch) in various text area classes.
- Introduced local copies of variables to track old state before updates.
- Simplified the initialization of generic types in MatchesTextArea.java.
- Amended and extended acceptance tests for project handling and fuzzy match functionality.
> feat(acceptance-test): wait search/matches panes ready and updated

- src/org/omegat/core/team2/impl/HTTPRemoteRepository.java
- test/src/org/omegat/core/team2/impl/HTTPRemoteRepositoryTest.java
Fix the issue I entered in last change for HTTPRemoteRepository class.
- Fix the handling of 304 http response:
- Consolidated HTTP error response handling into the main method instead of a separate function.
- Just return when 304 HTTP response from the main method.
- Simplification of logging and exception mechanisms:
- Refactored logging for better readability and debugging support.
- Improved consistency in method formatting and indentation.
- Improve error handling
- Added a check for directory creation failure with an appropriate exception. 
- Enhancements in unit tests (HTTPRemoteRepositoryTest):
- Added test cases to verify retrieve handling of "304 Not Modified" responses.
- Modified existing test cases to improve structuring and …
> fix: team/HTTPRemoteRepository: handle HTTP_NOT_MODIFIED response correctly

- src/org/omegat/util/StringUtil.java
- test/src/org/omegat/util/StringUtilTest.java
This Pull Request makes improvements to the StringUtil class by enhancing code readability, modularity, and functionality for normalizing character widths. It also includes a minor test case update in StringUtilTest.
- Javadoc
- Refactor
- Added a since parameter to the @Deprecated annotation for specifying the version of deprecation.
- Improved the documentation for the normalizeWidth method by clarifying its functionality and adding detailed explanations.
- Refactored the normalizeWidth method to extract specific functionality into new dedicated methods (processAsciiAndSpace, processHangul).
- Fixed a typo in variable and method names (HUNGLE to HANGUL) for consistency and …
> fix: correct typo and refactor normalizeWidth processing logic

- config/checkstyle/suppressions.xml
- src/org/omegat/core/search/SearchResultEntry.java
- src/org/omegat/core/search/Searcher.java
- Replaced variables prefixed with "m_" with descriptive camelCase names.
- Improved code readability and alignment with modern Java conventions.
- Refactor
- Refactoring SearchResultEntry:
- Renames member variables, removing prefixes (m_) for improved readability.
- Updates all class methods and references to align with the new variable names.
- Implements a Builder pattern for constructing SearchResultEntry objects, enhancing flexibility and clarity.
- Refactoring Searcher:
- Renames variables, similarly removing prefixes (m_) for consistency.
- Simplifies internal methods by reducing redundancy in how entries are added and matched against search criteria.
- No significant new functionality or bug fixes were introduced; changes focus solely on refactoring.
- …
> refactor(core): remove Hungarian notation from field names in `Searcher` and `SearchResultEntry` class

- src/org/omegat/help/Help.java
When using the online help, the master build points at "omegat-latest" on sourceforge.
The "latest" suffix is not used anymore and instead of pointing at a recent "weekly" build, it points at obsolete data.
This is a temporary fix until we implement a "weekly" or "dev" suffix for the online documentation system.
> the 'latest' suffix is not used anymore

- src/org/omegat/filters3/xml/XMLReader.java
This Pull Request fix the reference to the uninitialized field `encoding` in constructor.
- Bug fix
> fix(filters3): avoid uninitialized read of field `encoding` in XMLReader

- build-logic/src/main/groovy/org.omegat.verification-conventions.gradle
- src/org/omegat/gui/dialogs/ProjectPropertiesDialog.java
- src/org/omegat/gui/dialogs/ProjectPropertiesDialogController.java
- src/org/omegat/gui/main/BaseMainWindowMenu.java
- src/org/omegat/gui/main/ProjectUICommands.java
- test-acceptance/src/org/omegat/gui/align/AlignerWindowTest.java
- test-acceptance/src/org/omegat/gui/dialogs/ProjectPropertiesDialogTest.java
- test-acceptance/src/org/omegat/gui/main/TestMainWindowMenuHandler.java
Add acceptance test for Project Properties dialog.
During work, I found small bug that the component name is wrong, that is a testing purpose.
refactor
- Logical and Functional Improvements:
- Refactored directory and file handling to improve robustness in ProjectPropertiesDialogController.
- Adjusted the code to streamline project property editing (e.g., reusing application frame variables).
- Build Configuration: 
- Added jacocoAcceptanceReport and jacocoIntegrationReport tasks for code coverage reporting.
- UI Updates:
-  Updated GUI components in the ProjectPropertiesDialog and added identifiers for …
> test(acceptance): Project Properties dialog handling

- src/org/omegat/core/team2/impl/GITRemoteRepository2.java
Fix the spotbugs warning of WMI_WRONG_MAP_ITERATOR: Inefficient use of keySet iterator instead of entrySet iterator
refactoring
-
-
-
> refactor(git): replace keySet iteration with entrySet in `GITRemoteRepository2`

- src/org/omegat/gui/dialogs/ProjectPropertiesDialog.java
UI improvements
- add padding between UI elements to improve readability
- move post-processing commands to a separate group box
- make 'File locations' less confusing - move browse buttons on the same line with their associated input fields
Current dialog:
New dialog:
> UI: Rearrange "Project Properties" dialog

- src/org/omegat/gui/editor/ModificationInfoManager.java
This Pull Request refactors the ModificationInfoManager class to improve code readability and organization. It moves date and time formatting logic into the ModificationInfoVarExpansion class and renames several variables for clarity.
- refactor
- Moved date and time formatting logic from static initialization in ModificationInfoManager to the constructor of the ModificationInfoVarExpansion class.
- Renamed several variables for improved clarity (DATE_FORMAT becomes dateFormat, defaultTemplate becomes DEFAULT_TEMPLATE_VAR_EXPANSION, etc.).
- Consolidated related logic into ModificationInfoVarExpansion to reduce scattered responsibilities in the code.
- Improved encapsulation by associating locale-sensitive operations directly with ModificationInfoVarExpansion …
> refactor(gui): move date and time format initialization to `ModificationInfoVarExpansion` constructor

- src/org/omegat/filters3/xml/XMLFilter.java
- src/org/omegat/filters3/xml/XMLReader.java
This Pull Request refactors parts of the XML handling code in two files by improving type safety, streamlining encoding handling, and fixing method logic. Additionally, it introduces a clear and structured approach to detect end-of-line (EOL) characters.
- refactor
- Removed unused exception handling: UnsupportedEncodingException was removed where unnecessary.
- Added type safety: Charset was used instead of String for encoding to enforce safer encoding usage.
Introduced a new helper method: Enhanced EOL detection logic with better structure and readability.
- Refactored logic: Made updates to ensure the proper handling of default values for encoding and file reading.
- Minor code cleanup: Added @NotNull annotations, refined variable declarations (final usage).
> refactor(xml): replace String-based encoding with `Charset` and improve EOL detection in `XMLReader`

- src/org/omegat/gui/scripting/ScriptingWindow.java
- Ensures proper visibility and thread-safety for the `start` variable in multi-threaded environments.
Fix the threading issue
-
-
-
> fix(threading): mark `start` field as `volatile` in `ScriptWorker`

- src/org/omegat/gui/properties/MultilineCellRenderer.java
- src/org/omegat/gui/properties/SingleLineCellRenderer.java
refactor
- MultilineCellRenderer:
- Added a check using instanceof to verify if the table is of type FlashingTable before proceeding with typecasting.
- SingleLineCellRenderer:
- Similarly added an instanceof check before casting the table to FlashingTable.
#1296
> refactor(gui): add `instanceof` check for safer casting in cell renderers

- src/org/omegat/tokenizer/LuceneJapaneseTokenizer.java
refactor
- Added a custom implementation of the equals() method to compare instances of TagJoiningFilter, ensuring all critical fields are checked for equality.
- Added a custom implementation of the hashCode() method to generate hash codes based on relevant fields, aligning with the equals() implementation.
- Included the Objects class in the imports to support the new logic.
#1296
> refactor(tokenizer): implement `equals` and `hashCode` in `TagJoiningFilter` for better object comparison

- build-logic/src/main/groovy/org.omegat.module-conventions.gradle
- build-logic/src/main/groovy/org.omegat.publish-conventions.gradle
- build-logic/src/main/groovy/org.omegat.version-conventions.gradle
- build.gradle
Sonatype changes the publish procedure to use OSSRH portal API and deprecate previous `oss.sonatype.org` site in 30, June. 2025. This PR update build configuration to publish omegat core library and modules onto Maven central. 
-
-
-
> chore(build): update publishing plugins and migrate repository configs to Nexus

- src/org/omegat/filters4/xml/xliff/Xliff1Filter.java
- Refactor
- Added helper methods:
- getRequiredAttribute(): Centralizes and simplifies attribute retrieval, with error handling for mandatory attributes, and replace try-catch-null-exception anti-pattern.
- handleMrkElement(), handleDefaultElement(), and others: Modularized the processing of XML elements for better readability.
- Dedicated methods for handling specific end elements (handleFileEndElement, handleGroupEndElement, etc.).
- Improved code clarity:
- Removed inline verbose switch case logic by delegating to helper methods.
- Replaced repetitive patterns with reusable functions.
- Minor code cleanup:
- Removed outdated comments and cleaned unused code.
- Simplified generics in target initialization (new LinkedList<>()).
- Errors centralized: Introduced better exception handling …
> fix(filters4/xliff1):  fix the anti-pattern that catch the null pointer exception and refactor complex switch-case blocks

- src/org/omegat/util/TMXWriter2.java
- src/org/omegat/util/TmxEscapingWriterFactory.java
- test/data/tmx/test-save-tmx14.tmx
- test/src/org/omegat/util/TMXWriterTest.java
- test/src/org/omegat/util/TmxEscapingWriterTest.java
- TMX writer output in 6.1 should be the same as in 6.0
* https://sourceforge.net/p/omegat/feature-requests/1749/
- update TMX test expectation for level2 write
- use double quote for attribute
- format indentation and empty line
- Add TmxEscapingWriterFactory class and unit test with ordinary string, "< & >", Surrogate Pair and invalid one.
- Use TmxEscapingWriterFactory in TMXWriter2 for TEXT writer
`com.sun.xml.bind.marshaller#escape` which is ultimately OmegaT 6.0 and before use is as follows;
```java
public void escape(char[] ch, int start, int length, boolean isAttVal, Writer out) throws IOException {
int limit = start + length;
for(int i = start; i < limit; ++i) {
char c = ch[i];
if (c == '&' || c == '<' || c == '>' || c == '\r' || c == '\n' …
```
> feat: update tmx writer, escaper, and unit test

- src/org/omegat/Main.java
- src/org/omegat/core/spellchecker/SpellCheckerManager.java
- src/org/omegat/filters2/master/PluginUtils.java
- src/org/omegat/languagetools/LanguageClassBroker.java
- test-acceptance/src/org/omegat/TestMainInitializer.java
This Pull Request refactors and enhances the plugin loading mechanism in the PluginUtils class. It replaces individual class loaders for "theme" and "language" and the other plugins with a unified approach using EnumMap for managing multiple types of plugins. Additionally, it improves modularity and readability by introducing helper methods and consolidating repetitive logic.
- Enhancement
- Refactoring
- Refactoring ClassLoader Management:
- Replaced individual loaders (THEME_CLASSLOADER, LANGUAGE_CLASSLOADER) with an EnumMap (MAINCLASSLOADERS) to manage MainClassLoader instances per PluginType.
- Introduced Improved Plugin Initialization Workflow:
- Separated logic for locating plugins (initializePluginLocations), processing manifests (processPluginManifests), …
> feat(core/classloaders): use individual class loader for each plugin types

- test-acceptance/src/org/omegat/gui/dialogs/ProjectPropertiesDialogTest.java
Acceptance test for `ProjectPropertiesDialog` is flaky. This PR add more wait to fix the issue.
- Test
- Insert wait
- Additional assertion to mandate enable the component
-
> test: enhance ProjectPropertiesDialogTest with additional validations for UI elements

- release/changes.txt
- src/org/omegat/core/data/ProjectTMX.java
- src/org/omegat/core/matching/NearString.java
- src/org/omegat/core/statistics/FindMatches.java
- test/data/tmx/penalty-010/segment_1.tmx
- test/data/tmx/test-multiple-entries.tmx
- test/src/org/omegat/core/statistics/FindMatchesTest.java
Backport PR #963
- https://sourceforge.net/p/omegat/bugs/1251/
- Backport test case from PR #963
- Backport core fix from PR #963
- Extend NearString.Scores to hold penalty
- Update FindMatches.search to handle segmented search with penalty
> [BUGS#1251][6.0][backport] fix: FindMatches#search ignore penalty when segmented matches

- src/org/omegat/gui/glossary/GlossarySearcher.java
- src/org/omegat/gui/issues/IssuesPanelController.java
- test/src/org/omegat/gui/glossary/FindGlossaryThreadTest.java
- Checking for problems throws error: "Comparison method violates its general contract"
- https://sourceforge.net/p/omegat/bugs/1279/
-- Refactored `sortGlossaryEntries` to return a list and ensure null safety.
- Extracted issue provider logic in IssuesPanelController into a separate method for better readability and maintainability.
- Updated tests and adjusted method usage to align with these changes.
- Fix the IllegalArgument Error on sort with filter(Objects::nonNull) enforcement
- Trying to fix BUGS#1279
> [6.0][BUGS#1279]fix: glossary sorting and issue handling logic

- compose.yml
- test-integration/docker/client/Dockerfile
- test-integration/docker/client/entrypoint.sh
Add gradle cache for integration test container
- Improve test
- Added a new volume, gradle-cache, in compose.yml for Gradle dependency caching.
- Updated the entrypoint.sh script to handle Gradle dependency caching:
- Set up a GRADLE_USER_HOME environment variable pointing to the cache.
- Computed a hash based on build configuration files to determine cache validity.
- Implemented logic to download dependencies if the cache is outdated or missing.
- Cleaned up old cache markers keeping the most recent three for flexibility.
- Displayed cache statistics like size and configuration count.
> feat(gradle): implement dependency caching mechanism in integration tests

- aligner/build.gradle
- build-logic/src/main/groovy/org.omegat.jaxb-conventions.gradle
- build.gradle
- gradle/libs.versions.toml
- src/org/omegat/core/segmentation/SRX.java
- src/org/omegat/core/statistics/StatsResult.java
- src/org/omegat/filters2/master/FilterMaster.java
- src/org/omegat/gui/glossary/GlossaryReaderTBX.java
- src/org/omegat/util/ProjectFileStorage.java
- src/schemas/filters.xsd
- src/schemas/tmx14.xjb
- test/src/org/omegat/filters2/master/FilterMasterTest.java
- Update JAXB code generator to 4.0.x
= https://sourceforge.net/p/omegat/feature-requests/1761/
- Updated schema references to use `jakarta` namespace in compliance with JAXB 3.0.
- Tweak JAXB api package from javax.xml.* to jakarta.xml.*
- Bump maligna@4.0.0 which based on JAXB 4
- Update javax.xml.bind:jaxb.xml.bind-api:2.0.5 to jakarta.xml.bind:jakarta.xml.bind-api:4.0.2
- Update org.glassfish.jaxb:jaxb-xjc:2.3.1 to org.glassfish.jaxb:jaxb-xjc:4.0.5
- Update org.glassfish.jaxb:jaxb-runtime:2.3.0 to org.glassfish.jaxb:jaxb-runtime:4.0.5
- Update com.fasterxml.jackson.module:jackson-module-jaxb-annotations:2.16.1 to com.fasterxml.jackson.module:jackson-module-jakarta-xmlbind-annotations:2.16.1
retry of …
> feat: bump jaxb library to 4 and schema to version 3.0

- build-logic/src/main/groovy/org.omegat.document-conventions.gradle
- build.gradle
Fix bug that build system does not copy document in the distribution
- Document the location of the manual
- https://sourceforge.net/p/omegat/documentation/444/
- Update build.gradle 'distributions' section
- Avoid dynamic contents reference
- Temporary fix of the build system bug.
> fix(gradle): `docs` task output distribution

- test-acceptance/src/org/omegat/gui/align/AlignerWindowTest.java
- test-acceptance/src/org/omegat/gui/dialogs/AboutDialogTest.java
- test-acceptance/src/org/omegat/gui/dialogs/ConflictDialogTest.java
- test-acceptance/src/org/omegat/gui/dialogs/ProjectPropertiesDialogTest.java
- test-acceptance/src/org/omegat/gui/editor/EditorTextAreaIntroTest.java
- test-acceptance/src/org/omegat/gui/editor/EditorTextLoadedTest.java
- test-acceptance/src/org/omegat/gui/editor/EditorUtilsGUITest.java
- test-acceptance/src/org/omegat/gui/glossary/GlossaryTextTest.java
- test-acceptance/src/org/omegat/gui/issues/IssuesPanelTest.java
- test-acceptance/src/org/omegat/gui/main/TestMainWindowMenuHandler.java
- test-acceptance/src/org/omegat/gui/matches/FuzzyMatchesSegmentsTest.java
- test-acceptance/src/org/omegat/gui/matches/MatchesTextExternalTmTest.java
- test-acceptance/src/org/omegat/gui/matches/MatchesTextTest.java
- test-acceptance/src/org/omegat/gui/properties/SegmentPropertiesAreaTest.java
This Pull Request adds assertNotNull(window) checks to multiple test files to ensure that the window object is properly initialized during GUI testing.
refactor
- Added assertNotNull(window) assertions to 14 test files across various GUI-related test classes.
- Minor code cleanup in TestMainWindowMenuHandler.java by removing unused overridden methods.
> test: add null checks for `window` in GUI tests to improve robustness

- config/spotbugs/exclude.xml
- src/org/omegat/languagetools/LanguageToolNetworkBridge.java
This Pull Request includes both the removal of a class from a configuration and significant refactoring in the LanguageToolNetworkBridge class to improve code clarity and server termination handling.
- refactor
- 
- Update to exclude.xml:
- Removed exclusion for org.omegat.languagetools.LanguageToolNetworkBridge.
- Refactoring of LanguageToolNetworkBridge.java:
- Removed localPort field and associated logic for local server socket termination.
- Refactored fields for better readability by splitting declarations into separate lines.
- Enhanced the stop method for improved server shutdown handling:
- Added checks for server liveness (isAlive).
- Employed timeout mechanisms and forceful destruction for smoother termination.
- Minor formatting and restructuring for clarity.## Pull request …
> refactor(languagetools): enhance `LanguageToolNetworkBridge` stop logic and remove unused SpotBugs exclusions

- test-acceptance/src/org/omegat/gui/dialogs/ConflictDialogTest.java
Fix fraky acceptance test case.
- Added assertTrue to verify the correct behavior of latch.await with an increased timeout value (from 5 to 10 seconds).
- Introduced fail statements to handle scenarios where tests are interrupted due to timeouts, providing clearer debugging information.
> test(gui): extend timeout and add interruption handling in `ConflictDialogTest`

- src/org/omegat/core/data/SyncTMX.java
refactor
- Replaced explicit generic type declarations with the diamond operator for brevity.
- Added `@NotNull` annotations to enhance null safety.
- Simplified map population using `putAll` instead of looping through entries.
- Removed unused exception `WriteFailedException`.
> refactor(core): use diamond operator, add `@NotNull` annotations, and optimize map population in `SyncTMX`

- src_docs/manual/ja/HowTo_TranslateOtherFiles.xml
`ライセンス` が `サイセンス` となっていました。
- documentation
> 'licence' translation type

- src/org/omegat/languagetools/LanguageToolNativeBridge.java
When loading project without English, OmegaT throws exception in log file.
-  LanguageTool failed to load en-US when project is other than English
- https://sourceforge.net/p/omegat/bugs/1303/
- Change `LanguageToolNativeBridge` always load English LT module
> fix(LT): always load LT English module

- release/changes.txt
- src/org/omegat/filters3/xml/XMLFilter.java
- test/data/xml/文件/test.dtd
- test/data/xml/文件/test.xml
- test/src/org/omegat/filters3/XMLFilterTest.java
OmegaT 6.0.x does not handle path with CJK character properly.
- Unable to import a team project to a path containing Chinese characters(
- https://sourceforge.net/p/omegat/bugs/1302/
- Add reproducible as functional test
- `XMLFilter#processFile` to set system ID with URL encoded string.
> [6.0][BUGS#1302] XML filters does not handle DTD path with CJK characters properly 

- src/org/omegat/filters3/xml/XMLFilter.java
- test/data/xml/文件/test.dtd
- test/data/xml/文件/test.xml
- test/src/org/omegat/filters3/XMLFilterTest.java
- Unable to import a team project to a path containing Chinese characters
- https://sourceforge.net/p/omegat/bugs/1302/
- Add reproducible as functional test
- XMLFilter#processFile to set system ID with URL encoded string.
> [BUGS#1302] XML filters does not handle DTD path with CJK characters properly

- build.gradle
- release/changes.txt
- src/org/omegat/filters2/po/PoFilter.java
- src/org/omegat/util/MagicComment.java
- src/org/omegat/util/TMXReader2.java
Bump dependencies which has vulnerbility
- refactor
- dependency
- [6.0] [Security] vulnerability on dependencies
- https://sourceforge.net/p/omegat/bugs/1293/
- Bump commons-io, ivy, jgit and bouncycastle
- replace deprecated constructor in commons-io methods with recommended builder
-
> [6.0][BUGS#1293] chore: Bump dependencies to avoid vulnerability

- test-integration/docker/client/Dockerfile
- test-integration/docker/client/entrypoint.sh
This PR intend to add locales with UTF-8 in a container configuration on the integration test.
A current source tree have a non-ascii path name, which cause compile error on ASCII environment.
This fix the issue.
- Add locales package in the client container
- Generate `en_US.UTF-8` locale
- Enforce locale to be `en_US.UTF-8`
> chore(test-integ/container): Enforce operations in UTF-8

- build-logic/src/main/groovy/org.omegat.module-conventions.gradle
- config/checkstyle/suppressions.xml
- src/org/omegat/Bundle.properties
- src/org/omegat/core/data/PluginInformation.java
- src/org/omegat/filters2/master/PluginUtils.java
- src/org/omegat/gui/preferences/view/PluginDetailsPane.java
- src/org/omegat/gui/preferences/view/PluginInfoTableModel.java
- src/org/omegat/gui/preferences/view/PluginsPreferencesController.java
- src/org/omegat/gui/preferences/view/PluginsPreferencesPanel.form
- src/org/omegat/gui/preferences/view/PluginsPreferencesPanel.java
- src/org/omegat/util/PluginInstaller.java
Port new preferences/plugins view from PR #226
- Preference->Plugin dialog show plugin information in 3-pain
-    https://sourceforge.net/p/omegat/feature-requests/1549/
- Plugin preference table order (external first)
-   https://sourceforge.net/p/omegat/feature-requests/1545/
- Added a PluginDetailsPane to display detailed plugin information in the preferences UI.
- Refactored the PluginInformation and PluginInstaller functionalities to improve modularity and readability.
- Introduced new plugin statuses (e.g., "updatable", "uninstalled"), and localized their labels.
- Adjusted the PluginsPreferencesPanel layout for improved user interaction.
- Reworked PluginInfoTableModel to simplify plugin info presentation and column management.
- Included new …
> refactor(ui/plugin): enhance plugin management and table views

- src/org/omegat/filters2/po/PoFilter.java
- src/org/omegat/gui/comments/CommentsTextArea.java
- src/org/omegat/util/StringUtil.java
- test/data/filters/po/file-POFilter-multilines.po
- test/src/org/omegat/filters/POFilterTest.java
This PR is intended to reproduce BUGS#1305 and set proper target behavior for the multi-line continuation of the PO file format.
- Refactor
- .PO filter bug: display issue when a msgctxt spans several lines
- https://sourceforge.net/p/omegat/bugs/1305/
- refactor `POoFilter#processPoFile` private method to split multiple internal methods with the single purpose method principle.
- Add test data and reproducible of the BUGS#1305
- The test case also includes a check for multiline msgid
- Add behavior check for '\n' in multiline messages
- The second commit should be failed.
- https://www.gnu.org/software/gettext/manual/html_node/More-Details.html
> fix(pofilter): support multi-line msgctxt 

- src/org/omegat/util/OStrings.java
The PR refactors the method loadBundle in the OStrings class to use a try-with-resources statement for better handling of resource management and to eliminate the redundant manual closing of the FileInputStream.
- Bug fix
- Replaced the traditional try-finally block with a try-with-resources statement to ensure the FileInputStream resource is properly and automatically closed.
-  Removed the explicit in.close() call, simplifying the code and making it less error-prone.
> refactor(util): use try-with-resources to safely manage resource bundle loading

- azure-pipelines.yml
- build-logic/src/main/groovy/org.omegat.verification-conventions.gradle
The Pull Request updates CI configuration and build logic files by renaming a job, adjusting conditions, and removing Java 21 test-related tasks for simplify.
There is no actual test difference among JVM versions.
- The TestOnJava17 job in azure-pipelines.yml was renamed to testOnLinux, and its condition was updated for better clarity or alignment with Linux testing.
- Removed the testOnJava21 task from verification-conventions.gradle which previously focused on testing with Java 21.
> chore(ci): update pipeline job and remove unused Gradle task

- test-acceptance/src/org/omegat/gui/align/AlignerWindowTest.java
- test-acceptance/src/org/omegat/gui/dialogs/AboutDialogTest.java
- test-acceptance/src/org/omegat/gui/dialogs/ConflictDialogTest.java
- test-acceptance/src/org/omegat/gui/dialogs/ProjectPropertiesDialogTest.java
- test-acceptance/src/org/omegat/gui/editor/EditorTextAreaIntroTest.java
- test-acceptance/src/org/omegat/gui/editor/EditorTextLoadedTest.java
- test-acceptance/src/org/omegat/gui/editor/EditorUtilsGUITest.java
- test-acceptance/src/org/omegat/gui/glossary/GlossaryTextTest.java
- test-acceptance/src/org/omegat/gui/main/TestCoreGUI.java
- test-acceptance/src/org/omegat/gui/matches/FuzzyMatchesSegmentsTest.java
- test-acceptance/src/org/omegat/gui/matches/MatchesTextExternalTmTest.java
- test-acceptance/src/org/omegat/gui/matches/MatchesTextTest.java
- test-acceptance/src/org/omegat/gui/properties/SegmentPropertiesAreaTest.java
- test/fixtures/org/omegat/util/LocaleRule.java
This Pull Request removes the use of the LocaleRule from unit tests. Instead, methods to set and restore the locale at the class level (applyLocaleForClass and restoreLocaleForClass) were introduced in LocaleRule.java. Relevant adjustments have been made in TestCoreGUI to integrate these new methods.
- refactor
- Removed @Rule annotations and LocaleRule instances from individual test files.
- Added applyLocaleForClass and restoreLocaleForClass methods in LocaleRule.java to manage locale setup and restoration at the class level.
- Integrated the applyLocaleForClass and restoreLocaleForClass methods into TestCoreGUI with @BeforeClass and @AfterClass annotations.
- move calls to UIDesignManager.initialize in Swing thread
> refactor(test): centralize `LocaleRule` setup in `TestCoreGUI`

- build.gradle
- Fix distribution task to move OmegaT.jar to dist folder root
- Fix the degraded tasks by PR#1632
- Fix the gradle task bug that caused the failure of weekly release
- Update build.gradle to use `project.property('org.omegat.omegatJarFilename')` instead of direct reference of the property 'omegatJarFilename'
- Here is a missing part when PR#1632 updated
> chore(gradle): fix distribution task to place OmegaT.jar

- src/org/omegat/core/data/RealProject.java
Fix a potential issue and reflect review comment in dev-ML.
- insert `projectTMX.clear()` before `projectTMX#load`
https://sourceforge.net/p/omegat/mailman/message/59208342/
This change should be #1564, but it is in #1566, it is a mistake when my making PRs.
> fix(core): clear `projectTMX` before loading new TMX file

- config/checkstyle/suppressions.xml
- src/org/omegat/core/statistics/Statistics.java
- src/org/omegat/core/statistics/StatsResult.java
- test/src/org/omegat/core/statistics/CalcMatchStatisticsTest.java
- test/src/org/omegat/core/statistics/FindMatchesTest.java
- test/src/org/omegat/core/statistics/TestingParseCallback.java
- test/src/org/omegat/core/statistics/TestingProject.java
- test/src/org/omegat/core/statistics/TestingStatsConsumer.java
`CalcMatchStatisticsTest` is flaky now and many duplications in the code.
This PR eliminate to streamline the test code and improve stability of the test.
- refactor
- Refactor internal classes of `CalcMatchStasticsTest` to raise upper package. 
- Use `Testing *` class name for implementation of the interface for test.
- Use latch for synchronize threading of the statistics calculation.
- Update `Statistics#writeStat` methods with NIO2 functions for robustness of IO operations
> refactor(test): stabilize and modularize CalcMatchStatisticsTest

- test/src/org/omegat/core/statistics/CalcMatchStatisticsTest.java
This PR is to stabilize flaky test by extending timeout from 5 to 15 seconds.
refactor
- Introduced a `TIMEOUT` constant to replace the hardcoded timeout value.
- Updated `future.get` call to use the new `TIMEOUT` for better test stability.
> test(statistics): extend timeout in `CalcMatchStatisticsTest`

- build-logic/src/main/groovy/org.omegat.windows-conventions.gradle
- Added a clean task to remove outdated distribution files before preparation.
- Refined up-to-date checks for `OmegaT.jar' with configuration phase file path evaluation.
- Adjusted task dependencies for better build flow.
- Simplified executable detection in `genDists` task.
chore(gradle): refine Windows conventions for InnoSetup custom messages processing
- Enhanced regex to avoid capture comments in `CustomMessages*.ini`.
- Updated file content processing to ensure accurate key prefixing with language codes.
- Improve list processing to replace `collect` with `collectMany` which do `filter and map` operation in Groovy idiom.
-
-
> chore(gradle): improve a windows-conventions to evaluate in the configuration stage for cache support

- gradle.properties
- local.properties.example
This PR to set Gradle parameters of JVM heap memory for run and test tasks. An acceptance test requires more memory than Gradle default.
- Update gradle.properties to add JVM parameters for run and test tasks
- Deprecate Windows signing parameters in local settings placeholders
-
> chore(gradle): set runner JVM parameters

- src/org/omegat/util/gui/JTextPaneLinkifier.java
- Notes and Glossary panes keep HTML link styling
- https://sourceforge.net/p/omegat/bugs/1252/
- Clear all links on the pane before putting hyper links
-
-
> Clean character attributes in notes pane before update

- src/org/omegat/Bundle.properties
- src/org/omegat/gui/editor/EditorController.java
- test-acceptance/src/org/omegat/gui/editor/EditorTextLoadedTest.java
Update editor title to be special when first time loading to fix the BUGS#909.
- Wrong file name in the editor pane
- https://sourceforge.net/p/omegat/bugs/909/
- Added a new string resource GUI_SUBWINDOWTITLE_Editor_Loading to Bundle.properties for displaying a user-friendly loading message.
- Updated the editor title handling logic in EditorController.java to use the new string resource. 
- Removing updating of the entry number variables and call for `getCurrentFile`. This causes a selection change in the source file list dialog.
- Update acceptance test timeout to increase 15 seconds from 10.
> fix(core): [BUGS#909] update editor title to indicate loading state

- src/org/omegat/gui/editor/autocompleter/AutoCompleter.java
@aaron proposed the fix for OmegaT 5.3 development window,  but it was not merged.
> I've already cut the release, so it won't be included. The next release it could be included in would be 5.3.0, which won't be released probably for a while.
-  Autosuggestion and IME malfunctioning
- https://sourceforge.net/p/omegat/bugs/965/
- autocomplete pop-ups raised 100ms after input.
-
-
> [bugs:#965] Delay autocompleter popup until 100ms after last input

- build-logic/src/main/groovy/org.omegat.document-conventions.gradle
- build/release for documentation
- remove exclution of 'index.html' in manualZip tasks
- Solve the build error by recursive dependency with `copyDocIndex` task
Fix error on weekly release
> chore(gradle): remove unused exclusion rule in `manualZip` task
